APT::FTPArchive::Release {
  Origin "Augin";
  Label "Augin APT Repository";
  Suite "stable";
  Codename "stable";
  Architectures "amd64";
  Components "main";
  Description "Universal APT repository for Augin projects";
};
