keyStrings = {
    'lang':'Հայերեն',
    'alhabet':'աբգդեզէըթժիլխծկհձղճմյնշոչպջրսվտրցուփքևօֆ',
    'Channel list. Category: ':'Ալիքների ցանկ. Կատեգորիա: ',
    'EPG':'Ծրագիր',
    'Category':'Կատեգորիաներ',
    'Actions':'Գործողություններ',
    'Description':'Նկարագրություն',
    'Open in PiP':'Բացել PiP- ում',
    'Move channel up':'Տեղափոխեք ալիքը վերև',
    'Move channel down':'Տեղափոխեք ալիքը ներքև',
    'Delete channel':'Ջնջել ալիքը',
    'Add channel to category':'Ավելացնել ալիքը կատեգորիայի մեջ',
    'Add channel to favorites':'Ավելացնել ալիքը նախընտրելիների մեջ',
    'Channel parental control':'Ալիքների ծնողական հսկողություն',
    'Channel is not available!!!':'Ալիքը անհասանելի է!!!',
    'min':'րոպե',
    'Channel ':'Ալիք ',
    ' added to category ':' ավելացված է կատեգորիայում ',
    ' added to favorites':' ավելացված է նախընտրելիների ցանկում',
    'Favorites':'Նախընտրելիներ',
    'Select category to add channel':'Ընտրել կատեգորիան ՝ ալիք ավելացնելու համար',
    'Enter parental code':'Մուտքագրեք կոդը',
    'Wrong parental code !!!':'Սխալ կոդը !!!',
    '<br>Up<br>':'<br>Վերև<br>',
    '<br>Delete':'<br>Ջնջել',
    '<br>Add<br>to favorites':'<br>Ավելացնել<br>նախընտրելիների մեջ',
    '<br>Add<br>to category':'<br>Ավելացնել<br>կատեգորիայի մեջ',
    '<br>Parental<br>Control':'<br>Ծնողական<br>հսկողությունվ',
    '<br>Down':'<br>Ներքև',
    'Close':'Փակել',
    'Edit category name':'Խմբագրեկ կատեգորիայի անվանումը',
    'Category %1 already exists!':'Կատեգորիային %1 արդեն գոյություն ունի!',
    'Enter name for new category':'Մուտքագրեք նոր կատիգորայի անվանումը',
    '<br>More...<br>':'<br>Ավելին...<br>',
    '<br>Rename':'<br>Վերանվանել',
    '<br>Copy<br>category':'<br>Պատճենել<br>կատեգորիան',
    '<br>Back<br>':'<br>Հետ<br>',
    '<br>Create<br>category':'<br>Ստեղծել<br>категорию',
    'Category selection':'Կատեգորիայի ընտրություն',
    'Menu':'Մենյու',
    'Channel list':'Ալիքների ցանկ',
    'Move category up':'Տեղափոխել կատեգորիան վերև',
    'Move category down':'Տեղափոխել կատեգորիան ներքև',
    'Create category':'Ստեղծել կատեգորիա',
    'Rename category':'Վերանվանել կատեգորիան',
    'Copy category':'Պատճենել կատեգորիան',
    'Delete category':'Ջնջել կատեգորիան',
    'Su Mo Tu We Th Fr Sa':'Կիր Երկ Երք Չրք Հնգ Ուրբ Շբթ',
    'EPG and archive. Channel: ':'Ծրագիր և արխիվ. Ալիք: ',
    'By alphabet':'Ըստ այբուբենի',
    'Archive. Channel: ':'Արխիվ. Ալիք: ',
    'By time':'Ըստ ժամանակի',
    'Player info:':'Տեղեկություններ նվագարկիչի մասին:',
    'Device info:':'Տեղեկություններ սարքի մասին:',
    '- switch:':'- անցումը:',
    '- erase':'- ջնջել',
    '- move cursor':'- շարժվող կուրսոր',
    '- return without save':'- վերադառնալ առանց պահպանման',
    '- save':'- պահպանել',
    'Return to previous channel':'Վերադառնալ նախորդ ալիքին',
    'Call PiP / PiP exchange':'Բացել PiP / Փոխարինել PiP',
    'Info about TV program':'Տեղեկատվություն հեռուստածրագրի մասին',
    'Show player menu':'Ցույց տալ նվագարկիչի մենյուն',
    'Interface settings':'Ինտերֆեյսի կարգավորումները',
    'Show channel selection list':'Ցույց տալ ալիքի ընտրության ցուցակը',
    'Hide / Return':'Թաքցնել / Վերադառնալ',
    'Exit player':'Դուրս գալ նվագարկիչից',
    'Show EPG and archive for channel':'Ցույց տալ ալիքի EPG և արխիվը',
    'Channel category selection':'Ալիքների կատեգորիայի ընտրություն',
    'Toggle Aspect Ratio':'Փոխել "Էկրանի կողմերի հարաբերակցության" ռեժիմը (Aspect Ratio)',
    'Toggle Zoom Mode':'Փոխել խոշորացման ռեժիմը',
    'Switch sound track':'Փոխել ձայնային ուղին',
    'In live mode: <br/>':'Ուղիղ եթերի դիտման ռեժիմ:<br/>',
    'Channel selection by number':'Ընտրել ալիքը ըստ համարի',
    'Timeshift: to start of TV program':'Ժամանակի փոփոխություն: հաղորդման սկիզբ',
    'Timeshift: one minute back':'Ժամանակի փոփոխություն: մեկ րոպե հետ',
    '<br/><br/>In archive mode:<br/>':'<br/><br/>Արխիվի դիտման ռեժիմ:<br/>',
    'Pause/Play':'Դադար / Նվագարկում',
    'Stop playback and return to In live mode':'Դադարեցնել նվագարկումը և վերադառնալ ուղիղ հեռարձակման',
    'To start of TV program / Previous TV program':'Հաղորդման սկիզբ / Նախորդ հաղորդում',
    'Next TV program':'Հաջորդ հաղորդում',
    'Back / Forward for 1 minute':'Հետ / Առաջ 1 րոպե',
    'Back / Forward for 15 seconds':'Հետ / Առաջ 15 վայրկյան',
    'Back / Forward for 3 minutes':'Հետ / Առաջ 3 րոպե',
    'Back / Forward for 10 minutes':'Հետ / Առաջ 10 րոպե',
    'Show rewind window':'Ցույց տալ հետ/առաջի պատուհանը',
    'Description of remote control buttons':'Հեռակառավարման կոճակների գործառույթների նկարագրությունը',
    'Description of remote control buttons depending on the view mode':'Հեռակառավարման կոճակների գործառույթների նկարագրությունը `կախված դիտման ռեժիմից',
    'Set parental code':'Ստեղծել ծնողական կոդ',
    'Repeat parental code':'Կրկնել ծնողական կոդը',
    'Show list of channel archive records':'Ցույց տալ արխիվային ալիքների ցանկը',
    'Show list of channel archive records without duplication':'Ցույց տալ արխիվային ալիքների ցանկը առանց կրկնօրինակման',
    'Show Media Library':'Ցույց տալ մեդիա գրադարանը',
    'Rewind':'Հետ / Առաջ',
    'Close PiP':'Փակել PiP',
    'Parental control':'Ծնողական հսկողություն',
    'Change provider':'Փոխել օպերատորին',
    'Change provider - you can change the provider, and it will be remembered at the next start of player!':'Օպերատորի փոփոխություն - դուք կարող եք փոխել օպերատորին, և այն կհիշվի հաջորդ գործարկման ժամանակ!',
    'Restart player':'Վերագործարկել նվագարկիչը',
    // 'Restart player - after changing provider settings (as example)':'Վերագործարկել նվագարկիչը' - օրինակ՝ օպերատորը փոխելուց հետո:',
    'Description of remote control buttons':'Հեռակառավարման կոճակների նկարագրությունը',
    'About':'Տեղեկատվություն',
    'Player and device info':'Սարքավորման և նվագարկիչի տեղեկատվություն',
    'Donate <div class="btn" style="background-color:orange;">donate</div>':'Օգնություն նախագծին <div class="btn" style="background-color:orange;">donate</div>',
    'Voluntary donation for the development of project':'Կամավոր նվիրատվություն նախագծի զարգացման համար',
    'Settings saved':'Կարգավորումները պահպանված են',
    'no':'ոչ',
    'yes':'այո',
    'Records':'Ձայնագրություններ',
    'Previous':'Նախորդ',
    'Info':'Ինֆո',
    'Not reduce video when showing the list (bugfix)':'Մի նվազեցրեք տեսանյութը ցուցակը ցուցադրելիս (Bug fix)',
    'Black screen while switching the channel':'Ալիքը փոխելիս սև էկրան',
    'PiP window size':'PiP պատուհանի չափը',
    'small':'փոքր',
    'medium':'միջին',
    'large':'մեծ',
    'PiP window position':'PiP պատուհանի դիրքը',
    'top-right':'աջ-վերև',
    'bottom-right':'աջ-ժներքև',
    'left-bottom':'ձախ-ներքև',
    'top-left':'ձախ-վերև',
    'Number of rows in lists':'Ցուցակներում տողերի քանակը',
    'Distance between lines in lists':'Ցուցակներում տողերի միջեւ հեռավորությունը',
    'Font type':'Տառատեսակի տեսակը',
    'volume':'ձայնի բարձրություն',
    'paging':'էջադրում',
    'Nothing':'Ոչինչ',
    'Exit':'Ելք',
    'Joystick':'Ջոյստիկ',
    'Button %1 function when viewing':'Կոճակը գործառույթը %1 դիտելիս',
    'Button function %1 when viewing archive':'Կոճակը գործառույթը %1 արխիվ դիտելիս',
    'Channels':'Ալիքները',
    'Remote (color buttons N/A)':'Հեռակառավարման վահանակը առանց գունավոր կոճակների',
    'Remote (number buttons N/A)':'Հեռակառավարման վահանակը առանց համարի կոճակների',
    'Timezone':'Ժամային գոտի',
    'Sleep timer':'Քնի ժամաչափ',
    'off':'անջատված',
    '30 minutes':'30 րոպե',
    '1 hour':'1 ժամ',
    '2 hours':'2 ժամ',
    'Infobar display timeout, s':'Ինֆոբարի ցուցադրման թայմաութ, վ',
    '"Sliding" infobar':'"Սլայդինգ" ինֆոբար',
    'Interface transparency':'Թափանցիկ ինտերֆեյս',
    'Volume step, %':'Ձայնի բարձրության քայլ, %',
    'List location':'Ցուցակի դիրքը',
    'right':'աջ',
    'left':'ձախ',
    'Color spectrum':'Գունային գամմա',
    'select':'ընտրել',
    'Permanent clock on screen':'Մշտական ​​ժամացույց էկրանին',
    'Show channel number in list':'Ցույց տալ ալիքի համարը ցուցակում',
    'Show picons in channel list':'Ցույց տալ ալիքի պիկոններ ցուցակում',
    'Show channel name in list':'Ցույց տալ ալիքի անունները ցուցակում',
    'Show progress in channel list':'Ցույց տալ պռոգռեսը ցուցակում',
    'Show archive availability in list':'Ցույց տալ արխիվի առկայությունը ցուցակում',
    'Show scrollbar in list':'Ցույց տալ ոլորման սանդղակը ցուցակում',
    'Preview in channel list':'Նախադիտումը ալիքների ցանկում',
    'always':'միշտ',
    'on ':'ըստ ',
    'Number of next TV programs in channel list':'Հաջորդ հեռուստածրագրերի քանակը ալիքների ցուցակում',
    'Channel list editing style':'Ցուցակների խմբագրման ոճը',
    'All categories':'Բոլոր կատեգորիաները',
    '"Favorites"':'"նախընտրելիներ"',
    'Editor':'Խմբագիր',
    'built-in':'ներկառուցված',
    'native':'բնիկ',
    'HDMI-CEC support (on/off from TV)':'HDMI-СEC աջակցություն (միացնել/անջատել TV-ից)',
    'Type of player for streaming':'Նվագարկչի տեսակը',
    'Autostart of player':'Նվագարկչի ավտոմատ մեկնարկը',
    'Buffer Size, s':'Բուֆերի չափը, վ',
    'Choose from':'Տարբերակներ',
    'Settings':'Կարգավորումներ',
    'Change value':'Փոխել արժեքը',
    'Save Settings':'Պահպանել կարգավորումները',
    'To begining':'Սկիզբը',
    'Live':'Ուղիղ հեռարձակում',
    ' m ':' րոպե ',
    ' s':' վրկ',
    '1 minute':'1 րոպե',
    '10 Seconds':'10 վայրկյան',
    'Go to':'Գնալ',
    'Archive - begin':'Արխիվ - հաղորդման սկիզբը',
    'Pause':'Դադար',
    'Play':'Նվագարկումը',
    'Shutdown after %1 seconds<br/><br/>Cancel - any action':'Անջատվելու է %1 վարկյանից<br/><br/>Չեղարկում - ցանկացած գործողություն',
    'Do you want to exit player?':'Դուք ցանկանում եք դուրս գալ նվագարկիչից?',
    'Color':'Գույն',
    'Saturation':'Հագեցվածությունը',
    'Yellow':'Դեղին',
    'Green':'Կանաչ',
    'Blue':'Կապույտ',
    'Set':'Տեղադրել',
    'Restart stream':'Վերսկսել հոսքը',
    'Favorites':'Նախընտրելիներ',
    'All':'Բոլորը',
    '<br/>Processing the channel list...':'<br/>Ալիքիների ցուցակի մշակում...',
    '<br/>Start playback...':'<br/>Սկսել նվագարկումը...',
    '<br/>Channel list not received !!!':'<br/>Ալիքի ցուցակը չի ստացվել։!!',
    'Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>':'Ալիքի ցուցակը չի ստացվել!!!<br/><br/>Մուտքագրեք օպերատորի տվյալները և վերագործարկեք նվագարկիչը!!!<br/><br/>',
    'Error getting channel list !!!':'Ալիքների ցուցակը ստանալու սխալ!!!',
    'system':'համակարգ',
    'Choose provider':'Ընտրեք օպերատորին',
    '<br>Rewind<br>':'<br>Հետ / Առաջ<br>',
    '<br>Menu':'<br>Մենյու',
    '<br>Pause<br>':'<br>Դադար<br>',
    '<br>Toggle<br>sound track':'<br>Անցնել<br>Սաունդթրեք',
    '<br>Live':'<br>Ուղիղ Եթեր',
    '<br>Previous<br>channel':'<br>Նախորդ<br>ալիք',
    '<br/><b>Failed to load provider script !!!</b>':'<br/><b>Չհաջողվեց բեռնել օպերատորի սկրիպտը!!!</b>',
    '<br/>Loading provider %1 script ...':'<br/>Օպերատորի սկրիպտի ներբեռնում %1 ...',
    '<br/>Loading settings...':'<br/>Կարգավորումների բեռնումը...',
    '<br/>Loading channel list...':'<br/>Բեռնել ալիքների ցանկը...',
    'Choose language':'Ընտրեք լեզուն',
    'Change interface language':'Փոխել ինտերֆեյսի լեզուն',
    'Aspect':'Ասպեկտ',
    'Audio':'Սաունդթրեք',
    'Stalker portals':'Ստալկեր պորտալները',
    'm3u-m3u8 playlists':'m3u-m3u8 տեսացանկեր',
    '<br/>Loading STB...':'<br/>STB Բեռնում...',
    '<br/>Setup STB...':'<br/>Կարգավորել STB...',
    'Save settings to storage':'Գրանցեք կարգավորումները USB կրիչի վրա',
    'Load settings from storage':'Վերականգնել կարգավորումները USB կրիչից',
    'Download':'Բեռնել',
    'Skip this version':'Բաց թողնել այս տարբերակը',
    'Volume control':'Ձայնի բարձրության կարգավորումներ',
    'Long button presses':'Երկար կոճակի սեղմում',
    'Download new version Android App':'Ներբեռնեք նոր տարբերակը',
    'To access you must enter url, username and password!':'Մուտք գործելու համար անհրաժեշտ է մուտքագրել հասցեն, մուտքանունը և գաղտնաբառը:',
    'Failed to load channel list!':'Չհաջողվեց բեռնել ալիքների ցանկը!',
    'Year':'Տարի',
    'Duration':'Տևողությունը',
    'Genre':'Ժանր',
    'Country':'Երկիր',
    'Director':'Ռեժիսոր',
    'Actors':'Դերերում',
    'Release date':'Թողարկման ամսաթիվը',
    'Rating':'Վարկանիշ',
    'Season':'Սեզոն',
    'Episodes':'Դրվագներ',
    'VOD':'Ֆիլմեր եւ տեսանյութեր',
    'TV series':'Սերիալներ',
    'Episode':'Դրվագ',
    'Download! Wait ...':'Բեռնում! Սպասեք ...',
    'Server':'Սերվեր',
    'URL':'Հասցե',
    'Username':'Մուտքանուն',
    'Password':'Գաղտնաբառ',
    'Stream type':'Հոսքի տեսակը',
    'Account info':'Բաժանորդագրության տեղեկատվություն',
    'Select server number from 1 to 6 to save data':'Ընտրեք սերվերի համարը 1-ից 6, Տվյալների պահպանման համար',
    ' (after changing, restart player)':' (փոփոխությունից հետո անհրաժեշտ է վերագործարկել նվագարկիչը)',
    ' (after changing, switch the channel!)':' (փոփոխությունից հետո միացրեք ալիքը!)',
    'Enter URL of server':'Խմբագրել սերվերի հասցեն',
    'Enter username':'Մուտքանունի խմբագրում',
    'Enter password':'Գաղտնաբառի խմբագրում',
    'Select stream type':'Ընտրեք հոսքերի տեսակը',
    '??? No channel name':'??? Ալիքի անունը լրացված չէ',
    'Playlist URL':'Տեսացանկի հասցե',
    'Archive hours':'Արխիվի տևողություն',
    'Enter playlist URL':'Մուտքագրեք տեսացանկի հասցեն',
    'Enter playlist archive hours':'Մուտքագրեք արխիվի տևողություն տեսացանկի համար',
    'show on-screen keyboard':'ցույց տալ էկրանի ստեղնաշարը',
    'Sleep without leaving player':'Քնել առանց թողնելով նվագարկիչ',
    'PiP is not available!':'PiP անհասանելի է!',
    'NORMAL':'ՍՈՎՈՐԱԿԱՆ',
    'ENLARGE':'ԱՃ',
    'MAKE_WIDER':'ԼԱՅՆԱՑՆԵԼ',
    'NON_LINEAR_STRETCH':'ՍԽԱԼ ՓՈՓԽՈՒԹՅՈՒՆ',
    'NON_LINEAR_STRETCH_TO_FULL_SCREEN':'ԱՄԲՈՂՋ ԷԿՐԱՆԻ ՍԽԱԼ ՓՈՓԽՈՒԹՅՈՒՆ',
    'MAKE_TALLER':'ԵՐԿԱՐԱՑՆԵԼ',
    'CUT_EDGES':'ԵԶՐԵՐԻ ԿՏՐՈՒՄ',
    'FULL_SCREEN':'ԱՄԲՈՂՋԱԿԱՆ ԷԿՐԱՆ',
    'STRETCH_TO_FULL_SCREEN':'ՓԱԽԵԼ ԱՄԲՈՂՋ ԷԿՐԱՆ ՌԵԺԻՄԻ',
    'Background color':'Ֆոնի գույնը',
    'Brightness':'Պայծառություն',
    '3 hours':'3 ժամ',
    'Restart stream / Live':'Վերսկսել հոսքը / Ուղիղ հեռարձակում',
    '- keyboard': '- ստեղնաշար',
    'Media':'Մեդիաթեկ',
    'String for search':'Որոնման տող',
    'Playlist Name':'Տեսացանկի անվանումը',
    'Enter playlist Name':'Գրել տեսացանկի անվանումը',
    'Media Library URL':'Մեդիաթեկի հասցեն',
    'Enter Media Library URL':'Գրել մեդիաթեկի հասցեն',
    'Playlist':'Տեսացանկ',
    'Select playlist':'Ընտրեք տեսացանկը',
    'Edit':'Խմբագրել',
    'Load':'Ներբեռնում',
    'Edit playlist data':'Տեսացանկի տվյալների խմբագրում',
    'Select portal':'Ընտրեք պորտալը',
    'Portal Name':'Պորտալի անվանումը',
    'Enter Portal Name':'Գրել պորտալի անվանումը',
    'Edit portal data':'Պորտալի տվյալների խմբագրում',
    'without':'առանց',
    'Settings STB':'Սարքի կարգավորումներ',
    'Soft audio render':'Ծրագիր վերծանել աուդիոն',
    'Long press horizontal arrows for volume control':'Երկար սեղմեք հորիզոնական սլաքները ձայնի կարգավորման համար',
    'Yes':'Այո',
    'Back':'Հետ',
    'Show providers?':'Ցույց տալ օպերատորներին?',
    'Hide providers?':'Թաքցնել օպերտորներին?',
    'Show provider settings?':'Ցույց տալ օպերատորի կարգավորումները?',
    'Hide provider settings?':'Թաքցնել օպերատորի կարգավորումները?',
    'Clear all settings?':'Մաքրել բոլոր կարգավորումները?',
    'Timer':'Ժամանակաչափ',
    'Set timer?':'Սահմանել ժամանակաչափ?',
    'Remove timer?':'Հեռացնել ժամանակաչափը?',
    'Timer: switch to channel?':'ժամանակաչափ: անցնել ալիքին?',
    ' (if archive exists)':' (ալիքի արխիվի առկայության դեպքում)',
    'Preffered audio track':'Նախընտրելի ձայնի բարձրության',
    'Information':'Տեղեկատվություն',
    'Lists settings':'Ցուցակների կարգավորումները',
    'Channel list settings':'Ալիքների ցանկի կարգավորումները',
    'Buttons settings':'Հեռակառավարման կոճակների կարգավորումները',
    'Subtitle':'Ենթագրեր',
    'Switch subtitle':'Փոխել ենթագրերը',
    'Off':'Անջատել',
    'Not found':'Բացակայում են',
    'History of watched movies':'Դիտումների պատմություն',
    'Continue watching?':'Շարունակել դիտելը?',
    'Add to favorites':'Ավելացնել նախընտրելիների ցանկում',
    'Delete':'Ջնջել',
    'Info about current stream':'Տեղեկատվություն ընթացիկ հոսքի մասին',
    'Stop':'Կանգ',
    'Playlist file':'Տեսացանկի ֆայլ',
    'Select playlist file':'Ընտրեք տեսացանկի ֆայլը',
    'Graphical indication':'Գրաֆիկական ցուցադրություն',
    'Background color of selected item':'Ընտրության ֆոնի գույնը',
    'Default':'Գործարանային',
    'Not supported!':'Չի ապահովվում!',
    'Menu items settings':'Կարգավորել ցանկը',
    'Select menu items':'Ընտրեք ցանկի կետերը',
    'Protect Adult Channels':'Մեծահասակների ալիքների պաշտպանություն',
    'Protect Settings':'Պաշտպանություն կարգավորումներ',
    'Protect Change Provider':'Օպերատորի փոփոխության պաշտպանություն',
    'Infobar settings':'Ինֆոբարի կարգավորումներ',
    'Show when switching':'Ցույց տալ փոխելու ժամանակ',
    'Show when changing program':'Ցույց տալ, երբ փոխվում է ծրագիրը',
    'Show when rewind':'Ցույց տալ հետ/առաջի ժամանակ',
    'Archive. Category: ':'Արխիվ. Կատեգորիա: ',
    'Sort channels':'Տեսակավորում',
    '"As Is"':'"Ինչպես որ կա"',
    'Load playlist':'Բեռնել տեսացանկը',
    ' (after changing, load playlist)':' (փոփոխությունից հետո, բեռնել տեսացանկը)',
    'Statistics of current stream':'Ընթացիկ հոսքի վիճակագրություն',
    'Search':'Որոնում',
// 14.6
    'Behavior of %1/%2 buttons in lists':'Կոճակների կարգավորում %1/%2 ցուցակում',
    'begin/end':'սկիզբ/ավարտ',
    'Position shift -10 seconds after pause':'դադարից հետո փոխել դիրքը -10 վարկյան',
    'Remember previous channels':'Հիշել նախորդ ալիքները',
    'History in Media Library':'Դիտումների պատմություն մեդիատեկում',
// 5.11
    'Manage settings':'Կարգավորումների կառավարում',
    'Save settings':'Պահպանել կարգավորումները',
    'Load settings':'Ներբեռնել կարգավորումները',
    'Clear settings':'Ջնջել կարգավորումները',
    'Send settings':'Ուղարկել կագավորումները դեպի սերվեր',
    'Settings sended!':'Կարագավորումները ուղարկված է սերվեր!',
    'For download settings file open':'Բացեք կարգավորումների ներվեռման համար',
    'and enter code':'և մուտքագրեք կոդը',
    'or scan':'կամ սկանավորեք',
    'Send request':'Ուղարկել հարցում սերվերին',
    'Request sended!':'Հարցումը ուղարկված է սերվերին!',
    'For upload settings file open':'Բացեք կարգավորումների բեռման համար',
    'Enter Provider Code':'Մուտքագրեք օպերատորի կոդը',
    'Error Code!':'Կոդի սխալ!!!',
    'For enter value open':'Բացեք արժեքի մուտքագրման համար',
    'First Run Setup':'Առաջին գործարկման կարգավորումներ',
    'Enter Provider Code on PC or Phone':'Մուտքագրեք օպերատորի կոդը համակարգչով կամ հեռախոսով',
    'Manual setup':'Կարգավորել ձեռքով',
    'Access settings':'Մուտքի կարգավորումներ',
// 26.1
    'Script':'Սցենար',
    'Producer':'Պրոդյուսեր',
    'Operator':'Օպերատոր',
    'Composer':'Կոմպոզիտոր',
    'Artist':'Նկարիչ',
    'Installation':'Մոնտաժ',
    'Budget':'Բյուջե',
    'Audience':'Լսարան',
    'Premiere world':'Համաշխարհային պրեմիերա',
    'Display settings':'Нցուցադրման կարգավորումներ',
    'Age':'Տարիք',
    'Sort':'Դասավորում',
    'by name':'ըստ անվանման',
    'by adding':'ըստ ավելացման',
    'Order':'Կարգը',
    'asc':'աճման',
    'desc':'նվազման',
    'Language':'Լեզու',
    'Quality':'Որակ',
    'Show program name':'Ցույց տալով հաղորդման անվանումը',
    'Show description':'Ցույց տալով հաղորդման նկարագրությունը',
    'transparent':'թափանցիկ',
}
