keyStrings = {
    'lang':'беларуская',
    'alhabet':'абвгдеёжзійклмнопрстуўфхцчшыьэюя',
    'Channel list. Category: ':'Спіс каналаў. Катэгорыя: ',
    'EPG':'Праграма',
    'Category':'Катэгорыі',
    'Actions':'Дзеянні',
    'Description':'Апісанне',
    'Open in PiP':'Адкрыць у PiP',
    'Move channel up':'Перасунуць канал уверх',
    'Move channel down':'Перасунуць канал уніз',
    'Delete channel':'Выдаліць канал',
    'Add channel to category':'Дадаць канал у катэгорыю',
    'Add channel to favorites':'Дадаць канал у абраныя',
    'Channel parental control':'Бацькоўскі кантроль канала',
    'Channel is not available!!!':'Канал не даступны!!!',
    'min':'хвілін',
    'Channel ':'Канал ',
    ' added to category ':' дададзены ў катэгорыю ',
    ' added to favorites':' дададзены ў абраныя',
    'Favorites':'Абраныя',
    'Select category to add channel':'Выбар катэгорыі для дадання канала',
    'Enter parental code':'Увядзіце бацькоўскі код',
    'Wrong parental code !!!':'Няправільны бацькоўскі код !!!',
    '<br>Up<br>':'<br>Уверх<br>',
    '<br>Delete':'<br>Выдаліць',
    '<br>Add<br>to favorites':'<br>Дадаць<br>у абраныя',
    '<br>Add<br>to category':'<br>Дадаць<br>у катэгорыю',
    '<br>Parental<br>Control':'<br>Бацькоўскі<br>кантроль',
    '<br>Down':'<br>Уніз',
    'Close':'Зачыніць',
    'Edit category name':'Рэдагаванне назвы катэгорыі',
    'Category %1 already exists!':'Катэгорыя %1 ужо існуе!',
    'Enter name for new category':'Увядзіце назву для новай катэгорыі',
    '<br>More...<br>':'<br>Яшчэ...<br>',
    '<br>Rename':'<br>Перайменаваць',
    '<br>Copy<br>category':'<br>Капіяваць<br>катэгорыю',
    '<br>Back<br>':'<br>Назад<br>',
    '<br>Create<br>category':'<br>Стварыць<br>катэгорыю',
    'Category selection':'Выбар катэгорыі каналаў',
    'Menu':'Меню',
    'Channel list':'Спіс каналаў',
    'Move category up':'Перасунуць катэгорыю ўверх',
    'Move category down':'Перасунуць катэгорыю ўніз',
    'Create category':'Стварыць катэгорыю',
    'Rename category':'Перайменаваць катэгорыю',
    'Copy category':'Капіяваць катэгорыю',
    'Delete category':'Выдаліць катэгорыю',
    'Su Mo Tu We Th Fr Sa':'Нд Пн Аў Ср Чц Пт Сб',
    'EPG and archive. Channel: ':'Праграма і архіў. Канал: ',
    'By alphabet':'Па алфавіце',
    'Archive. Channel: ':'Архіў. Канал: ',
    'By time':'Па часе',
    'Player info:':'Інфармацыя пра плэер:',
    'Device info:':'Інфармацыя пра прыладу:',
    '- switch:':'- пераключэнне:',
    '- erase':'- сцерці',
    '- move cursor':'- перасоўванне курсора',
    '- return without save':'- вярнуцца без захавання',
    '- save':'- запомніць',
    'Return to previous channel':'Зварот да папярэдняга канала',
    'Call PiP / PiP exchange':'Выклік PiP / Абмен крыніцамі PiP',
    'Info about TV program':'Выклік інфармацыі пра перадачу',
    'Show player menu':'Выклік меню плэера',
    'Interface settings':'Налады інтэрфейсу',
    'Show channel selection list':'Выклік спіса выбару канала',
    'Hide / Return':'Прыбраць інфармацыю / вярнуцца',
    'Exit player':'Выхад з плэера',
    'Show EPG and archive for channel':'Выклік праграмы перадач і архіва канала',
    'Channel category selection':'Выбар катэгорыі каналаў',
    'Toggle Aspect Ratio':'Пераключыць рэжым "Суадносіны бакоў экрана" (Aspect Ratio)',
    'Toggle Zoom Mode':'Пераключыць рэжым павелічэння',
    'Switch sound track':'Пераключыць дарожку гуку',
    'In live mode: <br/>':'У рэжыме прагляду прамога эфіру:<br/>',
    'Channel selection by number':'Выбар канала па нумары',
    'Timeshift: to start of TV program':'Таймшыфт: у пачатак перадачы',
    'Timeshift: one minute back':'Таймшыфт: на хвіліну назад',
    '<br/><br/>In archive mode:<br/>':'<br/><br/>У рэжыме прагляду архіва:<br/>',
    'Pause/Play':'Паўза/Прайграванне',
    'Stop playback and return to In live mode':'Спыніць прайграванне і вярнуцца да прамога эфіру',
    'To start of TV program / Previous TV program':'У пачатак перадачы / На папярэднюю перадачу',
    'Next TV program':'На наступную перадачу',
    'Back / Forward for 1 minute':'Назад / Наперад на 1 хвіліну',
    'Back / Forward for 15 seconds':'Назад / Наперад на 15 секунд',
    'Back / Forward for 3 minutes':'Назад / Наперад на 3 хвіліны',
    'Back / Forward for 10 minutes':'Назад / Наперад на 10 хвілін',
    'Show rewind window':'Выклік акенца перамоткі',
    'Description of remote control buttons':'Апісанне функцый кнопак пульта',
    'Description of remote control buttons depending on the view mode':'Апісанне функцый кнопак пульта, залежных ад рэжыму прагляду',
    'Set parental code':'Задайце бацькоўскі код',
    'Repeat parental code':'Паўтарыце бацькоўскі код',
    'Show list of channel archive records':'Выклік спісу запісаў архіва канала',
    'Show list of channel archive records without duplication':'Выклік спісу запісаў архіва канала без паўтораў',
    'Show Media Library':'Выклік медыятэкі',
    'Rewind':'Перамотка',
    'Close PiP':'Зачыніць PiP',
    'Parental control':'Бацькоўскі кантроль',
    'Change provider':'Змена правайдэра',
    'Change provider - you can change the provider, and it will be remembered at the next start of player!':'Змена правайдэра - Вы можаце змяніць правайдэра, і ён запомніцца пры наступным запуску!',
    'Restart player':'Перазапусціць плэер',
    // 'Restart player - after changing provider settings (as example)':'Перазапусціць плэер - напрыклад пасля змены налад правайдэра',
    'Description of remote control buttons':'Апісанне кнопак пульта',
    'About':'Інфармацыя',
    'Player and device info':'Інфармацыя пра плэер і прыладу',
    'Donate <div class="btn" style="background-color:orange;">donate</div>':'Дапамога праекту <div class="btn" style="background-color:orange;">donate</div>',
    'Voluntary donation for the development of project':'Самаахвотная дапамога на развіццё праекта',
    'Settings saved':'Налады захаваны',
    'no':'не',
    'yes':'так',
    'Records':'Запісы',
    'Previous':'Папярэдні',
    'Info':'Інфа',
    'Not reduce video when showing the list (bugfix)':'Не змяншаць відэа пры выкліку спіса (bugfix)',
    'Black screen while switching the channel':'Чорны экран пры пераключэнні канала',
    'PiP window size':'Памер акенца PiP',
    'small':'маленькае',
    'medium':'сярэдняе',
    'large':'вялікае',
    'PiP window position':'Становішча акенца PiP',
    'top-right':'права-верх',
    'bottom-right':'права-ніз',
    'left-bottom':'лева-ніз',
    'top-left':'лева-верх',
    'Number of rows in lists':'Колькасць радкоў у спісах',
    'Distance between lines in lists':'Адлегласць паміж радкоў у спісах',
    'Font type':'Тып шрыфту',
    'volume':'гучнасць',
    'paging':'гартанне',
    'Nothing':'Нічога',
    'Exit':'Выхад',
    'Joystick':'Джойсцік',
    'Button %1 function when viewing':'Функцыя кнопкі %1 пры праглядзе',
    'Button function %1 when viewing archive':'Функцыя кнопкі %1 пры праглядзе архіва',
    'Channels':'Каналы',
    'Remote (color buttons N/A)':'Пульт без каляровых кнопак',
    'Remote (number buttons N/A)':'Пульт без лічбавых кнопак',
    'Timezone':'Часавы пояс',
    'Sleep timer':'Таймер сну',
    'off':'адключаны',
    '30 minutes':'30 хвілін',
    '1 hour':'1 гадзіна',
    '2 hours':'2 гадзіны',
    'Infobar display timeout, s':'Таймаўт паказу інфабара, с',
    '"Sliding" infobar':'"Выязджае" інфабар',
    'Interface transparency':'Празрыстасць інтэрфейсу',
    'Volume step, %':'Крок гучнасці, %',
    'List location':'Размяшчэнне спісу',
    'right':'справа',
    'left':'злева',
    'Color spectrum':'Колеравая гама',
    'select':'выберыце',
    'Permanent clock on screen':'Пастаянны гадзіннік на экране',
    'Show channel number in list':'Паказ нумара канала ў спісе',
    'Show picons in channel list':'Паказ піконаў у спісе каналаў',
    'Show channel name in list':'Паказ назвы канала ў спісе',
    'Show progress in channel list':'Паказ прагрэсу ў спісе каналаў',
    'Show archive availability in list':'Паказ наяўнасці архіва ў спісе',
    'Show scrollbar in list':'Паказ скроллбара ў спісе',
    'Preview in channel list':'Прэв\'ю ў спісе каналаў',
    'always':'заўсёды',
    'on ':'па ',
    'Number of next TV programs in channel list':'Колькасць наступных перадач у спісе каналаў',
    'Channel list editing style':'Стыль рэдагавання спісаў',
    'All categories':'Усе катэгорыі',
    '"Favorites"':'"Абранае"',
    'Editor':'Рэдактар',
    'built-in':'убудаваны',
    'native':'родны',
    'HDMI-CEC support (on/off from TV)':'HDMI-СEC падтрымка (укл/выкл ад ТВ)',
    'Type of player for streaming':'Тып плэера для прайгравання',
    'Autostart of player':'Старт плэера пры ўключэнні',
    'Buffer Size, s':'Памер буфера, с',
    'Choose from':'Варыянты',
    'Settings':'Налады',
    'Change value':'Змена значэння',
    'Save Settings':'Захаваць налады',
    'To begining':'У пачатак',
    'Live':'Прамая трансляцыя',
    ' m ':' хвл ',
    ' s':' сек',
    '1 minute':'1 хвіліна',
    '10 Seconds':'10 секундаў',
    'Go to':'Перайсці',
    'Archive - begin':'Архіў - пачатак перадачы',
    'Pause':'Паўза',
    'Play':'Прайграванне',
    'Shutdown after %1 seconds<br/><br/>Cancel - any action':'Выключэнне праз %1 секунд<br/><br/>Адмена - любое дзеянне',
    'Do you want to exit player?':'Вы хочаце выйсці з плэера?',
    'Color':'Колер',
    'Saturation':'Насычанасць',
    'Yellow':'Жоўты',
    'Green':'Зялёны',
    'Blue':'Блакітны',
    'Set':'Усталяваць',
    'Restart stream':'Рэстарт патоку',
    'Favorites':'Выбраныя',
    'All':'Усе',
    '<br/>Processing the channel list...':'<br/>Апрацоўка спісу каналаў...',
    '<br/>Start playback...':'<br/>Старт прайгравання...',
    '<br/>Channel list not received !!!':'<br/>Не атрыманы спіс каналаў!!!',
    'Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>':'Не атрыманы спіс каналов!!!<br/><br/>Увядзіце дадзеныя правайдара і перазапусціце плэер!!!<br/><br/>',
    'Error getting channel list !!!':'Памылка атрымання спісу каналаў!!!',
    'system':'сістэмны',
    'Choose provider':'Выберыце правайдэра',
    '<br>Rewind<br>':'<br>Перамотка<br>',
    '<br>Menu':'<br>Меню',
    '<br>Pause<br>':'<br>Паўза<br>',
    '<br>Toggle<br>sound track':'<br>Пераключыць<br>гук.дарожку',
    '<br>Live':'<br>Прамы эфір',
    '<br>Previous<br>channel':'<br>Папярэдні<br>канал',
    '<br/><b>Failed to load provider script !!!</b>':'<br/><b>Немагчыма загрузіць скрыпт правайдэра!!!</b>',
    '<br/>Loading provider %1 script ...':'<br/>Загрузка скрыпту правайдара %1 ...',
    '<br/>Loading settings...':'<br/>Загрузка налад...',
    '<br/>Loading channel list...':'<br/>Загрузка спісу каналаў...',
    'Choose language':'Выберыце мову',
    'Change interface language':'Змена мовы інтэрфейсу',
    'Aspect':'Аспект',
    'Audio':'Гук.дарожка',
    'Stalker portals':'Сталкер парталы',
    'm3u-m3u8 playlists':'m3u-m3u8 плэйлісты',
    '<br/>Loading STB...':'<br/>Загрузка STB...',
    '<br/>Setup STB...':'<br/>Налады STB...',
    'Save settings to storage':'Запісаць налады на флешку',
    'Load settings from storage':'Аднавіць наладкі з флэшкі',
    'Download':'Спампаваць',
    'Skip this version':'Прапусціць гэтую версію',
    'Volume control':'Рэгуляванне гучнасці',
    'Long button presses':'Доўгія націскі кнопак',
    'Download new version Android App':'Спампаваць новую версію абалонкі',
    'To access you must enter url, username and password!':'Для доступу неабходна ўвесці адрас, логін і пароль!',
    'Failed to load channel list!':'Немагчыма загрузіць спіс каналаў!',
    'Year':'Год',
    'Duration':'Працягласць',
    'Genre':'Жанр',
    'Country':'Краіна',
    'Director':'Рэжысёр',
    'Actors':'У ролях',
    'Release date':'Дата выхаду',
    'Rating':'Рэйтынг',
    'Season':'Сезон',
    'Episodes':'К-сць эпізодаў',
    'VOD':'Фільмы і відэа',
    'TV series':'Серыялы',
    'Episode':'Эпізод',
    'Download! Wait ...':'Загрузка! Пачакайце ...',
    'Server':'Сервер',
    'URL':'Адрас',
    'Username':'Логін',
    'Password':'Пароль',
    'Stream type':'Тып патокаў',
    'Account info':'Інфармацыя аб падпісцы',
    'Select server number from 1 to 6 to save data':'Выберыце нумар сервера ад 1 да 6 для захавання дадзеных',
    ' (after changing, restart player)':' (пасля змены трэба перазапусціць плэер)',
    ' (after changing, switch the channel!)':' (пасля змены пераключыце канал!)',
    'Enter URL of server':'Рэдагаванне адрасу сервера',
    'Enter username':'Рэдагаванне логіна',
    'Enter password':'Рэдагаванне пароля',
    'Select stream type':'Выберыце тып патокаў',
    '??? No channel name':'??? Няма назвы канала',
    'Playlist URL':'Адрас плэйліста',
    'Archive hours':'Колькасць гадзін архіва',
    'Enter playlist URL':'Увод адраса плэйліста',
    'Enter playlist archive hours':'Увод колькасці гадзін архіва для плэйліста',
    'show on-screen keyboard':'выклікаць экранную клавіятуру',
    'Sleep without leaving player':'Заснуць не выходзячы з плэера',
    'PiP is not available!':'PiP не даступны!',
    'NORMAL':'ЗВЫЧАЙНЫ',
    'ENLARGE':'ПАВЕЛІЧЭННЕ',
    'MAKE_WIDER':'ПАВЕЛІЧЭННЕ ШЫРЫНІ',
    'NON_LINEAR_STRETCH':'НЕЛІНЕЙНАЕ РАСЦЯЖЭННЕ',
    'NON_LINEAR_STRETCH_TO_FULL_SCREEN':'НЕЛІНЕЙНАЕ РАСЦЯЖЭННЕ НА ЎВЕСЬ ЭКРАН',
    'MAKE_TALLER':'ПАВЕЛІЧЭННЕ ВЫШЫНІ',
    'CUT_EDGES':'АБРАЗАННЕ КРАЁЎ',
    'FULL_SCREEN':'ПОЎНЫ ЭКРАН',
    'STRETCH_TO_FULL_SCREEN':'РАСЦЯЖЭННЕ НА ЎВЕСЬ ЭКРАН',
    'Background color':'Колер фону',
    'Brightness':'Яркасць',
    '3 hours':'3 гадзіны',
    'Restart stream / Live':'Рэстарт патоку / Прамая трансляцыя',
    '- keyboard': '- клавіятура',
    'Media':'Медыятэка',
    'String for search':'Радок для пошуку',
    'Playlist Name':'Назва плэйліста',
    'Enter playlist Name':'Увод назвы плэйліста',
    'Media Library URL':'Адрас медыятэкі',
    'Enter Media Library URL':'Увод адрасу медыятэкі',
    'Playlist':'Плэйліст',
    'Select playlist':'Выберыце плэйліст',
    'Edit':'Рэдагаваць',
    'Load':'Загрузіць',
    'Edit playlist data':'Рэдагаванне дадзеных плэйліста',
    'Select portal':'Абярыце партал',
    'Portal Name':'Назва партала',
    'Enter Portal Name':'Увод назвы партала',
    'Edit portal data':'Рэдагаванне дадзеных партала',
    'without':'без',
    'Settings STB':'Налады прылады',
    'Soft audio render':'Праграмна дэкадаваць гук',
    'Long press horizontal arrows for volume control':'Кіраванне гучнасцю утрыманнем гар.стрэлак',
    'Yes':'Так',
    'Back':'Назад',
    'Show providers?':'Паказаць выбар правайдэраў?',
    'Hide providers?':'Схаваць выбар правайдэраў?',
    'Show provider settings?':'Паказаць налады правайдара?',
    'Hide provider settings?':'Схаваць налады правайдара?',
    'Clear all settings?':'Ачысціць ўсе налады?',
    'Timer':'Таймер',
    'Set timer?':'Усталяваць таймер?',
    'Remove timer?':'Выдаліць таймер?',
    'Timer: switch to channel?':'Таймер: пераключыцца на канал?',
    ' (if archive exists)':' (пры наяўнасці архіва канала)',
    'Preffered audio track':'Пераважная гукавая дарожка',
    'Information':'Інфармацыя',
    'Lists settings':'Налады спісаў',
    'Channel list settings':'Налады спіса каналаў',
    'Buttons settings':'Налады кнопак пульта',
    'Subtitle':'Субтытры',
    'Switch subtitle':'Пераключыць субтытры',
    'Off':'Выключыць',
    'Not found':'Адсутнічаюць',
    'History of watched movies':'Гісторыя праглядаў',
    'Continue watching?':'Працягнуць прагляд?',
    'Add to favorites':'Дадаць у абранае',
    'Delete':'Выдаліць',
    'Info about current stream':'Інфармацыя аб бягучым патоку',
    'Stop':'Стоп',
    'Playlist file':'Файл плэйліста',
    'Select playlist file':'Выбар файла плэйліста',
    'Graphical indication':'Графічная Індыкацыя',
    'Background color of selected item':'Колер фону вылучэння',
    'Default':'Па змаўчанні',
    'Not supported!':'Не падтрымліваецца!',
    'Menu items settings':'Налада пунктаў меню',
    'Select menu items':'Выберыце пункты меню',
    'Protect Adult Channels':'Абарона "дарослых" каналаў',
    'Protect Settings':'Абарона налад',
    'Protect Change Provider':'Абарона змены правайдэра',
    'Infobar settings':'Налады інфабара',
    'Show when switching':'Паказаць пры пераключэнні',
    'Show when changing program':'Паказаць пры змене праграмы',
    'Show when rewind':'Паказаць пры перамотцы',
    'Archive. Category: ':'Архіў. Катэгорыя: ',
    'Sort channels':'Сартаванне',
    '"As Is"':'"Як ёсць"',
    'Load playlist':'Загрузіць плэйліст',
    ' (after changing, load playlist)':' (пасля змены, загрузіць плэйліст)',
    'Statistics of current stream':'Статыстыка бягучага патоку',
    'Search':'Пошук',
// 14.6
    'Behavior of %1/%2 buttons in lists':'Паводзіны кнопак %1/%2 у спісах',
    'begin/end':'пачатак/канец',
    'Position shift -10 seconds after pause':'Зрух пазіцыі на -10 секунд пасля паўзы',
    'Remember previous channels':'Запамінаць папярэдніх каналаў',
    'History in Media Library':'Гісторыя праглядаў у медыятэцы',
// 5.11
    'Manage settings':'Кіраванне наладамі',
    'Save settings':'Захаваць налады',
    'Load settings':'Загрузіць налады',
    'Clear settings':'Ачысціць налады',
    'Send settings':'Адпраўка налад на сервер',
    'Settings sended!':'Налады адпраўлены на сервер!',
    'For download settings file open':'Для спампавання файла налад адкрыйце',
    'and enter code':'і ўвядзіце код',
    'or scan':'ці адскануйце',
    'Send request':'Адпраўленне запыту на сервер',
    'Request sended!':'Запыт адпраўлены на сервер!',
    'For upload settings file open':'Для загрузкі файла налад адкрыйце',
    'Enter Provider Code':'Увод кода правайдара',
    'Error Code!':'Памылка кода!!!',
    'For enter value open':'Для ўводу значэння адкрыйце',
    'First Run Setup':'Налада пры першым запуску',
    'Enter Provider Code on PC or Phone':'Увод кода правайдэра на кампутары або тэлефоне',
    'Manual setup':'Ручная налада',
    'Access settings':'Налады доступу',
// 26.1
    'Script':'Сцэнар',
    'Producer':'Прадзюсер',
    'Operator':'Аператар',
    'Composer':'Кампазітар',
    'Artist':'Мастак',
    'Installation':'Мантаж',
    'Budget':'Бюджэт',
    'Audience':'Аўдыторыя',
    'Premiere world':'Сусветная прэм\'ера',
    'Display settings':'Налады адлюстравання',
    'Age':'Узрост',
    'Sort':'Сартаванне',
    'by name':'па назве',
    'by adding':'па даданні',
    'Order':'Парадак',
    'asc':'узрастанне',
    'desc':'змяншэнне',
    'Language':'Мова',
    'Quality':'Якасць',
    'Show program name':'Паказ назвы перадачы',
    'Show description':'Паказ апісання перадачы',
    'transparent':'празрыстыя',
// 23.3
    'Rewind step by buttons %1/%2':'Крок перамоткi кнопкамi %1/%2',
}
