keyStrings = {
    'lang':'Français',
    'alhabet':'abcdefghijklmnopqrstuvwxyz',
    'Channel list. Category: ':'Liste des chaînes. Catégorie : ',
    'EPG':'Guide des programmes TV',
    'Category':'Catégorie',
    'Actions':'Actions',
    'Description':'Description',
    'Open in PiP':'Ouvrir dans PiP',
    'Move channel up':'Déplacer la chaîne vers le haut',
    'Move channel down':'Déplacer la chaîne vers le bas',
    'Delete channel':'Supprimer la chaîne',
    'Add channel to category':'Ajouter la chaîne à la catégorie',
    'Add channel to favorites':'Ajouter la chaîne aux favoris',
    'Channel parental control':'Contrôle parental de la chaîne',
    'Channel is not available!!!':'La chaîne n\'est pas disponible !!!',
    'min':'min',
    'Channel ':'Chaîne ',
    ' added to category ':' ajoutée à la catégorie ',
    ' added to favorites':' ajoutée aux favoris',
    'Favorites':'Favoris',
    'Select category to add channel':'Sélectionner la catégorie pour ajouter la chaîne',
    'Enter parental code':'Entrer le code parental',
    'Wrong parental code !!!':'Mauvais code parental !!!',
    '<br>Up<br>':'<br>Haut<br>',
    '<br>Delete':'<br>Supprimer',
    '<br>Add<br>to favorites':'<br>Ajouter<br>aux favoris',
    '<br>Add<br>to category':'<br>Ajouter<br>à une catégorie',
    '<br>Parental<br>Control':'<br>Contrôle<br>parental',
    '<br>Down':'<br>Bas',
    'Close':'Fermer',
    'Edit category name':'Editer le nom de la catégorie',
    'Category %1 already exists!':'La catégorie %1 existe déjà !',
    'Enter name for new category':'Entrer le nom de la nouvelle catégorie',
    '<br>More...<br>':'<br>Plus...<br>',
    '<br>Rename':'<br>Renommer',
    '<br>Copy<br>category':'<br>Copier<br>catégorie',
    '<br>Back<br>':'<br>Retour<br>',
    '<br>Create<br>category':'<br>Сréer<br>catégorie',
    'Category selection':'Sélection de la catégorie',
    'Menu':'Menu',
    'Channel list':'Liste des chaînes',
    'Move category up':'Déplacer la catégorie vers le haut',
    'Move category down':'Déplacer la catégorie vers le bas',
    'Create category':'Créer une catégorie',
    'Rename category':'Renommer une catégorie',
    'Copy category':'Copier une catégorie',
    'Delete category':'Supprimer une catégorie',
    'Su Mo Tu We Th Fr Sa':'Di Lu Ma Me Je Ve Sa',
    'EPG and archive. Channel: ':'Programme et archives. Chaîne : ',
    'By alphabet':'Par ordre alphabétique',
    'Archive. Channel: ':'Archives. Chaîne : ',
    'By time':'Par heure',
    'Player info:':'Informations du lecteur :',
    'Device info:':'Informations de l\'appareil :',
    '- switch:':'- inverser :',
    '- erase':'- effacer',
    '- move cursor':'- déplacer le curseur',
    '- return without save':'- retour sans sauvegarder',
    '- save':'- sauvegarder',
    'Return to previous channel':'Retourner à la chaîne précédente',
    'Call PiP / PiP exchange':'Lancer PiP / Inverser PiP',
    'Info about TV program':'Informations à propos du programme TV',
    'Show player menu':'Afficher le menu du lecteur',
    'Interface settings':'Paramètres de l\'interface',
    'Show channel selection list':'Afficher la liste de sélection des chaînes',
    'Hide / Return':'Cacher / Retour',
    'Exit player':'Quitter le lecteur',
    'Show EPG and archive for channel':'Afficher le guide des programmes et les archives des chaînes',
    'Channel category selection':'Sélection d\'une catégorie de chaînes',
    'Toggle Aspect Ratio':'Basculer le rapport hauteur/largeur de l\'écran" (Aspect Ratio)',
    'Toggle Zoom Mode':'Basculer en mode zoom',
    'Switch sound track':'Changer de piste audio',
    'In live mode: <br/>':'En mode d\'affichage en direct :<br/>',
    'Channel selection by number':'Sélection des chaînes par numéro',
    'Timeshift: to start of TV program':'Timeshift : pour démarrer le programme TV',
    'Timeshift: one minute back':'Timeshift : une minute en arrière',
    '<br/><br/>In archive mode:<br/>':'<br/><br/>En mode archive :<br/>',
    'Pause/Play':'Pause/Lecture',
    'Stop playback and return to In live mode':'Arrêt de la lecture et retour au direct',
    'To start of TV program / Previous TV program':'Au début du programme TV / Programme TV précédent',
    'Next TV program':'Programme TV suivant',
    'Back / Forward for 1 minute':'Retour / Avancer de 1 minute',
    'Back / Forward for 15 seconds':'Retour / Avancer de 15 secondes',
    'Back / Forward for 3 minutes':'Retour / Avancer de 3 minutes',
    'Back / Forward for 10 minutes':'Retour / Avancer de 10 minutes',
    'Show rewind window':'Afficher la fenêtre de rembobinage',
    'Description of remote control buttons':'Description des fonctions des boutons de la télécommande',
    'Description of remote control buttons depending on the view mode':'Description des fonctions des boutons de la télécommande selon le mode de visualisation',
    'Set parental code':'Définir le code parental',
    'Repeat parental code':'Répéter le code parental',
    'Show list of channel archive records':'Afficher des enregistrements d\'archives de la chaîne',
    'Show list of channel archive records without duplication':'Afficher la liste des enregistrements d\'archives des chaînes sans duplication',
    'Show Media Library':'Afficher la médiathèque',
    'Rewind':'Rembobiner',
    'Close PiP':'Fermer PiP',
    'Parental control':'Contrôle parental',
    'Change provider':'Changer de fournisseur',
    'Change provider - you can change the provider, and it will be remembered at the next start of player!':'Changer de fournisseur - vous pouvez changer de fournisseur, et il sera sauvegardé au prochain démarrage du lecteur !',
    'Restart player':'Redémarrer le lecteur',
    // 'Restart player - after changing provider settings (as example)':'Redémarrer le lecteur - après avoir modifié les paramètres du fournisseur (par exemple)',
    'Description of remote control buttons':'Description des boutons de la télécommande',
    'About':'A propos',
    'Player and device info':'Informations du lecteur et de l\'appareil',
    'Donate <div class="btn" style="background-color:orange;">donate</div>':'Faire un don <div class="btn" style="background-color:orange;">faire un don</div>',
    'Voluntary donation for the development of project':'Don volontaire pour le développement du projet',
    'Settings saved':'Paramètres sauvegardés',
    'no':'non',
    'yes':'oui',
    'Records':'Enregistrements',
    'Previous':'Précédent',
    'Info':'Info',
    'Not reduce video when showing the list (bugfix)':'Ne pas réduire la vidéo lors de l\'affichage de la liste (correction de bug)',
    'Black screen while switching the channel':'Écran noir lors du changement de chaîne',
    'PiP window size':'Dimensions fenêtre PiP',
    'small':'petit',
    'medium':'moyen',
    'large':'grand',
    'PiP window position':'Position de la fenêtre PiP',
    'top-right':'En haut à droite',
    'bottom-right':'En bas à droite',
    'left-bottom':'En bas à gauche',
    'top-left':'En haut à gauche',
    'Number of rows in lists':'Nombre de lignes dans les listes',
    'Distance between lines in lists':'Distance entre les lignes dans les listes',
    'Font type':'Type de police',
    'volume':'volume',
    'paging':'pagination',
    'Nothing':'Rien',
    'Exit':'Quitter',
    'Joystick':'Manette',
    'Button %1 function when viewing':'Fonction du bouton %1 lors de la visualisation',
    'Button function %1 when viewing archive':'Fonction du bouton %1 lors de l\'affichage de l\'archive',
    'Channels':'Chaînes',
    'Remote (color buttons N/A)':'Télécommande (boutons de couleur N/D)',
    'Remote (number buttons N/A)':'Télécommande (touches numériques N/D)',
    'Timezone':'Fuseau horaire',
    'Sleep timer':'Minuterie de mise en veille',
    'off':'désactivée',
    '30 minutes':'30 minutes',
    '1 hour':'1 heure',
    '2 hours':'2 heures',
    'Infobar display timeout, s':'Durée d\'affichage de la barre d\'informations, s',
    '"Sliding" infobar':'Barre d\'informations "glissante"',
    'Interface transparency':'Transparence de l\'interface',
    'Volume step, %':'Niveau volume, %',
    'List location':'Emplacement de la liste',
    'right':'droite',
    'left':'gauche',
    'Color spectrum':'Spectre de couleurs',
    'select':'sélectionner',
    'Permanent clock on screen':'Horloge permanente à l\'écran',
    'Show channel number in list':'Afficher le numéro de chaîne dans la liste',
    'Show picons in channel list':'Afficher le logo de la chaîne dans la liste',
    'Show channel name in list':'Afficher le nom de la chaîne dans la liste',
    'Show progress in channel list':'Afficher la progression dans la liste des chaînes',
    'Show archive availability in list':'Afficher si une archive est dans la liste',
    'Show scrollbar in list':'Afficher la barre de défilement dans la liste',
    'Preview in channel list':'Aperçu de la liste des chaînes',
    'always':'toujours',
    'on ':'sur ',
    'Number of next TV programs in channel list':'Nombre de programmes suivants dans la liste des chaînes',
    'Channel list editing style':'Style d\'édition de la liste',
    'All categories':'Toutes catégories',
    '"Favorites"':'"Favoris"',
    'Editor':'Editeur',
    'built-in':'intégré',
    'native':'natif',
    'HDMI-CEC support (on/off from TV)':'Prise en charge HDMI-CEC (activé/désactivé depuis le téléviseur)',
    'Type of player for streaming':'Type de lecteur pour la lecture',
    'Autostart of player':'Démarrage automatique du lecteur',
    'Buffer Size, s':'Taille de la mémoire tampon, s',
    'Choose from':'Choisir parmi',
    'Settings':'Paramètres',
    'Change value':'Changer valeur',
    'Save Settings':'Sauvegarder paramètres',
    'To begining':'Au début',
    'Live':'Direct',
    ' m ':' min ',
    ' s':' sec',
    '1 minute':'1 minute',
    '10 Seconds':'10 secondes',
    'Go to':'Aller à',
    'Archive - begin':'Archive - début',
    'Pause':'Pause',
    'Play':'Lecture',
    'Shutdown after %1 seconds<br/><br/>Cancel - any action':'Arrêt après %1 secondes<br/><br/>Annuler - toute action',
    'Do you want to exit player?':'Voulez-vous quitter le lecteur ?',
    'Color':'Couleur',
    'Saturation':'Saturation',
    'Yellow':'Jaune',
    'Green':'Vert',
    'Blue':'Bleu',
    'Set':'Définir',
    'Restart stream':'Redémarrer le flux',
    'Favorites':'Favoris',
    'All':'Tout',
    '<br/>Processing the channel list...':'<br/>Traitement de la liste des chaînes...',
    '<br/>Start playback...':'<br/>Démarrer la lecture...',
    '<br/>Channel list not received !!!':'<br/>Liste des chaînes non reçue !!!',
    'Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>':'Liste des chaînes non reçue !!!<br/><br/>Entrez les détails du fournisseur et redémarrez le lecteur !!!<br/><br/>',
    'Error getting channel list !!!':'Erreur lors de l\'obtention de la liste des chaînes !!!',
    'system':'système',
    'Choose provider':'Choisissez un fournisseur',
    '<br>Rewind<br>':'<br>Rembobiner<br>',
    '<br>Menu':'<br>Menu',
    '<br>Pause<br>':'<br>Pause<br>',
    '<br>Toggle<br>sound track':'<br>Basculer<br>piste audio',
    '<br>Live':'<br>Direct',
    '<br>Previous<br>channel':'<br>Chaîne<br>précédente',
    '<br/><b>Failed to load provider script !!!</b>':'<br/><b>Échec du chargement du script du fournisseur !!!</b>',
    '<br/>Loading provider %1 script ...':'<br/>Chargement du script du fournisseur %1 ...',
    '<br/>Loading settings...':'<br/>Chargement des paramètres...',
    '<br/>Loading channel list...':'<br/>Chargement de la liste des chaînes...',
    'Choose language':'Choisissez la langue',
    'Change interface language':'Changer la langue de l\'interface',
    'Aspect':'Aspect',
    'Audio':'Audio',
    'Stalker portals':'Portails Stalker',
    'm3u-m3u8 playlists':'Liste de lecture m3u-m3u8',
    '<br/>Loading STB...':'<br/>Chargement Décodeur TV...',
    '<br/>Setup STB...':'<br/>Configuration Décodeur TV...',
    'Save settings to storage':'Enregistrer les paramètres sur un disque',
    'Load settings from storage':'Restaurer les paramètres à partir d\'un disque',
    'Download':'Télécharger',
    'Skip this version':'Passer cette version',
    'Volume control':'Contrôle du volume',
    'Long button presses':'Pression longue du bouton',
    'Download new version Android App':'Télécharger la nouvelle version d\'Android',
    'To access you must enter url, username and password!':'Pour y accéder, vous devez saisir l\'adresse, le nom d\'utilisateur et le mot de passe !',
    'Failed to load channel list!':'Échec du chargement de la liste des chaînes !',
    'Year':'Année',
    'Duration':'Durée',
    'Genre':'Genre',
    'Country':'Pays',
    'Director':'Producteur',
    'Actors':'Acteurs',
    'Release date':'Date de sortie',
    'Rating':'Note',
    'Season':'Saison',
    'Episodes':'Episodes',
    'VOD':'Films et Vidéos',
    'TV series':'Séries TV',
    'Episode':'Episode',
    'Download! Wait ...':'Chargement en cours ! Patientez...',
    'Server':'Serveur',
    'URL':'Adresse',
    'Username':'Nom d\'utilisateur',
    'Password':'Mot de passe',
    'Stream type':'Type de flux',
    'Account info':'Info du compte',
    'Select server number from 1 to 6 to save data':'Sélectionnez le numéro de serveur de 1 à 6 pour enregistrer les données',
    ' (after changing, restart player)':' (après modification, redémarrez le lecteur)',
    ' (after changing, switch the channel!)':' (après modification, changez de chaîne !)',
    'Enter URL of server':'Entrez l\'adresse du serveur',
    'Enter username':'Entrez le nom d\'utilisateur',
    'Enter password':'Entrez le mot de passe',
    'Select stream type':'Sélectionnez le type de flux',
    '??? No channel name':'??? Pas de nom de chaîne',
    'Playlist URL':'Adresse de la liste de lecture',
    'Archive hours':'Heures d\'archivage',
    'Enter playlist URL':'Entrez une adresse de liste de lecture',
    'Enter playlist archive hours':'Entrez le nombre d\'heures d\'archivage de la liste de lecture',
    'show on-screen keyboard':'faire apparaître le clavier à l\'écran',
    'Sleep without leaving player':'Endormez-vous sans quitter le lecteur',
    'PiP is not available!':'PiP non disponible !',
    'NORMAL':'NORMAL',
    'ENLARGE':'AGRANDIR',
    'MAKE_WIDER':'AUGMENTER LARGEUR',
    'NON_LINEAR_STRETCH':'ETIREMENT NON LINEAIRE',
    'NON_LINEAR_STRETCH_TO_FULL_SCREEN':'ETIREMENT NON LINEAIRE PLEIN ECRAN',
    'MAKE_TALLER':'AUGMENTER HAUTEUR',
    'CUT_EDGES':'COUPER LES BORDS',
    'FULL_SCREEN':'PLEIN ECRAN',
    'STRETCH_TO_FULL_SCREEN':'ETIREMENT PLEIN ECRAN',
    'Background color':'Couleur de fond',
    'Brightness':'Luminosité',
    '3 hours':'3 heures',
    'Restart stream / Live':'Redémarrer le flux / Diffusion en direct',
    '- keyboard': '- clavier',
    'Media':'Médiathèque',
    'String for search':'Chaîne de recherche',
    'Playlist Name':'Nom de la liste de lecture',
    'Enter playlist Name':'Entrez le nom de la liste de lecture',
    'Media Library URL':'Adresse de la médiathèque',
    'Enter Media Library URL':'Entrez l\'adresse de la médiathèque',
    'Playlist':'Liste de lecture',
    'Select playlist':'Sélectionnez une liste de lecture',
    'Edit':'Editer',
    'Load':'Charger',
    'Edit playlist data':'Modification des données de la liste de lecture',
    'Select portal':'Sélectionnez un portail',
    'Portal Name':'Nom du portail',
    'Enter Portal Name':'Entrez le nom du portail',
    'Edit portal data':'Modification des données du portail',
    'without':'sans',
    'Settings STB':'Paramètres Décodeur TV',
    'Soft audio render':'Décoder l\'audio par logiciel',
    'Long press horizontal arrows for volume control':'Longue pression des flèches horizontales pour contrôler le volume',
    'Yes':'Oui',
    'Back':'Retour',
    'Show providers?':'Afficher les fournisseurs ?',
    'Hide providers?':'Cacher les fournisseurs ?',
    'Show provider settings?':'Afficher les paramètres du fournisseur ?',
    'Hide provider settings?':'Cacher les paramètres du fournisseur ?',
    'Clear all settings?':'Effacer tous les paramètres ?',
    'Timer':'Minuteur',
    'Set timer?':'Régler la minuterie ?',
    'Remove timer?':'Supprimer le minuteur ?',
    'Timer: switch to channel?':'Minuterie : passer à la chaîne ?',
    ' (if archive exists)':' (si une archive existe)',
    'Preffered audio track':'Piste audio préférée',
    'Information':'Informations',
    'Lists settings':'Paramètres de liste',
    'Channel list settings':'Paramètres de la liste des chaînes',
    'Buttons settings':'Paramètres des boutons de la télécommande',
    'Subtitle':'Sous-titres',
    'Switch subtitle':'Changer de sous-titres',
    'Off':'Eteindre',
    'Not found':'Absent',
    'History of watched movies':'Historique de navigation',
    'Continue watching?':'Continuer la navigation ?',
    'Add to favorites':'Ajouter aux favoris',
    'Delete':'Supprimer',
    'Info about current stream':'Informations sur le flux en cours',
    'Stop':'Arrêter',
    'Playlist file':'Fichier de la liste de lecture',
    'Select playlist file':'Sélectionnez un fichier de liste de lecture',
    'Graphical indication':'Affichage graphique',
    'Background color of selected item':'Couleur d\'arrière plan de la sélection',
    'Default':'Par défaut',
    'Not supported!':'Non supporté !',
    'Menu items settings':'Réglages des éléments du menu',
    'Select menu items':'Sélectionnez les éléments du menu',
    'Protect Adult Channels':'Protection des chaînes adultes',
    'Protect Settings':'Protection des paramètres',
    'Protect Change Provider':'Protection contre le changement de fournisseur',
    'Infobar settings':'Paramètres de la barre d\'informations',
    'Show when switching':'Afficher lors du changement',
    'Show when changing program':'Afficher lors du changement de programme',
    'Show when rewind':'Afficher lors du rembobinage',
    'Archive. Category: ':'Archiver. Catégorie : ',
    'Sort channels':'Trier les chaînes',
    '"As Is"':'"Tel que"',
    'Load playlist':'Chargement liste de lecture',
    ' (after changing, load playlist)':' (après modification, chargez la liste de lecture)',
    'Statistics of current stream':'Statistiques du flux en cours',
    'Search':'Rechercher',
// 14.6
    'Behavior of %1/%2 buttons in lists':'Comportement des boutons %1/%2 dans les listes',
    'begin/end':'début/fin',
    'Position shift -10 seconds after pause':'Retour de -10 secondes après une pause',
    'Remember previous channels':'Se souvenir des chaînes précédentes',
    'History in Media Library':'Historique de navigation dans la médiathèque',
// 5.11
    'Manage settings':'Gestion des paramètres',
    'Save settings':'Enregistrer les paramètres sur le serveur',
    'Load settings':'Restaurer les paramètres à partir du serveur',
    'Clear settings':'Effacer les paramètres',
    'Send settings':'Envoyer les paramètres au serveur',
    'Settings sended!':'Paramètres envoyés au serveur !',
    'For download settings file open':'Pour télécharger le fichier des paramètres, ouvrez',
    'and enter code':'et entrez le code',
    'or scan':'ou scannez',
    'Send request':'Envoi d\'une requête au serveur',
    'Request sended!':'Requête envoyée au serveur !',
    'For upload settings file open':'Pour télécharger le fichier des paramètres, ouvrez',
    'Enter Provider Code':'Entrer code du fournisseur',
    'Error Code!':'Erreur de code !!!',
    'For enter value open':'Pour saisir une valeur, ouvrez',
    'First Run Setup':'Première configuration',
    'Enter Provider Code on PC or Phone':'Entrer le code fournisseur sur un PC ou un téléphone',
    'Manual setup':'Configuration manuelle',
    'Access settings':'Paramètres d\'accès',
// 26.1
    'Script':'Scénario',
    'Producer':'Producteur',
    'Operator':'Opérateur',
    'Composer':'Compositeur',
    'Artist':'Artiste',
    'Installation':'Installation',
    'Budget':'Budget',
    'Audience':'Audience',
    'Premiere world':'Première mondiale',
    'Display settings':'Paramètres d\'affichage',
    'Age':'Age',
    'Sort':'Tri',
    'by name':'par nom',
    'by adding':'par ajout',
    'Order':'Ordre',
    'asc':'croissant',
    'desc':'décroissant',
    'Language':'Langue',
    'Quality':'Qualité',
    'Show program name':'Afficher le titre du programme',
    'Show description':'Afficher la description',
    'transparent':'transparent',
// 23.3
    'Rewind step by buttons %1/%2':'Etape de rembobinage avec les boutons %1/%2',
}
