keyStrings = {
    'lang':'Deutsch',
    'alhabet':'ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜ',
    'Channel list. Category: ':'Kanalliste. Kategorie: ',
    'EPG':'Programm',
    'Category':'Kategorien',
    'Actions':'Aktionen',
    'Description':'Beschreibung',
    'Open in PiP':'Öffnen in PiP',
    'Move channel up':'Kanal nach oben bewegen',
    'Move channel down':'Kanal nach unten bewegen',
    'Delete channel':'Kanal löschen',
    'Add channel to category':'Kanal zur Kategorie hinzufügen',
    'Add channel to favorites':'Kanal zur Favoriten hinzufügen',
    'Channel parental control':'Jugendschutz',
    'Channel is not available!!!':'Kanal ist nicht verfügbar!!!',
    'min':'Minuten',
    'Channel ':'Kanal ',
    ' added to category ':' zur Kategorie hinzugefügt ',
    ' added to favorites':' zur Favoriten hinzugefügt',
    'Favorites':'Favoriten',
    'Select category to add channel':'Kategorie auswählen, um Kanal hinzuzufügen',
    'Enter parental code':'Geben Sie den Jugendschutz Code ein',
    'Wrong parental code !!!':'Falsch Jugendschutz Code !!!',
    '<br>Up<br>':'<br>Nach oben<br>',
    '<br>Delete':'<br>Löschen',
    '<br>Add<br>to favorites':'<br>Zur Favoriten<br>hinzufügen',
    '<br>Add<br>to category':'<br>Zur Kategorie<br>hinzufügen',
    '<br>Parental<br>Control':'<br>Jugendschutz<br>',
    '<br>Down':'<br>Nach unten',
    'Close':'Schließen',
    'Edit category name':'Kategoriename bearbeiten ',
    'Category %1 already exists!':'Kategorie %1 existiert bereits!',
    'Enter name for new category':'Geben Sie eine Name für die neue Kategorie ein',
    '<br>More...<br>':'<br>Mehr...<br>',
    '<br>Rename':'<br>Umbenennen',
    '<br>Copy<br>category':'<br>Kategorie<br>kopieren',
    '<br>Back<br>':'<br>Zurück<br>',
    '<br>Create<br>category':'<br>Kategorie<br>erstellen',
    'Category selection':'Kategorie auswählen',
    'Menu':'Menü',
    'Channel list':'Kanalliste',
    'Move category up':'Kategorie nach oben bewegen',
    'Move category down':'Kategorie nach unten bewegen',
    'Create category':'Kategorie erstellen',
    'Rename category':'Kategorie umbenennen',
    'Copy category':'Kategorie kopieren',
    'Delete category':'Kategorie löschen',
    'Su Mo Tu We Th Fr Sa':'So Mo Di Mi Do Fr Sa',
    'EPG and archive. Channel: ':'EPG und Archiv. Kanal: ',
    'By alphabet':'Alphabetisch',
    'Archive. Channel: ':'Archiv. Kanal: ',
    'By time':'Nach Zeit',
    'Player info:':'Player info:',
    'Device info:':'Gerätinfo:',
    '- switch:':'- umschalten:',
    '- erase':'- löschen',
    '- move cursor':'- Cursor bewegen',
    '- return without save':'- zurück ohne speichern',
    '- save':'- speichern',
    'Return to previous channel':'Zurück zum vorhergehenden Kanal',
    'Call PiP / PiP exchange':'PiP abrufen / PiP austausch',
    'Info about TV program':'Info über das Fernsehprogramm',
    'Show player menu':'Player Menü abrufen',
    'Interface settings':'Schnittstelleneinstellungen',
    'Show channel selection list':'Auswahlliste für einen Kanal anzeigen',
    'Hide / Return':'Verbergen / zurück',
    'Exit player':'Player beenden',
    'Show EPG and archive for channel':'EPG und Archiv für Kanal anzeigen',
    'Channel category selection':'Auswahl der Kanalkategorie',
    'Toggle Aspect Ratio':'Schalten den Modus "Seitenverhältnis des Bildschirms" (Aspect Ratio)',
    'Toggle Zoom Mode':'Schalten den Zoom-Modus',
    'Switch sound track':'Audiospur wechseln',
    'In live mode: <br/>':'Im Live-Modus:<br/>',
    'Channel selection by number':'Kanalauswahl durch die Nummer',
    'Timeshift: to start of TV program':'Timeshift: Zum Starten des TV-Programms',
    'Timeshift: one minute back':'Timeshift: eine Minute zurück',
    '<br/><br/>In archive mode:<br/>':'<br/><br/>Im Archivmodus:<br/>',
    'Pause/Play':'Pause/Abspielen',
    'Stop playback and return to In live mode':'Stoppen die Wiedergabe und zurück zum Live-Modus',
    'To start of TV program / Previous TV program':'Zum Starten des Fernsehprogramms / Vorheriges Fernsehprogramm',
    'Next TV program':'Nächstes Fernsehprogramm',
    'Back / Forward for 1 minute':'Zurück / 1 Minute vorwärts',
    'Back / Forward for 15 seconds':'Zurück / 15 Sekunden vorwärts',
    'Back / Forward for 3 minutes':'Zurück / 3 Minuten vorwärts',
    'Back / Forward for 10 minutes':'Zurück / 10 Minuten vorwärts',
    'Show rewind window':'Fenster zum Zurückspulen aufrufen',
    'Description of remote control buttons':'Beschreibung der Funktionen der Fernbedienungstasten',
    'Description of remote control buttons depending on the view mode':'Beschreibung der Funktionen der Fernbedienung Tasten je nach Anzeigemodus',
    'Set parental code':'Setzen Sie den Jugendschutz Code',
    'Repeat parental code':'Jugendschutz Code wiederholen',
    'Show list of channel archive records':'Aufnahmeliste aus Kanalarchiv abrufen',
    'Show list of channel archive records without duplication':'Aufnahmeliste aus Kanalarchiv (ohne Wiederholung) abrufen',
    'Show Media Library':'Medienbibliothek abrufen',
    'Show Media Library (if available from provider)':'Medienbibliothek abrufen (falls verfügbar beim Anbieter)',
    'Rewind':'Zurückspulen',
    'Close PiP':'Schließen PiP',
    'Parental control':'Jugendschutz',
    'Change provider':'Anbieter wechseln',
    'Change provider - you can change the provider, and it will be remembered at the next start of player!':'Anbieter wechseln - Sie können den Anbieter wechseln und es wird beim nächsten Start in Erinnerung bleiben!',
    'Restart player':'Player neu starten',
    'Restart player - after changing provider settings (as example)':'Player neu starten, beispielsweise nachdem Sie die Anbietereinstellungen geändert haben',
    'Description of remote control buttons':'Fernbedienungstasten Beschreibung',
    'About':'Über',
    'Player and device info':'Player- und Gerätinfo',
    'Donate <div class="btn" style="background-color:orange;">donate</div>':'Spenden <div class="btn" style="background-color:orange;">donate</div>',
    'Voluntary donation for the development of project':'Freiwillige Spende für die Projektentwicklung',
    'Settings saved':'Einstellungen gespeichert',
    'no':'nein',
    'yes':'ja',
    'Records':'Aufnahmeliste',
    'Previous':'Bisherige',
    'Info':'Info',
    'Not reduce video when showing the list (bugfix)':'Video beim Anzeigen der Liste nicht verkleinern (bugfix)',
    'Black screen while switching the channel':'Schwarzer Bildschirm beim Umschalten des Kanals',
    'PiP window size':'PiP-Fenstergröße',
    'small':'klein',
    'medium':'mittel',
    'large':'groß',
    'PiP window position':'PiP-Fensterposition',
    'top-right':'oben rechts',
    'bottom-right':'unten rechts',
    'left-bottom':'links unten',
    'top-left':'oben links',
    'Number of rows in lists':'Anzahl der Zeilen in Listen',
    'Distance between lines in lists':'Abstand zwischen Zeilen in Listen',
    'Font type':'Schrift',
    'volume':'Volume',
    'paging':'Paging',
    'Nothing':'Nichts',
    'Exit':'Beenden',
    'Joystick':'Joystick',
    'Button %1 function when viewing':'Tastenfunktion %1 beim Betrachten',
    'Button function %1 when viewing archive':'Tastenfunktion %1 beim Betrachten des Archivs',
    'Channels':'Kanäle',
    'Remote (color buttons N/A)':'Fernbedienung ohne Farbtasten',
    'Remote (number buttons N/A)':'Fernbedienung ohne Zifferntasten',
    'Timezone':'Zeitzone',
    'Sleep timer':'Sleep-Timer',
    'off':'getrennt',
    '30 minutes':'30 Minuten',
    '1 hour':'1 Stunde',
    '2 hours':'2 Stunden',
    'Infobar display timeout, s':'Infobar-Timeout, s',
    '"Sliding" infobar':'"Sliding" Infobar',
    'Interface transparency':'OSD-Transparenz',
    'Volume step, %':'Schritt des Volumens, %',
    'List location':'Listenplatz',
    'right':'rechts',
    'left':'links',
    'Color spectrum':'Farbspektrum',
    'select':'wählen',
    'Permanent clock on screen':'Permanente Uhr auf dem Bildschirm',
    'Show channel number in list':'Kanalnummer in der Kanalliste anzeigen',
    'Show picons in channel list':'Picons in der Kanalliste anzeigen',
    'Show channel name in list':'Kanalnamen in der Kanalliste anzeigen',
    'Show progress in channel list':'Zeigt den Fortschritt in der Kanalliste an',
    'Show archive availability in list':'Archivverfügbarkeit in der Kanalliste anzeigen',
    'Show scrollbar in list':'Bildlaufleiste in der Kanalliste anzeigen',
    'Preview in channel list':'Vorschau in der Kanalliste',
    'always':'immer',
    'on ':'auf ',
    'Number of next TV programs in channel list':'Anzahl der nächsten Fernsehprogramme in der Kanalliste',
    'Channel list editing style':'Bearbeitungsmethode der Kanalliste',
    'All categories':'Alle Kategorien',
    '"Favorites"':'"Favoriten"',
    'Editor':'Editor',
    'built-in':'eingebaut',
    'native':'eingebauter',
    'HDMI-CEC support (on/off from TV)':'HDMI-CEC-Unterstützung (Ein / Aus vom Fernseher)',
    'Type of player for streaming':'Streaming-Player wählen',
    'Autostart of player':'Autostart des Players',
    'Buffer Size, s':'Puffergröße, s',
    'Choose from':'Wähle aus',
    'Settings':'Einstellungen',
    'Change value':'Wert ändern',
    'Save Settings':'Einstellungen speichern',
    'To beginning':'Zum anfang',
    'Live':'Live-Stream',
    ' m ':' min ',
    ' s':' s',
    '1 minute':'1 Minute',
    '10 Seconds':'10 Sekunden',
    'Go to':'Gehe zu',
    'Archive - begin':'Archiv - Start von Anfang',
    'Pause':'Pause',
    'Play':'Wiedergabe',
    'Shutdown after %1 seconds<br/><br/>Cancel - any action':'Herunterfahren nach %1 Sekunden<br/><br/>Abbrechen - jede Aktion',
    'Do you want to exit player?':'Möchten Sie den Player beenden?',
    'Color':'Farbe',
    'Saturation':'Sättigung',
    'Yellow':'Gelb',
    'Green':'Grün',
    'Blue':'Blau',
    'Set':'einstellen',
    'Restart stream':'Stream neu starten',
    'Favorites':'Favoriten',
    'All':'Alle',
    '<br/>Processing the channel list...':'<br/>Kanalliste bearbeiten...',
    '<br/>Start playback...':'<br/>Starten die Wiedergabe...',
    '<br/>Channel list not received !!!':'<br/>Kanalliste nicht empfangen!!!',
    'Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>':'Kanalliste nicht empfangen!!!<br/><br/>Geben Sie die Anbieterdaten ein und starten Sie den Player neu!!!<br/><br/>',
    'Error getting channel list !!!':'Fehler beim Erhalten einer Kanalliste!!!',
    'system':'systemisch',
    'Choose provider':'Anbieter auswählen',
    '<br>Rewind<br>':'<br>Zurückspulen<br>',
    '<br>Menu':'<br>Menü',
    '<br>Pause<br>':'<br>Pause<br>',
    '<br>Toggle<br>sound track':'<br>Audiospür<br>umschalten',
    '<br>Live':'<br>Live-Sendung',
    '<br>Previous<br>channel':'<br>Vorheriger<br>Kanal',
    '<br/><b>Failed to load provider script !!!</b>':'<br/><b>Fehler beim Laden des Anbieterskripts!!!</b>',
    '<br/>Loading provider %1 script ...':'<br/>Anbieter-Skript wird geladen %1 ...',
    '<br/>Loading settings...':'<br/>Einstellungen werden geladen...',
    '<br/>Loading channel list...':'<br/>Kanalliste wird geladen...',
    'Choose language':'Sprache wählen',
    'Change interface language':'Ändern Sie die Sprache der Benutzeroberfläche',
    'Aspect':'Aspekt',
    'Audio':'Audio',
    'Stalker portals':'Stalker-Portals',
    'm3u-m3u8 playlists':'m3u-m3u8 Wiedergabelisten',
    '<br/>Loading STB...':'<br/>Laden von STB...',
    '<br/>Setup STB...':'<br/>STB einrichten...',
    'Save settings to storage':'Speichern die Einstellungen im Speicher',
    'Load settings from storage':'Laden die Einstellungen aus dem Speicher',
    'Download':'Herunterladen',
    'Skip this version':'Diese Version überspringen',
    'Volume control':'Lautstärkeregelung',
    'Long button presses':'Langes Drücken der Taste',
    'Download new version Android App':'Laden Sie die neue Version der Android App herunter',
    'To access you must enter url, username and password!':'Um darauf zuzugreifen, müssen Sie die URL, den Benutzernamen und das Passwort eingeben!',
    'Failed to load channel list!':'Fehler beim Laden der Kanalliste!',
    'Year':'Jahr',
    'Duration':'Dauer',
    'Genre':'Genre',
    'Country':'Land',
    'Director':'Regisseur',
    'Actors':'Schauspieler',
    'Release date':'Veröffentlichungsdatum',
    'Rating':'Bewertung',
    'Season':'Saison',
    'Episodes':'Folgen',
    'VOD':'Filme und Videos',
    'TV series':'Fernsehserien',
    'Episode':'Episode',
    'Download! Wait ...':'Herunterladen! Warten Sie bitte ...',
    'Server':'Server',
    'URL':'URL',
    'Username':'Nutzername',
    'Password':'Passwort',
    'Stream type':'Stream-Typ',
    'Account info':'ABO-Info',
    'Select server number from 1 to 6 to save data':'Wählen Sie eine Servernummer zwischen 1 und 6, um die Daten zu speichern',
    ' (after changing, restart player)':' (nach dem Änderung starten Sie den Player neu)',
    ' (after changing, switch the channel!)':' (nach dem Änderung den Kanal umschalten!)',
    'Enter URL of server':'Geben Sie die URL des Servers ein',
    'Enter username':'Nutzername bearbeiten',
    'Enter password':'Passwort bearbeiten',
    'Select stream type':'Wählen den Stream-Typ',
    '??? No channel name':'??? Keine Kanalname',
    'Playlist URL':'Playlist-URL',
    'Archive hours':'Archiv Stunden',
    'Enter playlist URL':'Geben Sie die URL der Wiedergabeliste ein',
    'Enter playlist archive hours':'Geben Sie die Archivstunden der Wiedergabeliste ein',
    'show on-screen keyboard':'Bildschirmtastatur anzeigen',
    'Sleep without leaving player':'Schlafen, ohne den Spieler zu verlassen',
    'PiP is not available!':'PiP ist nicht verfügbar!',
    'NORMAL':'NORMAL',
    'ENLARGE':'VERGRÖSSERN',
    'MAKE_WIDER':'VERBREITEN',
    'NON_LINEAR_STRETCH':'NICHT LINEARE STRETCKEN',
    'NON_LINEAR_STRETCH_TO_FULL_SCREEN':'NICHTLINIEARER STRETCKEN ZUM GANZEN BILDSCHIRM',
    'MAKE_TALLER':'ERHÖHTEN HÖHE',
    'CUT_EDGES':'KANTEN SCHNEIDEN',
    'FULL_SCREEN':'VOLLBILD',
    'STRETCH_TO_FULL_SCREEN':'STRECKEN BIS ZUM VOLLBILD',
    'Background color':'Hintergrundfarbe',
    'Brightness':' Helligkeit ',
    '3 hours':'3 Stunden',
    'Restart stream / Live':'Stream neu starten/ Live',
    '- keyboard': '- Tastatur',
    'Media':' Medienbibliothek ',
    'String for search':' Suchzeichenfolge ',
    'Playlist Name':'Name der Wiedergabeliste',
    'Enter playlist Name':'Name der Wiedergabeliste eingeben',
    'Media Library URL':'URL der Medienbibliothek',
    'Enter Media Library URL': 'Medienbibliotheks-URL eingeben',
    'Playlist':'Wiedergabeliste',
    'Select playlist':'Wählen Sie Playlist',
    'Edit':'Bearbeiten',
    'Load':'Beladen',
    'Edit playlist data':'Wiedergabelistendaten bearbeiten',
    'Select portal':'Portal auswählen',
    'Portal Name':'Portalname',
    'Enter Portal Name':'Geben Sie den Portalnamen ein',
    'Edit portal data':'Portaldaten bearbeiten',
    'without':'ohne',
    'Settings STB':'Einstellungen STB',
    'Soft audio render':'Soft Audio Render',
    'Long press horizontal arrows for volume control':'Lange horizontale Pfeile zur Lautstärkeregelung drücken',
    'Yes':'Ja',
    'Back':'Zurück',
    'Show providers?':'Anbieter anzeigen?',
    'Hide providers?':'Anbieter verstecken?',
    'Show provider settings?':'Anbietereinstellungen anzeigen?',
    'Hide provider settings?':'Anbietereinstellungen ausblenden?',
    'Clear all settings?':'Alle Einstellungen löschen?',
    'Timer':'Timer',
    'Set timer?':'Timer einstellen?',
    'Remove timer?':'Timer entfernen?',
    'Timer: switch to channel?':'Timer: Zum Kanal wechseln?',
    ' (if archive exists)':'(wenn Archiv existiert)',
    'Preffered audio track':'Bevorzugte Audiospur',
    'Information':' Information ',
    'Lists settings':'Listet Einstellungen auf',
    'Channel list settings':'Kanallisteneinstellungen',
    'Buttons settings':'Tasteneinstellungen',
    'Subtitle':' Untertitel ',
    'Switch subtitle':' Untertitel wechseln',
    'Off':' Ausschalten',
    'Not found':'Nicht gefunden',
    'History of watched movies':'Geschichte der gesehenen Filme',
    'Continue watching?':'Weiter schauen?',
    'Add to favorites':'Zu den Favoriten hinzufügen',
    'Delete':'Löschen',
    'Info about current stream':'Info zum aktuellen Stream',
    'Stop':'Stoppen',
    'Playlist file':'Wiedergabeliste-datei',
    'Select playlist file':'Wiedergabelistendatei auswählen',
    'Graphical indication':'Grafische Anzeige',
    'Background color of selected item':'Hintergrundfarbe des ausgewählten Elements',
    'Default':'Standard',
    'Not supported!':'Nicht unterstützt!',
    'Menu items settings':'Einstellungen für Menüelemente',
    'Select menu items':'Menüpunkte auswählen',
// 13.5
    'Protect Adult Channels':'Erwachsene Kanäle schützen',
    'Protect Settings':'Regelungen shützen',
    'Protect Change Provider':'Verrat Lieferant schützen',
    'Infobar settings':'Infobar Regelungen',
    'Show when switching':'Beim Umschalten anzeigen',
    'Show when changing program':'Beim Programmwechsel anzeigen',
    'Show when rewind':' Beim Zurückspulen anzeigen',
    'Archive. Category: ':'Archiv. Kategorie: ',
    'Sort channels':'Kanäle sortieren',
    '"As Is"':'"Wie es ist"',
    'Load playlist':'Playlist laden',
    ' (after changing, load playlist)':' (Laden nach dem Playlist Ändern)',
    'Statistics of current stream':'Statistik des aktuellen Streams',
    'Search':'Suche',
// 14.6
    'Behavior of %1/%2 buttons in lists':'Verhalten der Schaltflächen %1/%2 in die Listen',
    'begin/end':'Zum Anfang/Ende',
    'Position shift -10 seconds after pause':'Positionsverschiebung um -10 Sekunden nach der Pause',
    'Remember previous channels':'Vorherige Kanäle merken',
    'History in Media Library':'Browserverlauf in der Medienbibliothek',
}
