keyStrings = {
    'lang':'Ελληνικά',
    'alhabet':'αβγδεζηθικλμνξοπρστυφχψω',
    'Channel list. Category: ':'Λίστα καναλιών. Κατηγορία: ',
    'EPG':'Πρόγραμμα',
    'Category':'Κατηγορίες',
    'Actions':'Ενέργειες',
    'Description':'Περιγραφή',
    'Open in PiP':'Άνοιγμα σε PiP',
    'Move channel up':'Μετακίνηση προς τα πάνω',
    'Move channel down':'Μετακίνηση προς τα κάτω',
    'Delete channel':'Διαγραφή καναλιού',
    'Add channel to category':'Προσθήκη καναλιού σε κατηγορία',
    'Add channel to favorites':'Προσθήκη καναλιού στα αγαπημένα',
    'Channel parental control':'Γονικός έλεγχος καναλιού',
    'Channel is not available!!!':'Μη διαθέσιμο κανάλι!!!',
    'min':'λεπτά',
    'Channel ':'Κανάλι ',
    ' added to category ':' προστέθηκε σε κατηγορία ',
    ' added to favorites':' προστέθηκε στα αγαπημένα',
    'Favorites':'Αγαπημένα',
    'Select category to add channel':'Επιλογή κατηγορίας για προσθήκη καναλιού',
    'Enter parental code':'Εισάγετε κωδικό γονικού ελέγχου',
    'Wrong parental code !!!':'Λάθος κωδικός γονικού ελέγχου !!!',
    '<br>Up<br>':'<br>Πάνω<br>',
    '<br>Delete':'<br>Διαγραφή',
    '<br>Add<br>to favorites':'<br>Προσθήκη<br>στα αγαπημένα',
    '<br>Add<br>to category':'<br> Προσθήκη<br>σε κατηγορία',
    '<br>Parental<br>Control':'<br>Γονικός<br>έλεγχος',
    '<br>Down':'<br>Κάτω',
    'Close':'Κλείσιμο',
    'Edit category name':'Επεξεργασία ονόματος καναλιού',
    'Category %1 already exists!':'Η κατηγορία %1 ήδη υπάρχει!',
    'Enter name for new category':'Εισάγετε ονομασία νέας κατηγορίας',
    '<br>More...<br>':'<br>Επιπλέον...<br>',
    '<br>Rename':'<br>Μετονομασία',
    '<br>Copy<br>category':'<br>Αντιγραφή<br>κατηγορίας',
    '<br>Back<br>':'<br>Πίσω<br>',
    '<br>Create<br>category':'<br>Δημιουργία<br>κατηγορίας',
    'Category selection':'Επιλογή κατηγορίας καναλιών',
    'Menu':'Μενού',
    'Channel list':'Λίστα καναλιών',
    'Move category up':'Μετακίνηση κατηγορίας προς τα πάνω',
    'Move category down':' Μετακίνηση κατηγορίας προς τα κάτω',
    'Create category':'Δημιουργία κατηγορίας',
    'Rename category':'Μετονομασία κατηγορίας',
    'Copy category':'Αντιγραφή κατηγορίας',
    'Delete category':'Διαγραφή κατηγορίας',
    'Su Mo Tu We Th Fr Sa':'Κυ Δε Τρ Τε Πε Πα Σα',
    'EPG and archive. Channel: ':'Οδηγός προγράμματος και αρχείο. Κανάλι: ',
    'By alphabet':'Αλφαβητικά',
    'Archive. Channel: ':'Αρχείο. Κανάλι: ',
    'By time':'Χρονολογικά',
    'Player info:':'Πληροφορίες προγράμματος:',
    'Device info:':'Πληροφορίες συσκευής:',
    '- switch:':'- αλλαγή:',
    '- erase':'- διαγραφή',
    '- move cursor':'- μετακίνηση κέρσορα',
    '- return without save':'- επιστροφή χωρίς αποθήκευση',
    '- save':'- αποθήκευση',
    'Return to previous channel':'Επιστροφή στο προηγούμενο κανάλι',
    'Call PiP / PiP exchange':'Εμφάνιση PiP / Εναλλαγή πηγών PiP',
    'Info about TV program':'Εμφάνιση πληροφοριών εκπομπής',
    'Show player menu':'Εμφάνιση μενού προγράμματος',
    'Interface settings':'Ρυθμίσεις διεπαφής',
    'Show channel selection list':'Εμφάνιση λίστας επιλογής καναλιού',
    'Hide / Return':'Αφαίρεση πληροφοριών / επιστροφή',
    'Exit player':'Έξοδος από το πρόγραμμα',
    'Show EPG and archive for channel':'Εμφάνιση οδηγού προγράμματος και αρχείου καναλιού',
    'Channel category selection':'Επιλογή κατηγορίας καναλιών',
    'Toggle Aspect Ratio':'Εναλλαγή λειτουργίας "Λόγος διαστάσεων οθόνης" (Aspect Ratio)',
    'Toggle Zoom Mode':'Εναλλαγή λειτουργίας μεγέθυνσης',
    'Switch sound track':'Εναλλαγή ακολουθίας ήχου',
    'In live mode: <br/>':'Σε λειτουργία απευθείας μετάδοσης:<br/>',
    'Channel selection by number':'Επιλογή καναλιού με αριθμό',
    'Timeshift: to start of TV program':'Timeshift: μετάβαση στην αρχή',
    'Timeshift: one minute back':'Timeshift: πίσω κατά ένα λεπτό',
    '<br/><br/>In archive mode:<br/>':'<br/><br/>Σε λειτουργία αναπαραγωγής αρχείου:<br/>',
    'Pause/Play':'Παύση/Αναπαραγωγή',
    'Stop playback and return to In live mode':'Διακοπή αναπαραγωγής και επιστροφή σε απευθείας μετάδοση',
    'To start of TV program / Previous TV program':'Στην αρχή της εκπομπής / Στην προηγούμενη εκπομπή',
    'Next TV program':'Στην επόμενη εκπομπή',
    'Back / Forward for 1 minute':'Πίσω / Εμπρός κατά ένα λεπτό',
    'Back / Forward for 15 seconds':'Πίσω / Εμπρός κατά 15 δευτ.',
    'Back / Forward for 3 minutes':'Πίσω / Εμπρός κατά 3 λεπτά',
    'Back / Forward for 10 minutes': 'Πίσω / Εμπρός κατά 10 λεπτά',
    'Show rewind window':'Εμφάνιση παραθύρου γρήγορης αναπαραγωγής',
    'Description of remote control buttons':'Περιγραφή λειτουργιών κουμπιών τηλεκοντρόλ',
    'Description of remote control buttons depending on the view mode':'Περιγραφή λειτουργιών κουμπιών τηλεκοντρόλ, που εξαρτώνται από τη λειτουργία προβολής',
    'Set parental code':'Ορισμός κωδικού γονικού ελέγχου',
    'Repeat parental code':'Επανάληψη κωδικού γονικού ελέγχου',
    'Show list of channel archive records':'Εμφάνιση λίστας εγγραφών αρχείου καναλιού',
    'Show list of channel archive records without duplication':'Εμφάνιση λίστας εγγραφών αρχείου καναλιού χωρίς διπλότυπα',
    'Show Media Library':'Εμφάνιση βιβλιοθήκης πολυμέσων',
    'Rewind':'Γρήγορη αναπαραγωγή',
    'Close PiP':'Κλείσιμο PiP',
    'Parental control':'Γονικός έλεγχος',
    'Change provider':'Αλλαγή παρόχου',
    'Change provider - you can change the provider, and it will be remembered at the next start of player!':'Αλλαγή παρόχου – Μπορείτε να αλλάξετε πάροχο και η επιλογή σας θα ληφθεί υπόψη κατά την επόμενη εκκίνηση του προγράμματος!',
    'Restart player':'Επανεκκίνηση του προγράμματος',
    // 'Restart player - after changing provider settings (as example)':' Επανεκκίνηση του προγράμματος – για παράδειγμα μετά από αλλαγή ρυθμίσεων παρόχου',
    'Description of remote control buttons':'Περιγραφή κουμπιών τηλεκοντρόλ',
    'About':'Πληροφορίες',
    'Player and device info':'Πληροφορίες προγράμματος και συσκευής',
    'Donate <div class="btn" style="background-color:orange;">donate</div>':'Συνεισφορά στο έργο <div class="btn" style="background-color:orange;">donate</div>',
    'Voluntary donation for the development of project':'Εθελοντική συνεισφορά για την ανάπτυξη του έργου',
    'Settings saved':'Οι ρυθμίσεις έχουν αποθηκευτεί',
    'no':'όχι',
    'yes':'ναί',
    'Records':'Εγγραφές',
    'Previous':'Προηγούμενος',
    'Info':'Info',
    'Not reduce video when showing the list (bugfix)':'Να μη μικραίνει το βίντεο κατά την εμφάνιση της λίστας (bugfix)',
    'Black screen while switching the channel':'Μαύρη οθόνη κατά την αλλαγή καναλιού',
    'PiP window size':'Μέγεθος παραθύρου PiP',
    'small':'μικρό',
    'medium':'μεσαίο',
    'large':'μεγάλο',
    'PiP window position':'Θέση παραθύρου PiP',
    'top-right':'δεξιά-πάνω',
    'bottom-right':'δεξιά-κάτω',
    'left-bottom':'αριστερά-κάτω',
    'top-left':'αριστερά-πάνω',
    'Number of rows in lists':'Αριθμός γραμμών λίστας',
    'Distance between lines in lists':'Απόσταση μεταξύ γραμμών λίστας',
    'Font type':'Γραμματοσειρά',
    'volume':'ένταση ήχου',
    'paging':'αλλαγή σελίδας',
    'Nothing':'Τίποτα',
    'Exit':'Έξοδος',
    'Joystick':' Joystick',
    'Button %1 function when viewing':'Λειτουργία κουμπιού %1 κατά την προβολή',
    'Button function %1 when viewing archive': 'Λειτουργία κουμπιού %1 κατά την προβολή αρχείου',
    'Channels':'Κανάλια',
    'Remote (color buttons N/A)':'Τηλεκοντρόλ χωρίς έγχρωμα κουμπιά',
    'Remote (number buttons N/A)':'Τηλεκοντρόλ χωρίς αριθμητικά κουμπιά',
    'Timezone':'Ζώνη ώρας',
    'Sleep timer':'Χρονοδιακόπτης',
    'off':'απενεργοποιημένος',
    '30 minutes':'30 λεπτά',
    '1 hour':'1 ώρα',
    '2 hours':'2 ώρες',
    'Infobar display timeout, s':'Τάϊμ άουτ προβολής infobar, δευτ.',
    '"Sliding" infobar':'"Κυλιόμενο" infobar',
    'Interface transparency':'Διαφάνεια διεπαφής',
    'Volume step, %':'Βήμα έντασης ήχου, %',
    'List location':'Θέση λίστας',
    'right':'από δεξιά',
    'left':'από αριστερά',
    'Color spectrum':'Φάσμα χρωμάτων',
    'select':'επιλογή',
    'Permanent clock on screen':'Μόνιμη ένδειξη ώρας στην οθόνη',
    'Show channel number in list':'Ένδειξη αριθμού καναλιού στη λίστα',
    'Show picons in channel list':'Ένδειξη picons στη λίστα καναλιών',
    'Show channel name in list':'Ένδειξη ονόματος καναλιού στη λίστα',
    'Show progress in channel list':'Ένδειξη προόδου στη λίστα καναλιών',
    'Show archive availability in list':'Ένδειξη ύπαρξης αρχείου στη λίστα',
    'Show scrollbar in list':'Ένδειξη γραμμής κύλισης στη λίστα',
    'Preview in channel list':'Προεπισκόπηση στη λίστα καναλιών',
    'always':'πάντα',
    'on ':'με ',
    'Number of next TV programs in channel list':'Αριθμός επόμενων εκπομπών στη λίστα καναλιών',
    'Channel list editing style':'Στυλ επεξεργασίας λίστας',
    'All categories':'όλες οι κατηγορίες',
    '"Favorites"':'"Αγαπημένα"',
    'Editor':'Επεξεργαστής',
    'built-in':'ενσωματωμένος',
    'native':'εργοστασιακός',
    'HDMI-CEC support (on/off from TV)':'HDMI-СEC υποστήριξη (on/off από TV)',
    'Type of player for streaming':'Είδος αναπαραγωγέα',
    'Autostart of player':'Έναρξη αναπαραγωγέα κατά το άνοιγμα',
    'Buffer Size, s':'Μέγεθος buffer, δευτ.',
    'Choose from':'Επιλογές',
    'Settings':'Ρυθμίσεις',
    'Change value':'Αλλαγή τιμής',
    'Save Settings':'Αποθήκευση ρυθμίσεων',
    'To begining':'Στην αρχή',
    'Live':'Απευθείας μετάδοση',
    ' m ':' λεπτά ',
    ' s':' δευτ.',
    '1 minute':'1 λεπτό',
    '10 Seconds':'10 δευτ.',
    'Go to':'Μετάβαση',
    'Archive - begin':'Αρχείο – αρχή εκπομπής',
    'Pause':'Παύση',
    'Play':'Αναπαραγωγή',
    'Shutdown after %1 seconds<br/><br/>Cancel - any action':'Απενεργοποίηση σε %1 δευτερόλεπτα<br/><br/>Ακύρωση – οποιαδήποτε ενέργεια',
    'Do you want to exit player?':'Έξοδος από το πρόγραμμα?',
    'Color':'Χρώμα',
    'Saturation':'Φωτεινότητα',
    'Yellow':'Κίτρινο',
    'Green':'Πράσινο',
    'Blue':'Γαλάζιο',
    'Set':'Ρύθμιση',
    'Restart stream':'Επανεκκίνηση ροής',
    'Favorites':'Αγαπημένα',
    'All':'Όλα',
    '<br/>Processing the channel list...':'<br/>Επεξεργασία λίστας καναλιών...',
    '<br/>Start playback...':'<br/>Έναρξη αναπαραγωγής...',
    '<br/>Channel list not received !!!':'<br/>Δεν ελήφθη λίστα καναλιών!!!',
    'Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>':' Δεν ελήφθη λίστα καναλιών!!!<br/><br/>Εισάγετε τα στοιχεία του παρόχου και επανεκκινήστε το πρόγραμμα!!!<br/><br/>',
    'Error getting channel list !!!':'Λάθος κατά τη λήψη λίστας καναλιών!!!',
    'system':'συστήματος',
    'Choose provider':'Επιλογή παρόχου',
    '<br>Rewind<br>':'<br>Γρήγορη αναπαραγωγή<br>',
    '<br>Menu':'<br>Μενού',
    '<br>Pause<br>':'<br>Παύση<br>',
    '<br>Toggle<br>sound track':'<br>Αλλαγή<br>ακολουθίας ήχου',
    '<br>Live':'<br>Απευθείας μετάδοση',
    '<br>Previous<br>channel':'<br>Προηγούμενο<br>κανάλι',
    '<br/><b>Failed to load provider script !!!</b>':'<br/><b>Αδυναμία φόρτωσης script παρόχου!!!</b>',
    '<br/>Loading provider %1 script ...':'<br/>Φόρτωση script παρόχου %1 ...',
    '<br/>Loading settings...':'<br/>Φόρτωση ρυθμίσεων...',
    '<br/>Loading channel list...':'<br/>Φόρτωση λίστας καναλιών...',
    'Choose language':'Επιλογή γλώσσας',
    'Change interface language':'Αλλαγή γλώσσας διεπαφής',
    'Aspect':'Αναλογία οθόνης',
    'Audio':'Ηχητική ακολουθία',
    'Stalker portals':'Stalker πύλες',
    'm3u-m3u8 playlists':'m3u-m3u8 λίστες καναλιών',
    '<br/>Loading STB...':'<br/>Φόρτωση STB...',
    '<br/>Setup STB...':'<br/>Ρύθμιση STB...',
    'Save settings to storage':'Αποθήκευση ρυθμίσεων στο φλασάκι',
    'Load settings from storage':'Φόρτωση ρυθμίσεων από το φλασάκι',
    'Download':'Κατέβασμα',
    'Skip this version':'Παράλειψη αυτής της έκδοσης',
    'Volume control':'Ρύθμιση έντασης ήχου',
    'Long button presses':'Διαρκές πάτημα κουμπιών',
    'Download new version Android App':'Κατέβασμα νέας έκδοσης εφαρμογής',
    'To access you must enter url, username and password!':'Για την πρόσβαση είναι υποχρεωτική η εισαγωγή διεύθυνσης, ονόματος και κωδικού πρόσβασης!',
    'Failed to load channel list!':'Αδυναμία φόρτωσης λίστας καναλιών!',
    'Year':'Χρονία',
    'Duration':'Διάρκεια',
    'Genre':'Κατηγορία',
    'Country':'Χώρα',
    'Director':'Σκηνοθέτης',
    'Actors':'Ηθοποιοί',
    'Release date':'Ημερ. κυκλοφορίας',
    'Rating':'Αξιολόγηση',
    'Season':'Σεζόν',
    'Episodes':'Αριθμός επεισοδίων',
    'VOD':'Ταινίες και βίντεο',
    'TV series':'Τηλεοπτικές σειρές',
    'Episode':'Επεισόδιο',
    'Download! Wait ...':'Φόρτωση! Περιμένετε ...',
    'Server':'Σέρβερ',
    'URL':'Ηλ. διεύθυνση',
    'Username':'Όνομα χρήστη',
    'Password':'Κωδικός',
    'Stream type':'Τύπος ροής',
    'Account info':'Πληροφορίες συνδρομής',
    'Select server number from 1 to 6 to save data':'Επιλέξτε αριθμό σέρβερ από 1 έως 6 για αποθήκευση δεδομένων',
    ' (after changing, restart player)':' (μετά τις αλλαγές επανεκκίνηση του προγράμματος)',
    ' (after changing, switch the channel!)':' (μετά τις αλλαγές αλλάξτε κανάλι!)',
    'Enter URL of server':'Εισάγετε ηλ. διεύθυνση σέρβερ',
    'Enter username':'Εισάγετε όνομα χρήστη',
    'Enter password':'Εισάγετε κωδικό',
    'Select stream type':'Επιλέξτε τον τύπο ροής',
    '??? No channel name':'??? Δεν υπάρχει όνομα καναλιού',
    'Playlist URL':'Ηλ. διεύθυνση λίστας καναλιών',
    'Archive hours':'Αριθμός ωρών αρχείου',
    'Enter playlist URL':'Εισάγετε ηλ. διεύθυνση λίστας καναλιών',
    'Enter playlist archive hours':'Εισάγετε αριθμό ωρών αρχείου λίστας καναλιών',
    'show on-screen keyboard':'εμφάνιση πληκτρολογίου οθόνης',
    'Sleep without leaving player':'Σε αναστολή χωρίς έξοδο από το ρπόγραμμα',
    'PiP is not available!':'PiP μη διαθέσιμο!',
    'NORMAL':'ΚΑΝΟΝΙΚΟ',
    'ENLARGE':'ΜΕΓΕΘΥΝΣΗ',
    'MAKE_WIDER':'ΜΕΓΕΘΥΝΣΗ ΠΛΑΤΟΥΣ',
    'NON_LINEAR_STRETCH':'ΜΗ ΓΡΑΜΜΙΚΗ ΕΚΤΑΣΗ',
    'NON_LINEAR_STRETCH_TO_FULL_SCREEN':' ΜΗ ΓΡΑΜΜΙΚΗ ΕΚΤΑΣΗ ΣΕ ΠΛΗΡΗ ΟΘΟΝΗ',
    'MAKE_TALLER':'ΑΥΞΗΣΗ ΥΨΟΥΣ',
    'CUT_EDGES':'ΑΠΟΚΟΠΗ ΑΚΡΩΝ',
    'FULL_SCREEN':'ΠΛΗΡΗΣ ΟΘΟΝΗ',
    'STRETCH_TO_FULL_SCREEN':' ΕΚΤΑΣΗ ΣΕ ΠΛΗΡΗ ΟΘΟΝΗ',
    'Background color':'Χρώμα φόντου',
    'Brightness':'Φωτεινότητα',
    '3 hours':'3 ώρες',
    'Restart stream / Live':'Επανεκκίνηση ροής / Απευθείας μετάδοση',
    '- keyboard': '- πληκτρολόγιο',
    'Media':'Βιβλιοθήκη πολυμέσων',
    'String for search':'Γραμμή αναζήτησης',
    'Playlist Name':'Όνομα λίστας καναλιών',
    'Enter playlist Name':'Εισαγωγή ονόματος λίστας καναλιών',
    'Media Library URL':'Διεύθυνση βιβλιοθήκης πολυμέσων',
    'Enter Media Library URL':'Εισαγωγή διεύθυνσης βιβλιοθήκης πολυμέσων',
    'Playlist':'Λίστα καναλιών',
    'Select playlist':'Επιλογή λίστας καναλιών',
    'Edit':'Επεξεργασία',
    'Load':'Φόρτωση',
    'Edit playlist data':'Επεξεργασία περιεχομένου λίστας καναλιών',
    'Select portal':'Επιλογή πύλης',
    'Portal Name':'Όνομα πύλης',
    'Enter Portal Name':'Εισαγωγή ονόματος πύλης',
    'Edit portal data':'Επεξεργασία στοιχείων πύλης',
    'without':'χωρίς',
    'Settings STB':'Ρυθμίσεις συσκευής',
    'Soft audio render':'Αποκωδικοποίηση ήχου από λογισμικό',
    'Long press horizontal arrows for volume control':'Αλλαγή έντασης ήχου μέσω οριζ. βελών',
    'Yes':'Ναι',
    'Back':'Πίσω',
    'Show providers?':'Προβολή επιλογής παρόχων?',
    'Hide providers?':'Απόκρυψη επιλογής παρόχων?',
    'Show provider settings?':'Προβολή ρυθμίσεων παρόχου?',
    'Hide provider settings?':'Απόκρυψη ρυθμίσεων παρόχου?',
    'Clear all settings?':'Διαγραφή όλων των ρυθμίσεων?',
    'Timer':'Χρονοδιακόπτης',
    'Set timer?':'Ρύθμιση χρονοδιακόπτη?',
    'Remove timer?':'Διαγραφή χρονοδιακόπτη?',
    'Timer: switch to channel?':'Χρονοδιακόπτης: αλλαγή σε κανάλι?',
    ' (if archive exists)':' (σε ύπαρξη αρχείου καναλιού)',
    'Preffered audio track':'Προτιμώμενη ακολουθία ήχου',
    'Information':'Πληροφορίες',
    'Lists settings':'Ρύθμιση λιστών',
    'Channel list settings':'Ρύθμιση λίστας καναλιών',
    'Buttons settings':'Ρύθμιση κουμπιών τηλεκοντρόλ',
    'Subtitle':'Υπότιτλοι',
    'Switch subtitle':'Αλλαγή υπότιτλων',
    'Off':'Απενεργοποίηση',
    'Not found':'Δεν υπάρχουν',
    'History of watched movies':'Ιστορικό προβολών',
    'Continue watching?':'Συνέχεια προβολής?',
    'Add to favorites':'Προσθήκη στα αγαπημένα',
    'Delete':'Διαγραφή',
    'Info about current stream':'Πληροφορίες για την τρέχουσα ροή',
    'Stop':'Στοπ',
    'Playlist file':'Αρχείο λίστας καναλιών',
    'Select playlist file':'Επιλογή αρχείου λίστας καναλιών',
    'Graphical indication':'Γραφική ένδειξη',
    'Background color of selected item':'Χρώμα φόντου επιλογής',
    'Default':'Προεπιλογή',
    'Not supported!':'Δεν υποστηρίζεται!',
    'Menu items settings':'Ρύθμιση στοιχείων μενού',
    'Select menu items':'Επιλέξτε τα στοιχεία του μενού',
    'Protect Adult Channels':'Προστασία καναλιών “για ενήλικες”',
    'Protect Settings':'Προστασία ρυθμίσεων',
    'Protect Change Provider':'Προστασία εναλλαγής παρόχου',
    'Infobar settings':'Ρυθμίσεις του infobar',
    'Show when switching':'Εμφάνιση κατά την αλλαγή καναλιού',
    'Show when changing program':' Εμφάνιση κατά την αλλαγή προγράμματος',
    'Show when rewind':'Εμφάνιση κατά τη γρήγορη αναπαραγωγή',
    'Archive. Category: ':'Αρχείο. Κατηγορία: ',
    'Sort channels':'Ταξινόμηση',
    '"As Is"':'"Ως έχει"',
    'Load playlist':'Φόρτωση λίστας καναλιών',
    ' (after changing, load playlist)':' (μετά τις αλλαγές, φόρτωση αρχείου καναλιών)',
    'Statistics of current stream':'Στατιστική τρέχουσας ροής',
    'Search':'Αναζήτηση',
// 14.6
    'Behavior of %1/%2 buttons in lists':'Λειτουργία κουμπιών %1/%2 στις λίστες',
    'begin/end':'αρχή/τέλος',
    'Position shift -10 seconds after pause':'Μετακίνηση θέσης κατά -10 λεπτά μετά την παύση',
    'Remember previous channels':'Απομνημόνευση προηγούμενων καναλιών',
    'History in Media Library':'Ιστορικό προβολής στη βιβλιοθήκη πολυμέσων',
// 5.11
    'Manage settings':'Διαχείριση ρυθμίσεων',
    'Save settings':'Αποθήκευση ρυθμίσεων',
    'Load settings':'Φόρτωση ρυθμίσεων',
    'Clear settings':'Διαγραφή ρυθμίσεων',
    'Send settings':'Αποστολή ρυθμίσεων στο σέρβερ',
    'Settings sended!':'Οι ρυθμίσεις έχουν αποσταλεί στο σέρβερ!',
    'For download settings file open':'Για κατέβασμα του αρχείου ρυθμίσεων ανοίξτε',
    'and enter code':'και εισάγετε τον κωδικό',
    'or scan':'ή σκανάρετε',
    'Send request':'Αποστολή αιτήματος στο σέρβερ',
    'Request sended!':'Το αίτημα εστάλη στο σέρβερ!',
    'For upload settings file open':'Για ανέβασμα του αρχείου ρυθμίσεων ανοίξτε',
    'Enter Provider Code':'Εισαγωγή κωδικού παρόχου',
    'Error Code!':'Λάθος κωδικός!!!',
    'For enter value open':'Για εισαγωγή τιμής ανοίξτε',
    'First Run Setup':'Ρυθμίσεις κατά την αρχική εκκίνηση',
    'Enter Provider Code on PC or Phone':'Εισαγωγή κωδικού παρόχου από τον υπολογιστή ή κινητό',
    'Manual setup':'Χειροκίνητη ρύθμιση',
    'Access settings':'Ρυθμίσεις πρόσβασης',
// 26.1
    'Script':'Σενάριο',
    'Producer':'Παραγωγός',
    'Operator':'Οπερατέρ',
    'Composer':'Συνθέτης',
    'Artist':'Ζωγράφος',
    'Installation':'Μοντάζ',
    'Budget':'Προϋπολογισμός',
    'Audience':'Κοινό',
    'Premiere world':'Παγκόσμια πρεμιέρα',
    'Display settings':'Ρυθμίσεις εμφάνισης',
    'Age':'Ηλικία',
    'Sort':'Ταξινόμηση',
    'by name':'με ονομασία',
    'by adding':'πότε προστέθηκε',
    'Order':'Σειρά',
    'asc':'αύξουσα',
    'desc':'φθίνουσα',
    'Language':'Γλώσσα',
    'Quality':'Ποιότητα',
    'Show program name':'Ένδειξη ονόματος εκπομπής',
    'Show description':'Ένδειξη περιγραφής εκπομπής',
    'transparent':'διαφανείς',
// 23.3
    'Rewind step by buttons %1/%2':'Βήμα γρήγορης αναπαραγωγής με κουμπιά %1/%2',
}
