keyStrings = {
    'lang':'עברית',
    'alhabet':'אבגדהוזחטיכךלמןסעפףצץקרדת',
    'Channel list. Category: ':'רשימת ערוצים. קטגוריה: ',
    'EPG':'לוח שידורים',
    'Category':'קטגוריה',
    'Actions':'פעולות',
    'Description':'תיאור',
    'Open in PiP':'פתח ב- PiP',
    'Move channel up':'הזז את הערוץ למעלה',
    'Move channel down':'הזז את הערוץ למטה',
    'Delete channel':'למחוק ערוץ',
    'Add channel to category':'הוספת ערוץ לקטגוריה',
    'Add channel to favorites':'הוספת ערוץ למעודפים',
    'Channel parental control':'בקרת הורים בערוץ',
    'Channel is not available!!!':'הערוץ אינו זמין!!!',
    'min':'דקה',
    'Channel ':'ערוץ ',
    ' added to category ':' נוסף לקטגוריה ',
    ' added to favorites':' נוסף למועדפים',
    'Favorites':'מעודפים',
    'Select category to add channel':'בחירת קטגוריה להוספת ערוץ',
    'Enter parental code':'הזן קוד בקרת הורים',
    'Wrong parental code !!!':'קוד בקרת הורים לא חוקי !!!',
    '<br>Up<br>':'<br>למעלה<br>',
    '<br>Delete':'<br>לִמְחוֹק',
    '<br>Add<br>to favorites':'<br>להוסיף<br>למעודפים',
    '<br>Add<br>to category':'<br>להוסיף<br>לקטגוריה',
    '<br>Parental<br>Control':'<br>בקרת<br>הורים',
    '<br>Down':'<br>למטה',
    'Close':'לסגור',
    'Edit category name':'עריכת שם קטגוריה',
    'Category %1 already exists!':'קטגוריה 1% כבר קיימת!',
    'Enter name for new category':'הזן שם לקטגוריה החדשה',
    '<br>More...<br>':'<br>עוד...<br>',
    '<br>Rename':'<br>להחליף שם',
    '<br>Copy<br>category':'<br>לעתיק<br>קטגוריה',
    '<br>Back<br>':'<br>חזרה<br>',
    '<br>Create<br>category':'<br>ליצור<br>קטגוריה',
    'Category selection':'בחירת קטגוריה ערוצים',
    'Menu':'תפריט',
    'Channel list':'רשימת ערוצים',
    'Move category up':'להזיז קטגוריה למעלה',
    'Move category down':'להזיז קטגוריה למטה',
    'Create category':'ליצור קטגוריה',
    'Rename category':'לשנות שם לקטגוריה',
    'Copy category':'להעתיק קטגוריה',
    'Delete category':'למחוק קטגוריה',
    // 'Su Mo Tu We Th Fr Sa':'א ב ג ד ה ו ת',
    'EPG and archive. Channel: ':'לוח שידורים והקלטות: ',
    'By alphabet':'לפי אלף בית',
    'Archive. Channel: ':'הקלטות. ערוץ: ',
    'By time':'בזמן',
    'Player info:':'מידע על נגן:',
    'Device info:':'מידע על ממיר:',
    '- switch:':'- החלפה:',
    '- erase':'- למחוק',
    '- move cursor':'- העבר את הסמן',
    '- return without save':'- חזור בלי לשמור',
    '- save':'- לזכור',
    'Return to previous channel':'חזור לערוץ הקודם',
    'Call PiP / PiP exchange':'הזמן PiP / החלף מקורות PiP',
    'Info about TV program':'קורא מידע לשידור',
    'Show player menu':'קורא את תפריט הנגן',
    'Interface settings':'הגדרות ממשק',
    'Show channel selection list':'הצג את רשימת בחירת הערוצים',
    'Hide / Return':'הסרת מידע / חזרה',
    'Exit player':'צא מהנגן',
    'Show EPG and archive for channel':'הצג לוח שידורים וארכיון הערוצים',
    'Channel category selection':'בחירת קטגוריית ערוצים',
    'Toggle Aspect Ratio':'החלף את יחס הממדים של המסך" (Aspect Ratio)',
    'Toggle Zoom Mode':'החלף מצב זום',
    'Switch sound track':'החלפת פס קול',
    'In live mode: <br/>':'עבור למצב שידור חי:<br/>',
    'Channel selection by number':'בחירת ערוץ לפי מספר',
    'Timeshift: to start of TV program':'שינוי הזמן: בתחילת ההעברה',
    'Timeshift: one minute back':'שינוי הזמן: לפני דקה',
    '<br/><br/>In archive mode:<br/>':'<br/><br/>מעבר לבמצב תצוגת ארכיון:<br/>',
    'Pause/Play':'הפסקה/השמעה',
    'Stop playback and return to In live mode':'הפסק שידור וחזור לשידור חי',
    'To start of TV program / Previous TV program':'התחל מחדש / חזרה לתוכנית קודמת',
    'Next TV program':'תוכנית הבאה',
    'Back / Forward for 1 minute':'הרצה / קדימה למשך 1 דקות',
    'Back / Forward for 15 seconds':'הרצה / קדימה למשך 15 שניות',
    'Back / Forward for 3 minutes':'הרצה / קדימה למשך 3 דקות',
    'Back / Forward for 10 minutes':'הרצה / קדימה למשך 10 דקות',
    'Show rewind window':'קורא לחלון הרצה אחורה',
    'Description of remote control buttons':'תיאור הפונקציות של לחצני השלט הרחוק',
    'Description of remote control buttons depending on the view mode':'תיאור הפונקציות של לחצני השלט הרחוק בהתאם למצב התצוגה',
    'Set parental code':'הגדר קוד בקרת הורים',
    'Repeat parental code':'חזור על קוד בקרת הורים',
    'Show list of channel archive records':'הצג רשימת הקלטות של ערוץ',
    'Show list of channel archive records without duplication':'הצג רשימת ארכיון ללא כפולים',
    'Show Media Library':'הזמן ספריית וידאו',
    'Show Media Library (if available from provider)':'הזמן ספריית וידאו (אם הספק מספק)',
    'Rewind':'הרצה',
    'Close PiP':'לסגור PiP',
    'Parental control':'בקרת הורים',
    'Change provider':'החלפת ספק',
    'Change provider - you can change the provider, and it will be remembered at the next start of player!':'החלף ספק - אתה יכול להחליף ספק, והוא ייזכר בפעם הבאה שתתחיל!',
    'Restart player':'הפעל מחדש את אפליקציה',
    'Restart player - after changing provider settings (as example)':'הפעל מחדש את הנגן - למשל לאחר שינוי הגדרות הספק',
    'Description of remote control buttons':'תיאור לחצני שלט רחוק',
    'About':'מידע',
    'Player and device info':'מידע על נגן ומכשיר',
    'Donate <div class="btn" style="background-color:orange;">donate</div>':'עזור לפרויקט <div class="btn" style="background-color:orange;">donate</div>',
    'Voluntary donation for the development of project':'סיוע מרצון לפיתוח הפרויקט',
    'Settings saved':'ההגדרות נשמרו',
    'no':'לא',
    'yes':'כן',
    'Records':'הקלטות',
    'Previous':'קודם',
    'Info':'מידע',
    'Not reduce video when showing the list (bugfix)':'אל תתקרב לקטעי וידיאו בעת התקשרות לרשימה (bugfix)',
    'Black screen while switching the channel':'מסך שחור בעת החלפת ערוץ',
    'PiP window size':'גודל חלון PiP',
    'small':'קטן',
    'medium':'ממוצע',
    'large':'גדול',
    'PiP window position':'מיקום חלון ה- PiP',
    'top-right':'ימין למעלה',
    'bottom-right':'מימין למטה',
    'left-bottom':'שמאל למטה',
    'top-left':'שמאל למעלה',
    'Number of rows in lists':'מספר השורות ברשימות',
    'Distance between lines in lists':'מרחק בין שורות ברשימות',
    'Font type':'סוג גופן',
    'volume':'עוצמת קול',
    'paging':'החלפה',
    'Nothing':'שום דבר',
    'Exit':'יציאה',
    'Joystick':'מוט הגוי',
    'Button %1 function when viewing':'פונקציה של כפתור %1 בעת הצפייהה',
    'Button function %1 when viewing archive':'פונקצית כפתור %1 בעת צפייה בארכיונים שלהן',
    'Channels':'ערוצים',
    'Remote (color buttons N/A)':'שלט רחוק ללא כפתורים צבעוניים',
    'Remote (number buttons N/A)':'שלט רחוק ללא כפתורי מספר',
    'Timezone':'אזור זמן',
    'Sleep timer':'טיימר שינה',
    'off':'מנותק',
    '30 minutes':'30 דקות',
    '1 hour':'1 שעה',
    '2 hours':'שעתיים',
    'Infobar display timeout, s':'זמן קצוב לתצוגת אינפובאר, ש',
    '"Sliding" infobar':'"תפריט מידע " יוצא"',
    'Interface transparency':'שקיפות ממשק',
    'Volume step, %':'עוצמת קול באחוזים',
    'List location':'מיקום הרשימה',
    'right':'מימין',
    'left':'משמואל',
    'Color spectrum':'ספקטרום צבעים',
    'select':'בחר',
    'Permanent clock on screen':'Постоянные часы на экране',
    'Show channel number in list':'הראה את מספר הערוץ ברשימה',
    'Show picons in channel list':'הראה פסגות ברשימת הערוצים',
    'Show channel name in list':'הראה את שם הערוץ ברשימה',
    'Show progress in channel list':'הראה התקדמות ברשימת הערוצים',
    'Show archive availability in list':'הראה נוכחות של ארכיון ברשימה',
    'Show scrollbar in list':'הראה את סרגל הגלילה ברשימה',
    'Preview in channel list':'תצוגה מקדימה של רשימת הערוצים',
    'always':'תמיד',
    'on ':'על-פי ',
    'Number of next TV programs in channel list':'מספר התוכניות הבאות ברשימת הערוצים',
    'Channel list editing style':'סגנון עריכת רשימה',
    'All categories':'כל הקטגוריות',
    '"Favorites"':'"מועדפים"',
    'Editor':'עוֹרֵך',
    'built-in':'מובנה',
    'native':'מקומי',
    'HDMI-CEC support (on/off from TV)':'תמיכה ב- HDMI-CEC (הפעלה / כיבוי מהטלוויזיה)',
    'Type of player for streaming':'סוג נגן להפעלה',
    'Autostart of player':'הפעל את הנגן כשהוא מופעל',
    'Buffer Size, s':'גודל מאגר, s',
    'Choose from':'אפשרויות',
    'Settings':'הגדרות',
    'Change value':'שינוי ערך',
    'Save Settings':'לשמור הגדרות',
    'To begining':'להתחלה',
    'Live':'שידור חי',
    ' m ':' דקה ',
    ' s':' שניות',
    '1 minute':'דקה 1',
    '10 Seconds':'10 שניות',
    'Go to':'לעבור ל',
    'Archive - begin':'ארכיון - תחילת השידור',
    'Pause':'הַפסָקָה',
    'Play':'נגן',
    'Shutdown after %1 seconds<br/><br/>Cancel - any action':'כיבוי לאחר (1%) שניות<br/><br/>בטל - כל פעולה',
    'Do you want to exit player?':'האם אתה רוצה לצאת מהנגן?',
    'Color':'צבע',
    'Saturation':'רוויה',
    'Yellow':'צהוב',
    'Green':'ירוק',
    'Blue':'כָּחוֹל',
    'Set':'להתקין',
    'Restart stream':'התחל מחדש את התוכנית',
    'Favorites':'מועדפים',
    'All':'הכול',
    '<br/>Processing the channel list...':'<br/>עיבוד רשימת הערוצים ...',
    '<br/>Start playback...':'<br/>התחל ניגון...',
    '<br/>Channel list not received !!!':'<br/>רשימת הערוצים לא התקבלה !!!',
    'Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>':'רשימת הערוצים לא התקבלה !!!<br/><br/>הזן את פרטי הספק והפעל מחדש את הנגן !!!<br/><br/>',
    'Error getting channel list !!!':'שגיאה בקבלת רשימת הערוצים !!!',
    'system':'מערכתית',
    'Choose provider':'בחר ספק',
    '<br>Rewind<br>':'<br>הרצה<br>',
    '<br>Menu':'<br>תַפרִיט',
    '<br>Pause<br>':'<br>הַפסָקָה<br>',
    '<br>Toggle<br>sound track':'<br>החלף<br>פס קול',
    '<br>Live':'<br>שיגור חי',
    '<br>Previous<br>channel':'<br>ערוץ<br>קודם',
    '<br/><b>Failed to load provider script !!!</b>':'<br/><b>טעינת סקריפט הספק נכשלה !!!</b>',
    '<br/>Loading provider %1 script ...':'<br/>טוען סקריפט ספק ( 1% ) ... ',
    '<br/>Loading settings...':'<br/>טוען הגדרות ...',
    '<br/>Loading channel list...':'<br/>טוען רשימת ערוצים ...',
    'Choose language':'בחר שפה',
    'Change interface language':'שנה את שפת הממשק',
    'Aspect':'אספקט',
    'Audio':'פס קול',
    // 'Stalker portals':'Stalker portals',
    'm3u-m3u8 playlists':'m3u-m3u8 פלייליסטים',
    '<br/>Loading STB...':'<br/>טעינה STB...',
    '<br/>Setup STB...':'<br/>הגדרות STB...',
    // 'Save settings to storage':'Save settings to storage',
    // 'Load settings from storage':'Load settings from storage',
    'Download':'להוריד',
    'Skip this version':'דלג על גרסה זו',
    'Volume control':'בקרת עוצמת קול',
    'Long button presses':'לחיצות ארוכות על כפתור',
    'Download new version Android App':'הורד את הגרסה החדשה של מערכת',
    'To access you must enter url, username and password!':'כדי לגשת, עליך להזין את הכתובת, שם המשתמש והסיסמה!',
    'Failed to load channel list!':'טעינת רשימת הערוצים נכשלה!',
    'Year':'שָׁנָה',
    'Duration':'Проמֶשֶׁךдолжительность',
    'Genre':'סיגנון',
    'Country':'מדינה',
    'Director':'במאי',
    'Actors':'שחקנים',
    'Release date':'תאריך הוצאה',
    'Rating':'דֵרוּג',
    'Season':'עונה',
    'Episodes':'פרקים',
    'VOD':'ספריית וידאו',
    'TV series':'סדרות',
    'Episode':'פרק',
    'Download! Wait ...':'טעינה! המשך ...',
    'Server':'שרת',
    'URL':'הכתובת',
    'Username':'שם משתמש',
    'Password':'סיסמא',
    'Stream type':'סוג זרם',
    'Account info':'פרטי מנוי',
    'Select server number from 1 to 6 to save data':'בחר מספר שרת בין 1 ל -6 כדי לשמור נתונים',
    ' (after changing, restart player)':' (לאחר החלפה עליך להפעיל מחדש את הנגן)',
    ' (after changing, switch the channel!)':' (לאחר החלפת ערוץ!)',
    'Enter URL of server':'עריכת כתובת השרת',
    'Enter username':'הכנס שם משתמש',
    'Enter password':'הכנס סיסמא',
    'Select stream type':'בחר סוג זרם',
    '??? No channel name':'??? אין שם ערוץ',
    'Playlist URL':'כתובת פלייליסט',
    'Archive hours':'שעות ארכיון',
    'Enter playlist URL':'הזנת כתובת הפלייליסט',
    'Enter playlist archive hours':'הזנת מספר שעות הארכיון לפלייליסט',
    'show on-screen keyboard':'להעלות את המקלדת שעל המסך',
    'Sleep without leaving player':'להירדם בלי לעזוב את הנגן',
    'PiP is not available!':'PiP אינו זמין!',
    'NORMAL':'רָגִיל',
    'ENLARGE':'להגביר',
    'MAKE_WIDER':'רוחב מוגבר',
    'NON_LINEAR_STRETCH':'מתיחה לא מקוונת',
    'NON_LINEAR_STRETCH_TO_FULL_SCREEN':'מתיחה לא מלאה ללא מסך',
    'MAKE_TALLER':'עלייה בגובה',
    'CUT_EDGES':'קצוות קצוות',
    'FULL_SCREEN':'מסך מלא',
    'STRETCH_TO_FULL_SCREEN':'מתיחת מסך מלא',
    'Background color':'צבע רקע',
    'Brightness':'בְּהִירוּת',
    '3 hours':'3 שעות',
    'Restart stream / Live':'הפעל מחדש את הזרם / השידור החי',
    '- keyboard': '- מקלדת',
    'Media':'מדיה',
    'String for search':'שורת חיפוש',
    'Playlist Name':'שם הפלייליסט',
    'Enter playlist Name':'הזנת שם הפלייליסט',
    'Media Library URL':'כתובת הספרייה',
    'Enter Media Library URL':'הזנת כתובת הספרייה',
    'Playlist':'פלייליסט',
    'Select playlist':'בחר פלייליסט',
    'Edit':'לַעֲרוֹך',
    'Load':'הורד',
    'Edit playlist data':'עריכת נתוני פלייליסט',
    'Select portal':'בחר פורטל',
    'Portal Name':'בחר פורטל',
    'Enter Portal Name':'הזנת שם הפורטל',
    'Edit portal data':'עריכת נתוני פורטל',
    'without':'לְלֹא',
    'Settings STB':'הגדרות מכשיר STB',
    'Soft audio render':'לפענח אודיו בתכנות',
    'Long press horizontal arrows for volume control':'שליטה על עוצמת הקול על ידי החזקת חצים אופקיים',
    'Yes':'כן',
    'Back':'אחורה',
    'Show providers?':'להציג מבחר ספקים?',
    'Hide providers?':'להסתיר את בחירת הספקים?',
    'Show provider settings?':'להציג הגדרות ספק?',
    'Hide provider settings?':'להסתיר את הגדרות הספק?',
    'Clear all settings?':'למחוק את כל ההגדרות?',
    'Timer':'טיימר',
    'Set timer?':'הגדר טיימר?',
    'Remove timer?':'למחוק טיימר?',
    'Timer: switch to channel?':'טיימר: לעבור לערוץ?',
    ' (if archive exists)':' (אם יש ארכיון ערוצים)',
    'Preffered audio track':'רצועת שמע מועדפת',
    'Information':'מֵידָע',
    'Lists settings':'הגדרות רשימה',
    'Channel list settings':'הגדרות רשימת ערוצים',
    'Buttons settings':'הגדרות לחצן מרחוק',
    'Subtitle':'כתוביות',
    'Switch subtitle':'החלף כתוביות',
    'Off':'לכבות',
    'Not found':'חסר',
    'History of watched movies':'היסטוריה של סרטים נצפים',
    'Continue watching?':'להמשיך לצפות?',
    'Add to favorites':'הוסף למועדפים',
    'Delete':'לִמְחוֹק',
    'Info about current stream':'מידע על הזרם הנוכחי',
    'Stop':'לַעֲצוֹר',
    'Playlist file':'קובץ פלייליסט',
    'Select playlist file':'בחר קובץ פלייליסט',
    'Graphical indication':'אינדיקציה גרפית',
    'Background color of selected item':'צבע הרקע של הפריט שנבחר',
    'Default':'בְּרִירַת מֶחדָל',
    'Not supported!':'לא נתמך!',
    'Menu items settings':'הגדרות פריטי תפריט',
    'Select menu items':'בחר פריטי תפריט',
// 13.5
    'Protect Adult Channels':'הגן על ערוצים למבוגרים',
    'Protect Settings':'הגן על הגדרות',
    'Protect Change Provider':'Защита смены провайдера',
    'Infobar settings':'הגדרות אינפובר',
    'Show when switching':'הצג בעת מעבר',
    'Show when changing program':'הצג בעת שינוי תוכנית',
    'Show when rewind':'הצג כאשר אחורה',
    'Archive. Category': 'ארכיון. קטגוריה:',
    'Sort channels':'מִיוּן',
    '"As Is"':'"כמו שזה"',
    'Load playlist':'טען רשימת השמעה',
    ' (after changing, load playlist)':' (לאחר השינוי, טען רשימת השמעה)',
    'Statistics of current stream':'סטטיסטיקות זרם עדכניות',
    'Search':'חפש',
// 14.6
    'Behavior of %1/%2 buttons in lists':'התנהגות הכפתורים %2/%1 ברשימה שלה',
    'begin/end':'התחלה /סוף',
    'Position shift -10 seconds after pause':'משמרת מיקום ב -10 שניות לאחר ההשהיה',
    'Remember previous channels':'זכרו ערוצים קודמים',
    'History in Media Library':'דפדוף בהיסטוריה בספריית המדיה',
// 5.11
    'Manage settings':'ניהול הגדרות',
    'Save settings':'שמור הגדרות',
    'Load settings':'טען הגדרות',
    'Clear settings':'נקה הגדרות',
    'Send settings':'שליחת הגדרות לשרת',
    'Settings sended!':'הגדרות נשלחות לשרת!',
    'For download settings file open':'כדי להוריד את קובץ ההגדרות פתח',
    'and enter code':'והזן את הקוד',
    'or scan':'או לסרוק',
    'Send request':'שליחת בקשה לשרת',
    'Request sended!':'הבקשה נשלחה לשרת!',
    'For upload settings file open':'כדי להוריד את קובץ ההגדרות פתח',
    'Enter Provider Code':'הזנת קוד ספק',
    'Error Code!':'שגיאת קוד !!!',
// 7.12
    'For enter value open':'להזנת ערך, פתח',
    'First Run Setup':'התקנה ראשונה',
    'Enter Provider Code on PC or Phone':'הזנת קוד הספק במחשב או טלפון',
    'Manual setup':'הגדרה ידנית',
// 17.1
    'Access settings':'הגדרות גישה',
}
