keyStrings = {
    'lang':'Magyar',
    'alhabet':'aábccsddzdzseéfggyhiíjkllymnnyoóöőpqrsszttyuúüűvwxyzzs',
    'Channel list. Category: ':'Csatorna lista. Kategória: ',
    'EPG':'Program',
    'Category':'Kategóriák',
    'Actions':'Művelet',
    'Description':'Leirás',
    'Open in PiP':'PiP megnyitás',
    'Move channel up':'Csatorna mozgatása fel',
    'Move channel down':'Csatorna mozgatása le',
    'Delete channel':'Csatorna eltávolitása',
    'Add channel to category':'Csatorna hozzáadása kategóriához',
    'Add channel to favorites':'Csatorna hozzáadása a kedvencekhez',
    'Channel parental control':'Szülői felügyelet',
    'Channel is not available!!!':'Csatorna nem elérhető!!!',
    'min':'perc',
    'Channel ':'Csatorna ',
    ' added to category ':' Kategóriához adva ',
    ' added to favorites':'Kedvencekhez adva',
    'Favorites':'Kedvencek',
    'Select category to add channel':'Mategória kiválasztása csatorna hozzáadásához',
    'Enter parental code':'Adja meg a szülői felügyelet kódot',
    'Wrong parental code !!!':'Rossz kód !!!',
    '<br>Up<br>':'<br>Fel<br>',
    '<br>Delete':'<br>Eltávolitani',
    '<br>Add<br>to favorites':'<br>Hozzáadni<br>a kedvencekhez',
    '<br>Add<br>to category':'<br>Hozzáadni<br>a ketegóriába',
    '<br>Parental<br>Control':'<br>Szülői<br>felügyelet',
    '<br>Down':'<br>Le',
    'Close':'Bezárni',
    'Edit category name':'Kategória szerkesztése',
    'Category %1 already exists!':'Kategória %1 már létezik !',
    'Enter name for new category':'Irja be az új kategória nevét',
    '<br>More...<br>':'<br>Még...<br>',
    '<br>Rename':'<br>Átnevezés',
    '<br>Copy<br>category':'<br>Másolás<br>kategóriába',
    '<br>Back<br>':'<br>Vissza<br>',
    '<br>Create<br>category':'<br>Létrehoz<br>kategóriát',
    'Category selection':'Csatorna kategória kiválasztása',
    'Menu':'Menu',
    'Channel list':'Csatorna lista',
    'Move category up':'Kategória mozgatása fel',
    'Move category down':'Kategória mozgatása le',
    'Create category':'Kategória létrehozása',
    'Rename category':'Kategória átnevezése',
    'Copy category':'Kategória másolása',
    'Delete category':'Kategória eltávolitása',
    'Su Mo Tu We Th Fr Sa':'Vas Hét Ked Sze Csü Pén Szo',
    'EPG and archive. Channel: ':'Müsör és arhivum. Csatorna: ',
    'By alphabet':'Abc sorrend',
    'Archive. Channel: ':'Arhivum. Csatorna: ',
    'By time':'Idő szerint',
    'Player info:':'Lejátszó információ:',
    'Device info:':'Eszköz információ:',
    '- switch:':'- váltás:',
    '- erase':'- törlés',
    '- move cursor':'- kurzor mozgatása',
    '- return without save':'- vissza mentés nélkül',
    '- save':'- mentés',
    'Return to previous channel':'Vissza az előzó csatornához',
    'Call PiP / PiP exchange':' PiP /PiP forrás csere',
    'Info about TV program':'Információ az adásról',
    'Show player menu':'Lejátszó menü előhivása',
    'Interface settings':'Interfész beálitás',
    'Show channel selection list':'Csatorna lista előhivás',
    'Hide / Return':'Információ eltávolitása / vissza',
    'Exit player':'Kilépés a lejátszóből',
    'Show EPG and archive for channel':'Müsörújság előhivása és az arhivum megjelenitése',
    'Channel category selection':'Csatorna kategória választása',
    'Toggle Aspect Ratio':'Váltás "képméret-arány" (Aspect Ratio)',
    'Toggle Zoom Mode':'Zoom',
    'Switch sound track':'Audió csatorna váltás',
    'In live mode: <br/>':'ő adás:<br/>',
    'Channel selection by number':'Csatorna választás szám alapján',
    'Timeshift: to start of TV program':'Тimeshift adás elejére',
    'Timeshift: one minute back':'Timeshift: egy percre vissza',
    '<br/><br/>In archive mode:<br/>':'<br/><br/>Arhivum mode:<br/>',
    'Pause/Play':'Szünet/Lejátszás',
    'Stop playback and return to In live mode':'Lejátszás leállitása és vissza az élő adáshoz',
    'To start of TV program / Previous TV program':'Adás elejére/ kovetkezö adás',
    'Next TV program':'Következő adás',
    'Back / Forward for 1 minute':'Vissza / Előre 1 perc',
    'Back / Forward for 15 seconds':'Vissza / Előre 15 masodpercet',
    'Back / Forward for 3 minutes':'Vissza / Előre 3 percet',
    'Back / Forward for 10 minutes':'Vissza / Előre 10 percet',
    'Show rewind window':'Tekerő ablak előhivása',
    'Description of remote control buttons':'Távirányitó gombjainak leirása',
    'Description of remote control buttons depending on the view mode':'Távirányitó gombjainak leirása, müsor megtekintés függő',
    'Set parental code':'Adja meg a szülői felügyelet kódot',
    'Repeat parental code':'Ismételje meg a kódot',
    'Show list of channel archive records':'Arhivum lista előhivása',
    'Show list of channel archive records without duplication':'Arhivum előhivása ismétlések nélkül',
    'Show Media Library':'Videótár',
    'Rewind':'Tekerés',
    'Close PiP':'PiP bezárás',
    'Parental control':'Szülői felügyelet',
    'Change provider':'Szolgáltató váltás',
    'Change provider - you can change the provider, and it will be remembered at the next start of player!':'Szolgáltató váltás - Le cserélheti a szolgáltatót, mentve lessz a kovetkező inditásnál!',
    'Restart player':'Lejátszó újrainditása',
    // 'Restart player - after changing provider settings (as example)':'Lejátszó újrainditás - P.l. szolgáltató beállitások módósitásakor',
    'Description of remote control buttons':'Távirányitó gombjai leirása',
    'About':'Információ',
    'Player and device info':'Információ a lejátszóról és eszközről',
    'Donate <div class="btn" style="background-color:orange;">donate</div>':'Project segitcség  <div class="btn" style="background-color:orange;">donate</div>',
    'Voluntary donation for the development of project':'Добровольная помощь на развитие проекта',
    'Settings saved':'Beállitások mentve',
    'no':'nem',
    'yes':'igen',
    'Records':'Felvételek',
    'Previous':'Előző',
    'Info':'Infó',
    'Not reduce video when showing the list (bugfix)':'Ne csökentcse a videót a lista megjelenitésekor (bugfix)',
    'Black screen while switching the channel':'Fekete kijelző csatorna váltáskor',
    'PiP window size':'PiP ablak mérete',
    'small':'kicsi',
    'medium':'közepes',
    'large':'Nagy',
    'PiP window position':'PiP ablak helyzete',
    'top-right':'jobra-fel',
    'bottom-right':'jobra-le',
    'left-bottom':'balra-le',
    'top-left':'balra-fel',
    'Number of rows in lists':'Sorok mennyisége a listákban',
    'Distance between lines in lists':'Távolság a sorok kozott a listákban',
    'Font type':'Betűtipus',
    'volume':'hangerő',
    'paging':'váltás',
    'Nothing':'Semmi',
    'Exit':'Kijárat',
    'Joystick':'Jojsztik',
    'Button %1 function when viewing':'Gomb funkció %1 lejátszás kozben',
    'Button function %1 when viewing archive':'Gomb funkció %1 arhivum lejátszása közben',
    'Channels':'Каналы',
    'Remote (color buttons N/A)':'Szintelen gombos távirányitó',
    'Remote (number buttons N/A)':'Szám nélküli távirámyitó',
    'Timezone':'Idő zóna',
    'Sleep timer':'Elalvás időzitő',
    'off':'kikapcsolva',
    '30 minutes':'30 perc',
    '1 hour':'1 óra',
    '2 hours':'2 óra',
    'Infobar display timeout, s':'Az infobár kijelző tullépése, a',
    '"Sliding" infobar':'"előcsüszó" infobár',
    'Interface transparency':'Interfész átláthatósága',
    'Volume step, %':'Hangositás lépése, %',
    'List location':'Lista elhejeszkedése',
    'right':'jobb oldalon',
    'left':'bal oldalon',
    'Color spectrum':'Szin gamma',
    'select':'Valassz',
    'Permanent clock on screen':'Állandó óra a képernyőn',
    'Show channel number in list':'Csatorna számának kijelzése a listában',
    'Show picons in channel list':'Piconok megjelenitése a csatornák listájában',
    'Show channel name in list':'Csatorna nevének megjelenitése a listában',
    'Show progress in channel list':'Haladás megjelenitése csatornalistában',
    'Show archive availability in list':'Az arhivum elérhetőségének megjelenitése a listában',
    'Show scrollbar in list':'Görgetősáv megjelenitése a listában',
    'Preview in channel list':'Előnézet a csatornák listájában',
    'always':'mindig',
    'on ':'ig',
    'Number of next TV programs in channel list':'A következő tévéműsorok száma a csatornák listájaban',
    'Channel list editing style':'Csatornalista szerkesztési stilus',
    'All categories':'Minden kategória',
    '"Favorites"':'"Kedvencek"',
    'Editor':'Szerkesztő',
    'built-in':'beéjpitett',
    'native':'anyanyelvi',
    'HDMI-CEC support (on/off from TV)':'HDMI-СEC támogatás (be/ki TV től)',
    'Type of player for streaming':'Streaming lejátszó tipusa',
    'Autostart of player':'A lejátszó autómatikus inditása',
    'Buffer Size, s':'Puffer mérete, s',
    'Choose from':'Válassz',
    'Settings':'Beállitások',
    'Change value':'Érték módositása',
    'Save Settings':'Beállitások mentése',
    'To begining':'Az elejére',
    'Live':'Élő adás',
    ' m ':' perc ',
    ' s':' másodperc',
    '1 minute':'1 perc',
    '10 Seconds':'10 másodperc',
    'Go to':'Menj',
    'Archive - begin':'Arhivum - adás elejére',
    'Pause':'Szünet',
    'Play':'Lejátszás',
    'Shutdown after %1 seconds<br/><br/>Cancel - any action':'Kikapcsolás %1 másodperc<br/><br/>Mégse - bármilyen cselekvés',
    'Do you want to exit player?':'Szeretne kilépni a lejátszóból?',
    'Color':'Szin',
    'Saturation':'Telitettcség',
    'Yellow':'Sárga',
    'Green':'Zold',
    'Blue':'Kék',
    'Set':'Beállit',
    'Restart stream':'Stream újrainditása',
    'Favorites':'Kedvencek',
    'All':'Mind',
    '<br/>Processing the channel list...':'<br/>A csatornalista feltolgozása...',
    '<br/>Start playback...':'<br/>Lejátszás inditása...',
    '<br/>Channel list not received !!!':'<br/>Nincs csatornalista!!!',
    'Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>':'Nincs csatornalista!!!<br/><br/>Irja be a szolgáltató adatait és inditcsa újra a lejátszót!!!<br/><br/>',
    'Error getting channel list !!!':'Hiba csatornalista betöltésekor!!!',
    'system':'rendszer',
    'Choose provider':'Válasszon szolgáltatót',
    '<br>Rewind<br>':'<br>Tekerés<br>',
    '<br>Menu':'<br>Menu',
    '<br>Pause<br>':'<br>Szünet<br>',
    '<br>Toggle<br>sound track':'<br>Váltás<br>au.csatornát',
    '<br>Live':'<br>Élő adás',
    '<br>Previous<br>channel':'<br>Előző<br>csatorna',
    '<br/><b>Failed to load provider script !!!</b>':'<br/><b>Nem sikerült betölteni a szolgáltató skriptjét!!!</b>',
    '<br/>Loading provider %1 script ...':'<br/>Szolgáltató skriptjének betöltése %1 ...',
    '<br/>Loading settings...':'<br/>Beállitások betöltése...',
    '<br/>Loading channel list...':'<br/>Csatornalista betöltése...',
    'Choose language':'Nyelv kiválasztása',
    'Change interface language':'Változtassa meg az interfész nyelvét ',
    'Aspect':'Vonatkozás',
    'Audio':'audió. Sáv',
    'Stalker portals':'Stalker portálok',
    'm3u-m3u8 playlists':'m3u-m3u8 lejátszási lista',
    '<br/>Loading STB...':'<br/>STB betöltése...',
    '<br/>Setup STB...':'<br/> STB betöltése...',
    'Save settings to storage':'Beállitások mentése usb tárolóra',
    'Load settings from storage':'Beállitások visszaitása usb tárolóból',
    'Download':'Letoltés',
    'Skip this version':'Verzió kihagyása',
    'Volume control':'Hangerőszabályozó',
    'Long button presses':'Hosszú gombnyomások',
    'Download new version Android App':'Tölcse le az Android app új verzióját ',
    'To access you must enter url, username and password!':'A hozzáféréshez meg kell adnia az URL -t , a felhasználónevet és a jelszót!',
    'Failed to load channel list!':'Nem sikerült betölteni a csatornalistát!',
    'Year':'Év',
    'Duration':'Időtartam',
    'Genre':'Műfaj',
    'Country':'Város',
    'Director':'Rendező',
    'Actors':'Szinészek',
    'Release date':'Kiadási dátum',
    'Rating':'Értékelés',
    'Season':'Évad',
    'Episodes':'Évadok mennyisége',
    'VOD':'Filmek',
    'TV series':'Sorozatok',
    'Episode':'Epizód',
    'Download! Wait ...':'Betöltés! Kérem várjon ...',
    'Server':'Szerver',
    'URL':'Cim',
    'Username':'Felhasználó',
    'Password':'Jelszó',
    'Stream type':'Stream tipusa',
    'Account info':'Előfizetés információ',
    'Select server number from 1 to 6 to save data':'Válasszon szervert 1 től 6 ig az adatok mentéséhez',
    ' (after changing, restart player)':' (adat csere után indítsa újra a lejátszót)',
    ' (after changing, switch the channel!)':' (változtatások után , váltson csatornát!)',
    'Enter URL of server':'Szerver URL szerkesztése',
    'Enter username':'Felhasználó szerkesztése',
    'Enter password':'Jelszó szerkesztése',
    'Select stream type':'Adatfolyam tipusának kiválasztása',
    '??? No channel name':'??? Nincs csatorna név',
    'Playlist URL':'Lejátszásilista cime',
    'Archive hours':'Argivum idő mennyisége',
    'Enter playlist URL':'Csatornalista URL bevitele',
    'Enter playlist archive hours':'Adja meg a lejátszásilista arhiv óráit',
    'show on-screen keyboard':'A képernyón megjelenő billentyuzet megjelenitése',
    'Sleep without leaving player':'Alugy el a lejátszó elhagyása nélkül',
    'PiP is not available!':'PiP nem elérhetö!',
    'NORMAL':'NORMÁL',
    'ENLARGE':'NAGYITÁS',
    'MAKE_WIDER':'SZÉLESSEG NAGYITÁSA',
    'NON_LINEAR_STRETCH':'VONALNÉLKÜLI SZÉTHUZÁS',
    'NON_LINEAR_STRETCH_TO_FULL_SCREEN':'NEM VONALOS FESZITÉS  A KÉPERNYŐHOZ',
    'MAKE_TALLER':'MAGASSÁG NAGYITÁS',
    'CUT_EDGES':'SZÉLEK LEVÁGÁSA',
    'FULL_SCREEN':'TELJES KÉPERNYŐ',
    'STRETCH_TO_FULL_SCREEN':'NYÚITÁS TELYJES KÉPERNYŐRE',
    'Background color':'Háttérszin',
    'Brightness':'Fényerősség',
    '3 hours':'3 óra',
    'Restart stream / Live':'Stream ujrainditása / Élő adás',
    '- keyboard': '- billentyúzet',
    'Media':'Videótár',
    'String for search':'Kereső sáv',
    'Playlist Name':'Csatornalista neve',
    'Enter playlist Name':'Csatornalista név bevitele',
    'Media Library URL':'Videótár URL cime',
    'Enter Media Library URL':'Ввод адреса медиатеки',
    'Playlist':'Плейлист',
    'Select playlist':'Выберите плейлист',
    'Edit':'Szerkesztés',
    'Load':'Betoltés',
    'Edit playlist data':'Lejátszási lista adatainak betoltése',
    'Select portal':'Válasszon portált',
    'Portal Name':'Portál neve',
    'Enter Portal Name':'Portál név bevitele',
    'Edit portal data':'Portál adatainak szerkesztése',
    'without':'nélkül',
    'Settings STB':'Eszköz beállitása',
    'Soft audio render':'Szoftveresen dekódolt hang',
    'Long press horizontal arrows for volume control':'Hosszan nyomja meg a vizszintes a hangerő szabályozásához',
    'Yes':'Igen',
    'Back':'Vissza',
    'Show providers?':'Szolgáltatók megjelenitése?',
    'Hide providers?':'Szolgáltatók elrejtése?',
    'Show provider settings?':'A szolgáltató beállításainak megjelenitése?',
    'Hide provider settings?':'A szolgáltató beállitásainak elrejtése?',
    'Clear all settings?':'Törli az osszes beállitást?',
    'Timer':'Időzitő',
    'Set timer?':'Időzitő beállitása?',
    'Remove timer?':'Időzitő törlése?',
    'Timer: switch to channel?':'Időzitő: váltson csatornára?',
    ' (if archive exists)':' (Ha van csatorna arhivum)',
    'Preffered audio track':'Elsődleges audió sáv',
    'Information':'Információ',
    'Lists settings':'Listák beálitásai',
    'Channel list settings':'Csatornalista beállitásai',
    'Buttons settings':'Távirányitó gombok beállítása',
    'Subtitle':'Felirat',
    'Switch subtitle':'Felirat váltás',
    'Off':'Kikapcsolás',
    'Not found':'Nem található',
    'History of watched movies':'A nézett müsörok története',
    'Continue watching?':'Lejátszás folytatása?',
    'Add to favorites':'Hozzáadás kedvencekhez',
    'Delete':'Törlés',
    'Info about current stream':'Információ az aktuális adatfolyamról',
    'Stop':'Leállit',
    'Playlist file':'Lejátszási lista fálja',
    'Saelect playlist file':'Lehátszási lista kiválasztása',
    'Graphical indication':'Grafikus jelzések',
    'Background color of selected item':'A kijelölt elem háttérszine',
    'Default':'Alapértelmezett',
    'Not supported!':'Nem támogatott!',
    'Menu items settings':'Menűtételek beállitásai',
    'Select menu items':'Menűelemek kiválasztása',
    'Protect Adult Channels':'Felnőtt csatornák védelme',
    'Protect Settings':'Beállitások védelme',
    'Protect Change Provider':'Szolgáltató változtatás védelem',
    'Infobar settings':'Infobár beállitásai',
    'Show when switching':'Megjelenités váltáskor',
    'Show when changing program':'Megjelenités programváltáskor',
    'Show when rewind':'Visszatekerés megjelenitése',
    'Archive. Category: ':'Arhivum. Kategória: ',
    'Sort channels':'Csatornák rendezése',
    '"As Is"':'"Ahogy van"',
    'Load playlist':'Csatornalista betoltése',
    ' (after changing, load playlist)':' (változtatások után, csatornalista betöltése)',
    'Statistics of current stream':'Az aktuális adatfolyam statisztikája',
    'Search':'Keresés',
// 14.6
    'Behavior of %1/%2 buttons in lists':'Gombok viselkedése %1/%2 a.listákban',
    'begin/end':'eleje/vége',
    'Position shift -10 seconds after pause':'Helyzeteltolás -10 másodperccel a szünet után',
    'Remember previous channels':'Emlékezz az előző csatornákra',
    'History in Media Library':'Videótár megtekintés feljégyzése',
// 5.11
    'Manage settings':'Beállitások kezelése',
    'Save settings':'Beállitások mentése',
    'Load settings':'Beállitások betöltése',
    'Clear settings':'Beállitások törlése',
    'Send settings':'Beállitások küldése a szerverre',
    'Settings sended!':'Beállitások elküldve a szerverre!',
    'For download settings file open':'A beállitási fájl letöltéséhez nissa meg',
    'and enter code':'és irja be a kódot',
    'or scan':'vagy szkennelje',
    'Send request':'Felkérés küldése a szerverre',
    'Request sended!':'Felkérés elküldve a szerverre!',
    'For upload settings file open':'A fájl letöltéséhez nissa meg',
    'Enter Provider Code':'Szolgáltató kód bevitele',
    'Error Code!':'Hibás kód!!!',
    'For enter value open':'A beirt értékhez nissa meg',
    'First Run Setup':'Beállitás első inditáskor',
    'Enter Provider Code on PC or Phone':'Szolgáltató kódjának megadása számitógépen vagy telefonon',
    'Manual setup':'Kézi Beállitás',
    'Access settings':'Hozzáférési beállitás',
// 26.1
    'Script':'Forgatókönyv',
    'Producer':'Producer',
    'Operator':'Operatőr',
    'Composer':'Zeneszerző',
    'Artist':'Művész',
    'Installation':'Vágó',
    'Budget':'Költségvetés',
    'Audience':'Közönség',
    'Premiere world':'Világ premier',
    'Display settings':'Megjelenitési beállitások',
    'Age':'Kor',
    'Sort':'Rendezés',
    'by name':'Név szerint',
    'by adding':'Hozzáadás szerint',
    'Order':'Rend',
    'asc':'felnövekvő',
    'desc':'lenövekvő',
    'Language':'Nyelv',
    'Quality':'Minóség',
    'Show program name':'Adás nevének megjelenitése',
    'Show description':'Leírás megjelenitése',
    'transparent':'átlátszó',
}
