keyStrings = {
    'lang':'Latviešu',
    'alhabet':'aābcčdeēfgģhiījkķlļmnņoprsštuūvzž',
    'Channel list. Category: ':'Kanālu saraksts. Kategorija: ',
    'EPG':'Programma',
    'Category':'Kategorijas',
    'Actions':'Darbības',
    'Description':'Apraksts',
    'Open in PiP':'Atvērt PiP',
    'Move channel up':'Pārvietot kanālu uz augšu',
    'Move channel down':'Pārvietot kanālu uz leju',
    'Delete channel':'Dzēst kanālu',
    'Add channel to category':'Pievienot kanālu kategorijai',
    'Add channel to favorites':'Pievienot kanālu favorītiem',
    'Channel parental control':'Kanāla vecāku kontrole',
    'Channel is not available!!!':'Kanāls nav pieejams!!!',
    'min':'min',
    'Channel ':'Kanāls ',
    ' added to category ':' pievienots kategorijai ',
    ' added to favorites':' pievienots favorītiem',
    'Favorites':'Favorīti',
    'Select category to add channel':'Izvēlies kategoriju kurā pievienot kanālu',
    'Enter parental code':'Ievadiet vecāku kontroles kodu',
    'Wrong parental code !!!':'Nepareizss vecāku kontroles kods !!!',
    '<br>Up<br>':'<br>Uz augšu<br>',
    '<br>Delete':'<br>Izdzēst',
    '<br>Add<br>to favorites':'<br>Pievienot<br>favorītiem',
    '<br>Add<br>to category':'<br>Pievienot<br>kategorijai',
    '<br>Parental<br>Control':'<br>Vecāku<br>kontrole',
    '<br>Down':'<br>Uz leju',
    'Close':'Aizvērt',
    'Edit category name':'Mainīt kategorijas nosaukumu',
    'Category %1 already exists!':'Kategorija %1 jau eksistē!',
    'Enter name for new category':'Ievadiet jaunās kategorijas nosaukumu',
    '<br>More...<br>':'<br>Vēl...<br>',
    '<br>Rename':'<br>Pārdēvēt',
    '<br>Copy<br>category':'<br>Kopēt<br>kategoriju',
    '<br>Back<br>':'<br>Atpakaļ<br>',
    '<br>Create<br>category':'<br>Izveidot<br>kategoriju',
    'Category selection':'Kategorijas izvēle',
    'Menu':'Izvēlne',
    'Channel list':'Kanālu saraksts',
    'Move category up':'Pārvietot kategoriju uz augšu',
    'Move category down':'Pārvietot kategiriju uz leju',
    'Create category':'Izveidot kategoriju',
    'Rename category':'Pārdēvēt kategoriju',
    'Copy category':'Kopēt kategoriju',
    'Delete category':'Izdzēst kategoriju',
    'Su Mo Tu We Th Fr Sa':'Sv Pr Ot Tr Ce Pk Se',
    'EPG and archive. Channel: ':'Programma un arhīvs. Kanāls: ',
    'By alphabet':'Alfabētiski',
    'Archive. Channel: ':'Arhīvs. Kanāls: ',
    'By time':'Pēc laika',
    'Player info:':'Informācija par atskaņotāju:',
    'Device info:':'Informācija par ierīci:',
    '- switch:':'- pārslēgšana:',
    '- erase':'- notīrīt',
    '- move cursor':'- kursora pārvietošana',
    '- return without save':'- atgriezties nesaglabājot',
    '- save':'- saglabāt',
    'Return to previous channel':'Atgriezties pie iepriekšējā kanāla',
    'Call PiP / PiP exchange':'Izsaukt PiP / Samainīt vietām PiP',
    'Info about TV program':'Parādīt informāciju par TV programmu',
    'Show player menu':'Parādīt atskaņotāja izvēlni',
    'Interface settings':'Interfeisa iestatījumi',
    'Show channel selection list':'Parādīt kanāla izvēles sarakstu',
    'Hide / Return':'Paslēpt / Atgriezties',
    'Exit player':'Iziet no atskaņotāja',
    'Show EPG and archive for channel':'Programma un kanāla arhīva ieraksti',
    'Channel category selection':'Kanāla kategorijas izvēle',
    'Toggle Aspect Ratio':'Pārslēgt malu attiecību',
    'Toggle Zoom Mode':'Pārslēgt palielināšanas režīmu',
    'Switch sound track':'Pārslēgt skaņas celiņu',
    'In live mode: <br/>':'Tiešraides režīmā:<br/>',
    'Channel selection by number':'Kanāla izvēle pēc numura',
    'Timeshift: to start of TV program':'Laika nobīde: uz raidījuma sākumu',
    'Timeshift: one minute back':'Laika nobīde: minūti atpakaļ',
    '<br/><br/>In archive mode:<br/>':'<br/><br/>Arhīva skata režīmā:<br/>',
    'Pause/Play':'Pauze/Atskaņošana',
    'Stop playback and return to In live mode':'Pārtraukt atskaņošanu un atgriezties tiešraides režīmā',
    'To start of TV program / Previous TV program':'Raidījuma sākumā / Uz iepriekšējo raidījumu',
    'Next TV program':'Uz nākamo raidījumu',
    'Back / Forward for 1 minute':'Atpakaļ / Uz priekšu par 1 minūti',
    'Back / Forward for 15 seconds':'Atpakaļ / Uz priekšu par 15 sekundēm',
    'Back / Forward for 3 minutes':'Atpakaļ / Uz priekšu par 3 minūtēm',
    'Back / Forward for 10 minutes':'Atpakaļ / Uz priekšu par 10 minūtēm',
    'Show rewind window':'Rādīt pārtīšanas logu',
    'Description of remote control buttons':'TV tālvadības pults apraksts',
    'Description of remote control buttons depending on the view mode':'TV tālvadības pults apraksts, atkarībā no skatīšanās režīma',
    'Set parental code':'Iestatīt vecāku kontroles kodu',
    'Repeat parental code':'Atkārtojiet vecāku kontroles kodu',
    'Show list of channel archive records':'Kanāla arhīva ieraksti',
    'Show list of channel archive records without duplication':'Parādīt kanāla arhīva ierakstus bez atkārtojumiem',
    'Show Media Library':'Multivides Bibliotēka',
    'Rewind':'Pārtīt',
    'Close PiP':'Aizvērt PiP',
    'Parental control':'Vecāku kontrole',
    'Change provider':'Provaidera maiņa',
    'Change provider - you can change the provider, and it will be remembered at the next start of player!':'Provaidera maiņa - Jūs varat nomainīt Provaideri, tas tiks saglabāts nākamreiz atverot programmu!',
    'Restart player':'Restartēt atskaņotāju',
    // 'Restart player - after changing provider settings (as example)':'Restartēt atskaņotāju - piemēram pēc Provaidera maiņas',
    'Description of remote control buttons':'Tālvadības pults pogu apraksts',
    'About':'Informācija',
    'Player and device info':'Ierīces un Atskaņotāja informācija',
    'Donate <div class="btn" style="background-color:orange;">donate</div>':'Projekta atbalsts <div class="btn" style="background-color:orange;">donate</div>',
    'Voluntary donation for the development of project':'Brīvprātīga palīdzība projekta attīstībai',
    'Settings saved':'Iestatījumi saglabāti',
    'no':'nē',
    'yes':'jā',
    'Records':'Ieraksti',
    'Previous':'Iepriekšējais',
    'Info':'Info',
    'Not reduce video when showing the list (bugfix)':'Nesamazināt video parādot sarakstu (bugfix)',
    'Black screen while switching the channel':'Melns ekrāns pārslēdzot kanālus',
    'PiP window size':'PiP loga izmērs',
    'small':'mazss',
    'medium':'vidējs',
    'large':'liels',
    'PiP window position':'PiP loga atrašanās viena',
    'top-right':'pa labi augšā',
    'bottom-right':'pa labi apakšā',
    'left-bottom':'pa kreisi apakšā',
    'top-left':'pa kreisi augšā',
    'Number of rows in lists':'Rindu skaits sarakstos',
    'Distance between lines in lists':'Attālums starp rindām sarakstos',
    'Font type':'Fonta veids',
    'volume':'skaļums',
    'paging':'šķiršana',
    'Nothing':'Nekā',
    'Exit':'Izeja',
    'Joystick':'Konsole',
    'Button %1 function when viewing':'pogas funkcija %1 skatoties',
    'Button function %1 when viewing archive':'pogas funkcija %1 skatoties arhīvu',
    'Channels':'Kanāli',
    'Remote (color buttons N/A)':'Pults bez krāsainajām pogām',
    'Remote (number buttons N/A)':'Pults bez ciparu pogām',
    'Timezone':'Laika josla',
    'Sleep timer':'Miega taimeris',
    'off':'izslēgts',
    '30 minutes':'30 minūtes',
    '1 hour':'1 stunda',
    '2 hours':'2 stundas',
    'Infobar display timeout, s':'Infobāra taimauts, sek',
    '"Sliding" infobar':'Slīdošs infobārs',
    'Interface transparency':'Interfeisa caurspīdīgums',
    'Volume step, %':'Skaņas solis, %',
    'List location':'Saraksta atrašanās vieta',
    'right':'pa labi',
    'left':'pa kreisi',
    'Color spectrum':'Krāsu gamma',
    'select':'izvēlies',
    'Permanent clock on screen':'Patstāvīgs pulkstens uz ekrāna',
    'Show channel number in list':'Parādīt kanāla numuru sarakstā',
    'Show picons in channel list':'Parādīt ikonas kanālu sarakstā',
    'Show channel name in list':'Parādīt kanāla nosaukumu sarakstā',
    'Show progress in channel list':'Parādīt progresu kanālu sarakstā',
    'Show archive availability in list':'Parādīt arhīva pieejamību kanālu sarakstā',
    'Show scrollbar in list':'Parādīt scrollbar kanālu sarakstā',
    'Preview in channel list':'Priekšskatīt kanālu sarakstā',
    'always':'vienmēr',
    'on ':'pēc ',
    'Number of next TV programs in channel list':'Nākamo raidījumu skaits kanālu sarakstā',
    'Channel list editing style':'Kanālu saraksta rediģēšanas stils',
    'All categories':'Visas kategorijas',
    '"Favorites"':'"Favorīti"',
    'Editor':'Redaktors',
    'built-in':'iebūvētais',
    'native':'dzimtais',
    'HDMI-CEC support (on/off from TV)':'HDMI-СEC atbalsts (iesl/izsl no TV)',
    'Type of player for streaming':'Straumēšanas atskaņotāja veids',
    'Autostart of player':'Atskaņotāja automātiska palaišana',
    'Buffer Size, s':'Bufera izmērs, sek',
    'Choose from':'Izvēlies no',
    'Settings':'Iestatījumi',
    'Change value':'Vērtības maiņa',
    'Save Settings':'Saglabāt iestatījumus',
    'To begining':'Uz sākumu',
    'Live':'Tiešraide',
    ' m ':' min ',
    ' s':' sek',
    '1 minute':'1 minūte',
    '10 Seconds':'10 sekundes',
    'Go to':'Iet uz',
    'Archive - begin':'Arhīvs - raidījuma sākums',
    'Pause':'Pauze',
    'Play':'Atskaņošana',
    'Shutdown after %1 seconds<br/><br/>Cancel - any action':'Izslēgšanās pēc %1 sekundēm<br/><br/>Atcelt - jebkura poga',
    'Do you want to exit player?':'Vai vēlies iziet?',
    'Color':'Krāsa',
    'Saturation':'Piesātinājums',
    'Yellow':'Dzeltens',
    'Green':'Zaļš',
    'Blue':'Zils',
    'Set':'Uzstādīt',
    'Restart stream':'Restartēt plūsmu',
    'Favorites':'Favorīti',
    'All':'Visi',
    '<br/>Processing the channel list...':'<br/>Kanālu saraksta apstrāde...',
    '<br/>Start playback...':'<br/>Sākt atskaņošanu...',
    '<br/>Channel list not received !!!':'<br/>Kanālu saraksts nav saņemts!!!',
    'Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>':'Kanālu saraksts nav saņemts!!!<br/><br/>Ievadiet Provaidera datus un restartējiet atskaņotāju!!!<br/><br/>',
    'Error getting channel list !!!':'Kanālu saraksta saņemšanas kļūda!!!',
    'system':'sistēmas',
    'Choose provider':'Izvēlies Provaideri',
    '<br>Rewind<br>':'<br>Pārtīt<br>',
    '<br>Menu':'<br>Izvēlne',
    '<br>Pause<br>':'<br>Pauze<br>',
    '<br>Toggle<br>sound track':'<br>Pārslēgt<br>skaņas celiņu',
    '<br>Live':'<br>Tiešraide',
    '<br>Previous<br>channel':'<br>Iepriekšējais<br>kanāls',
    '<br/><b>Failed to load provider script !!!</b>':'<br/><b>Neizdevās ielādēt Provaidera skriptu!!!</b>',
    '<br/>Loading provider %1 script ...':'<br/>Provaidera skripta ielāde %1 ...',
    '<br/>Loading settings...':'<br/>Iestatījumu ielāde...',
    '<br/>Loading channel list...':'<br/>Kanālu saraksta ielāde...',
    'Choose language':'Izvēlies valodu',
    'Change interface language':'Interfeisa valodas maiņa',
    'Aspect':'Aspekts',
    'Audio':'Audio',
    'Stalker portals':'Stalker portāli',
    'm3u-m3u8 playlists':'m3u-m3u8 playlists',
    '<br/>Loading STB...':'<br/>Ielādē STB...',
    '<br/>Setup STB...':'<br/>STB iestatījumi...',
    'Save settings to storage':'Saglabāt iestatījumus krātuvē',
    'Load settings from storage':'Atjaunot iestatījumus no krātuves',
    'Download':'Lejupielādēt',
    'Skip this version':'Izlaist šo versiju',
    'Volume control':'Skaļuma regulēšana',
    'Long button presses':'Ilgstošas pogas nospiešanas',
    'Download new version Android App':'Lejupielādēt jauno versiju',
    'To access you must enter url, username and password!':'Lai piekļūtu ir jāievada adrese, login un parole!',
    'Failed to load channel list!':'Neizdevās ielādēt kanālu sarakstu!',
    'Year':'Gads',
    'Duration':'Ilgums',
    'Genre':'Žanrs',
    'Country':'Valsts',
    'Director':'Režisors',
    'Actors':'Lomās',
    'Release date':'Izdota',
    'Rating':'Reitings',
    'Season':'Sezona',
    'Episodes':'Epizodes',
    'VOD':'Filmas un Video',
    'TV series':'Seriāli',
    'Episode':'Epizode',
    'Download! Wait ...':'Lādējam! Uzgaidiet ...',
    'Server':'Serveris',
    'URL':'Adrese',
    'Username':'Login',
    'Password':'Parole',
    'Stream type':'Plūsmas veids',
    'Account info':'Konta informācija',
    'Select server number from 1 to 6 to save data':'Izvēlies servera numuru no 1 līdz 6 datu saglabāšanai',
    ' (after changing, restart player)':' (pēc izmaiņām restartējiet atskaņotāju)',
    ' (after changing, switch the channel!)':' (pēc izmaiņām pārslēdziet kanālu!)',
    'Enter URL of server':'Ievadiet servera adresi',
    'Enter username':'Ievadiet lietotājvārdu',
    'Enter password':'Ievadiet paroli',
    'Select stream type':'Izvēlies plūsmas veidu',
    '??? No channel name':'??? Nav kanāla nosaukuma',
    'Playlist URL':'Atskaņošanas saraksta adrese',
    'Archive hours':'Arhīva stundu skaits',
    'Enter playlist URL':'Ievadiet atskaņošanas saraksta adresi',
    'Enter playlist archive hours':'Ievadiet atskaņošanas saraksta arhīva stundu skaitu',
    'show on-screen keyboard':'parādīt uznirstošo klaviatūru',
    'Sleep without leaving player':'Aizmigt neizejot no atskaņotāja',
    'PiP is not available!':'PiP nav pieejams!',
    'NORMAL':'PARASTS',
    'ENLARGE':'PALIELINĀT',
    'MAKE_WIDER':'PADARĪT PLATĀKU',
    'NON_LINEAR_STRETCH':'NELINEĀRĀ IZSTIEPŠANA',
    'NON_LINEAR_STRETCH_TO_FULL_SCREEN':'NELINEĀRĀ IZSTIEPŠANA PA VISU EKRĀNU',
    'MAKE_TALLER':'PADARĪT AUGSTĀKU',
    'CUT_EDGES':'MALU APGRIEŠANA',
    'FULL_SCREEN':'PILNEKRĀNS',
    'STRETCH_TO_FULL_SCREEN':'IZSTIEPŠANA PA VISU EKRĀNU',
    'Background color':'Fona krāsa',
    'Brightness':'Spilgtums',
    '3 hours':'3 stundas',
    'Restart stream / Live':'Plūsmas restarts / Tiešraide',
    '- keyboard': '- klaviatūra',
    'Media':'Multivide',
    'String for search':'Meklēšanas rinda',
    'Playlist Name':'Atskaņošanas saraksta nosaukums',
    'Enter playlist Name':'Ievadiet atskaņošanas saraksta nosaukumu',
    'Media Library URL':'Multivides Bibliotēkas adrese',
    'Enter Media Library URL':'Ievadiet Multivides Bibliotēkas adresi',
    'Playlist':'Atskaņošanas saraksts',
    'Select playlist':'Izvēlies atskaņošanas sarakstu',
    'Edit':'Rediģēt',
    'Load':'Ielādēt',
    'Edit playlist data':'Atskaņošanas saraksta rediģēšana',
    'Select portal':'Izvēlies portālu',
    'Portal Name':'Portāla nosaukums',
    'Enter Portal Name':'Ievadiet Portāla nosaukumu',
    'Edit portal data':'Portāla datu rediģēšana',
    'without':'bez',
    'Settings STB':'Ierīces iestatījumi',
    'Soft audio render':'Atkodēt audio programmatiski',
    'Long press horizontal arrows for volume control':'Skaļuma regulēšana ilgstoši nospiežot horizontālās pogas',
    'Yes':'Jā',
    'Back':'Atpakaļ',
    'Show providers?':'Parādīt Provaiderus?',
    'Hide providers?':'Slēpt Provaiderus?',
    'Show provider settings?':'Parādīt Provaidera iestatījumus?',
    'Hide provider settings?':'Slēpt Provaidera iestatījumus?',
    'Clear all settings?':'Dzēst visus iestatījumus?',
    'Timer':'Taimeris',
    'Set timer?':'Uzstādīt taimeri?',
    'Remove timer?':'Dzēst taimeri?',
    'Timer: switch to channel?':'Taimeris: pārslēgties uz kanālu?',
    ' (if archive exists)':' (ja pastāv arhīvs)',
    'Preffered audio track':'Vēlamais audio celiņš',
    'Information':'Informācija',
    'Lists settings':'Sarakstu uzstādījumi',
    'Channel list settings':'Kanālu sarakstu uzstādījumi',
    'Buttons settings':'Tālvadības pults pogu uzstādījumi',
    'Subtitle':'Subtitri',
    'Switch subtitle':'Pārslēgt subtitrus',
    'Off':'Izslēgt',
    'Not found':'Nav',
    'History of watched movies':'Skatījumu vēsture',
    'Continue watching?':'Turpināt skatīties?',
    'Add to favorites':'Pievienot favorītiem',
    'Delete':'Dzēst',
    'Info about current stream':'Info par pašreizējo plūsmu',
    'Stop':'Stop',
    'Playlist file':'Atskaņošanas saraksta fails',
    'Select playlist file':'Izvēlies atskaņošanas saraksta failu',
    'Graphical indication':'Grafiskā indikācija',
    'Background color of selected item':'Atlasītā vienuma fona krāsa',
    'Default':'Noklusējums',
    'Not supported!':'Netiek atbalstīts!',
    'Menu items settings':'Izvēlnes iestatīšana',
    'Select menu items':'Izvēlies izvēlnes punktus',
    'Protect Adult Channels':'Aizsargāt "Pieaugušo" kanālus',
    'Protect Settings':'Iestatījumu aizsardzība',
    'Protect Change Provider':'Provaidera maiņas aizsardzība',
    'Infobar settings':'Infobāra iestatījumi',
    'Show when switching':'Parādīt pārslēdzot',
    'Show when changing program':'Parādīt pārslēdzot programmu',
    'Show when rewind':'Parādīt pārtinot',
    'Archive. Category: ':'Arhīvs. Kategorija: ',
    'Sort channels':'Kārtot kanālus',
    '"As Is"':'"Kā ir"',
    'Load playlist':'Ielādēt atskaņošanas sarakstu',
    ' (after changing, load playlist)':' (pēc izmaiņām, ielādēt atskaņošanas sarakstu)',
    'Statistics of current stream':'Pašreizējās plūsmas statistika',
    'Search':'Meklēšana',
// 14.6
    'Behavior of %1/%2 buttons in lists':'Uzvedība pogām %1/%2 sarakstos',
    'begin/end':'sākums/beigas',
    'Position shift -10 seconds after pause':'Nobīde par -10 sekundēm pēc pauzes',
    'Remember previous channels':'Atcerēties iepriekšējos kanālus',
    'History in Media Library':'Multivides Bibliotēkas vēsture',
// 5.11
    'Manage settings':'Iestatījumu pārvaldība',
    'Save settings':'Saglabāt iestatījumus',
    'Load settings':'Ielādēt iestatījumus',
    'Clear settings':'Notīrīt iestatījumus',
    'Send settings':'Nosūtīt iestatījumus uz serveri',
    'Settings sended!':'Iestatījumi nosūtīti uz serveri!',
    'For download settings file open':'Iestatījumu faila lejupielādei atveriet',
    'and enter code':'un ievadiet kodu',
    'or scan':'vai noskenējiet',
    'Send request':'Pieprasījuma nosūtīšana uz serveri',
    'Request sended!':'Pieprasījums nosūtīts uz serveri!',
    'For upload settings file open':'Iestatījumu faila augšupielādei atveriet',
    'Enter Provider Code':'Ievadiet Provaidera Kodu',
    'Error Code!':'Koda Kļūda!!!',
    'For enter value open':'Datu ievadīšanai atveriet',
    'First Run Setup':'Pirmreizējā iestatīšana',
    'Enter Provider Code on PC or Phone':'Ievadiet Provaidera Kodu Datorā vai Telefonā',
    'Manual setup':'Manuālā uzstādīšana',
    'Access settings':'Pieejas uzstādīšana',
// 26.1
    'Script':'Scenārijs',
    'Producer':'Producents',
    'Operator':'Operātors',
    'Composer':'Komponists',
    'Artist':'Mākslinieks',
    'Installation':'Montāža',
    'Budget':'Budžets',
    'Audience':'Auditorija',
    'Premiere world':'Pasaules pirmizrāde',
    'Display settings':'Displeja iestatījumi',
    'Age':'Vecums',
    'Sort':'Šķirošana',
    'by name':'pēc nosaukuma',
    'by adding':'pēc pievienošanas',
    'Order':'Sakārtot',
    'asc':'palielināšana',
    'desc':'samazināšana',
    'Language':'Valoda',
    'Quality':'Kvalitāte',
    'Show program name':'Parādīt raidījuma nosaukumu',
    'Show description':'Parādīt raidījuma aprakstu',
    'transparent':'caurspīdīgi',
}
