keyStrings = {
    'lang':'Lietuvių',
    'alhabet':'aąbcčdeęėfghiįyjklmnoprsštuųūvzž',
    'Channel list. Category: ':'Kanalų sąrašas. Grupė: ',
    'EPG':'TV gidas',
    'Category':'Grupė',
    'Actions':'Veiksmai',
    'Description':'Aprašymas',
    'Open in PiP':'Atidaryti vaizdą vaizde (PiP)',
    'Move channel up':'Perkelti kanalą į viršų',
    'Move channel down':'Perkelti kanalą į apačią',
    'Delete channel':'Ištrinti kanalą',
    'Add channel to category':'Pridėti kanalą į grupę',
    'Add channel to favorites':'Pridėti kanalą prie mėgstamiausių',
    'Channel parental control':'Kanalo tėvų kontrolė',
    'Channel is not available!!!':'Kanalo nėra!!!',
    'min':'minučių',
    'Channel ':'Kanalas ',
    ' added to category ':' pridėtas į grupę',
    ' added to favorites':' pridėtas prie mėgstamiausių',
    'Favorites':'Mėgstamiausi',
    'Select category to add channel':'Pasirinkite grupę norėdami pridėti šį kanalą',
    'Enter parental code':'Įrašykite tėvų kontrolės kodą',
    'Wrong parental code !!!':'Neteisingas tėvų kontrolės kodas !!!',
    '<br>Up<br>':'<br>Į viršų<br>',
    '<br>Delete':'<br>Ištrinti',
    '<br>Add<br>to favorites':'<br>Pridėti<br>į mėgstamiausių sąrašą',
    '<br>Add<br>to category':'<br>Pridėti<br>į grupę',
    '<br>Parental Control':'<br>Tėvų kontrolė',
    '<br>Down':'<br>Į Apačia',
    'Close':'Uždaryti',
    'Edit category name':'Pervadinti grupės pavadinimą',
    'Category %1 already exists!':'Grupė %1 jau egzistuoja!',
    'Enter name for new category':'Įrašykite naujos grupės pavadinimą',
    '<br>More...<br>':'<br>Daugiau<br>',
    '<br>Rename':'<br>Pervadinti',
    '<br>Copy category':'<br>Kopijuoti grupę',
    '<br>Back<br>':'<br>Atgal<br>',
    '<br>Create category':'<br>Sukurti grupę',
    'Category selection':'Grupių pasirinkimas',
    'Menu':'Meniu',
    'Channel list':'Kanalų sąrašas',
    'Move category up':'Perkelti grupę į viršų',
    'Move category down':'Perkelti grupę į apačią',
    'Create category':'Sukurti grupę',
    'Rename category':'Pervadinti grupę',
    'Copy category':'Kopijuoti grupę',
    'Delete category':'Ištrinti grupę',
    'Su Mo Tu We Th Fr Sa':'Sk Pr An Tr Kt Pn Št',
    'EPG and archive. Channel: ':'EPG ir archyvas. Kanalas: ',
    'By alphabet':'Pagal Abėcėlę',
    'Archive. Channel: ':'Archyvas. Kanalas: ',
    'By time':'Pagal laiką',
    'Player info:':'Informacija apie grotuvą:',
    'Device info:':'Informacija apie įrenginį',
    '- switch:':'- perjungimas:',
    '- erase':'- ištrinti',
    '- move cursor':'- perkelti žymeklį',
    '- return without save':'- grįžti be išsaugojimo',
    '- save':'- įrašyti',
    'Return to previous channel':'Grįžti į ankstesnį kanalą',
    'Call PiP / PiP exchange':'Rodyti PiP / Pakeisti PiP kanalą',
    'Info about TV program':'Informacija apie TV programą',
    'Show player menu':'Rodyti grotuvo meniu',
    'Interface settings':'Sąsajos nustatymai',
    'Show channel selection list':'Rodyti kanalų pasirinkimo sąrašą',
    'Hide / Return':'Slėpti informaciją / grįžti',
    'Exit player':'Užverti grotuvą',
    'Show EPG and archive for channel':'Rodyti kanalo TV gidą ir archyvą',
    'Channel category selection':'Pasirinkti kanalų grupę',
    'Toggle Aspect Ratio':'Perjungti vaizdo santykį',
    'Toggle Zoom Mode':'Perjungti mastelio keitimo režimą',
    'Switch sound track':'Perjungti garso takelį',
    'In live mode: <br/>':'Tiesioginėje transliacijoje:<br/>',
    'Channel selection by number':'Kanalo pasirinkimas pagal numerį',
    'Timeshift: to start of TV program':'Archyvas: į programos pradžią',
    'Timeshift: one minute back':'Archyvas: atsukti vieną minutę atgal',
    '<br/><br/>In archive mode:<br/>':'<br/><br/>Archyvo režimas:<br/>',
    'Pause/Play':'Pristabdyti/tęsti žiūrėjimą',
    'Stop playback and return to In live mode':'Išjungti archyvą ir grįžti prie tiesioginės transliacijos',
    'To start of TV program / Previous TV program':'Į TV programos pradžią / Į ankstesnę TV programą',
    'Next TV program':'Į sekančią TV programą',
    'Back / Forward for 1 minute':'Persukimas: 1 minutę atgal / pirmyn',
    'Back / Forward for 15 seconds':'Persukimas: 15 sekundžių atgal / pirmyn',
    'Back / Forward for 3 minutes':'Persukimas: 3 minutes atgal / pirmyn',
    'Back / Forward for 10 minutes':'Persukimas: 10 minučių  atgal / pirmyn',
    'Show rewind window':'Įjungti atsukimo langelį',
    'Description of remote control buttons':'Nuotolinio valdymo mygtukų aprašymas',
    'Description of remote control buttons depending on the view mode':'Nuotolinio valdymo mygtukų aprašymas atsižvelgiant į peržiūros režimą',
    'Set parental code':'Įrašykite tėvų kontrolės kodą',
    'Repeat parental code':'Pakartokite tėvų kontrolės kodą',
    'Show list of channel archive records':'Rodyti šio kanalo archyvo sąrašą',
    'Show list of channel archive records without duplication':'Rodyti šio kanalo archyvo sąrašą nedubliuojant',
    'Show Media Library':'Rodyti medijos biblioteką',
    'Show Media Library (if available from provider)':'Rodyti medijos biblioteką (jei galima iš teikėjo)',
    'Rewind':'Transliacijos valdymas',
    'Close PiP':'Uždaryti PiP',
    'Parental control':'Tėvų kontrolė',
    'Change provider':'Pakeisti teikėją',
    'Change provider - you can change the provider, and it will be remembered at the next start of player!':'Pakeisti teikėją - jūs galite pakeisti teikėją - grotuvas įsimins jį kito paleidimo metu!',
    'Restart player':'Paleiskite grotuvą iš naujo',
    'Restart player - after changing provider settings (as example)':'Paleisti iš naujo grotuvą - pakeitus teikėjo nustatymus',
    'Description of remote control buttons':'Nuotolinio valdymo mygtukų aprašymas',
    'About':'Apie',
    'Player and device info':'Informacija apie grotuvą ir įrenginį',
    'Donate <div class="btn" style="background-color:orange;">donate</div>':'Pagalba projektui <div class="btn" style="background-color:orange;">paremti</div>',
    'Voluntary donation for the development of project':'Savanoriškos aukos projekto plėtrai.',
    'Settings saved':'Nustatymai išsaugoti',
    'no':'ne',
    'yes':'taip',
    'Records':'Įrašai',
    'Previous':'Ankstesnis',
    'Info':'Informacija',
    'Not reduce video when showing the list (bugfix)':'Nesumažinti vaizdo, kai rodomas sąrašas (ištaisyta)',
    'Black screen while switching the channel':'Juodas ekranas perjungiant kanalą',
    'PiP window size':'PiP langelio dydis',
    'small':'mažas',
    'medium':'vidutinis',
    'large':'didelis',
    'PiP window position':'PiP langelio padėtis',
    'top-right':'viršuje dešinėje',
    'bottom-right':'apačioje dešinėje',
    'left-bottom':'kairėje apačioje',
    'top-left':'viršuje kairėje',
    'Number of rows in lists':'Eilučių skaičius sąraše',
    'Distance between lines in lists':'Atstumas tarp eilučių sąraše',
    'Font type':'Šrifto tipas',
    'volume':'garsumas',
    'paging':'puslapių kaita',
    'Nothing':'Jokios funkcijos',
    'Exit':'Išėjimas',
    'Joystick':'Vairalazdė',
    'Button %1 function when viewing':'Mygtuko %1 funkcija peržiūros metu',
    'Button function %1 when viewing archive':'Mygtuko funkcija %1 žiūrint archyvą',
    'Channels':'Kanalai',
    'Remote (color buttons N/A)':'Nuotolinio valdymo pultas (be spalvotų mygtukų)',
    'Remote (number buttons N/A)':'Nuotolinio valdymo pultas (be skaičių mygtukų)',
    'Timezone':'Laiko juosta',
    'Sleep timer':'Miego laikmatis',
    'off':'išjungtas',
    '30 minutes':'30 minučių',
    '1 hour':'1 valanda',
    '2 hours':'2 valandos',
    'Infobar display timeout, s':'Informacijos juostos rodymo laikas sek.',
    '"Sliding" infobar':'"Slenkanti" informacijos juosta',
    'Interface transparency':'Sąsajos skaidrumas',
    'Volume step, %':'Garso didinimo arba mažinimo žingsnis, %',
    'List location':'Sąrašo vieta',
    'right':'dešinėje',
    'left':'kairėje',
    'Color spectrum':'Spalvų spektras',
    'select':'pasirinkite',
    'Permanent clock on screen':'Nuolatinis laikrodis ekrane',
    'Show channel number in list':'Rodyti kanalo numerį sąraše',
    'Show picons in channel list':'Rodyti logotipus kanalų sąraše',
    'Show channel name in list':'Rodyti kanalo pavadinimą sąraše',
    'Show progress in channel list':'Rodyti eigą kanalų sąraše',
    'Show archive availability in list':'Rodyti archyvų prieinamumą sąraše',
    'Show scrollbar in list':'Rodyti slinkties juostą sąraše',
    'Preview in channel list':'Peržiūra kanalų sąraše',
    'always':'visada',
    'on ':'paspaudus',
    'Number of next TV programs in channel list':'Kitų TV programų skaičius kanalų sąraše',
    'Channel list editing style':'Kanalų sąrašo redagavimo stilius',
    'All categories':'Visos grupės',
    '"Favorites"':'"Mėgstamiausi"',
    'Editor':'Redaktorius',
    'built-in':'įdiegtas',
    'native':'vietinis (gimtasis)',
    'HDMI-CEC support (on/off from TV)':'HDMI-СEC palaikimas (įjungti/išjungti TV su priedėlio pultu)',
    'Type of player for streaming':'Transliacijos grotuvo tipas',
    'Autostart of player':'Automatinis grotuvo paleidimas',
    'Buffer Size, s':'Buferio dydis, sekundėmis',
    'Choose from':'Rinktis iš',
    'Settings':'Nustatymai',
    'Change value':'Pakeisti reikšmę',
    'Save Settings':'Išsaugoti nustatymus',
    'To begining':'Į laidos pradžią',
    'Live':'Tiesioginė transliacija',
    ' m ':' min ',
    ' s':' sek',
    '1 minute':'1 minutė',
    '10 Seconds':'10 sekundžių',
    'Go to':'Eiti į',
    'Archive - begin':'Archyvas - programos pradžia',
    'Pause':'Pauzė',
    'Play':'Atkūrimas',
    'Shutdown after %1 seconds<br/><br/>Cancel - any action':'Automatinis išjungimas po %1 sekundžių <br/><br/>Norėdami atšaukti - spauskite bet kurį mygtuką',
    'Do you want to exit player?':'Ar tikrai norite išeiti iš grotuvo?',
    'Color':'Spalva',
    'Saturation':'Prisotinimas',
    'Yellow':'Geltonas',
    'Green':'Žalias',
    'Blue':'Mėlynas',
    'Set':'Nustatyti',
    'Restart stream':'Paleiskite srautą iš naujo',
    'Favorites':'Mėgstamiausi',
    'All':'Visi kanalai',
    '<br/>Processing the channel list...':'<br/>Kanalų sąrašo paleidimas ...',
    '<br/>Start playback...':'<br/>Paleidimas...',
    '<br/>Channel list not received !!!':'<br/>Kanalų sąrašas negautas!!!',
    'Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>':'Kanalų sąrašas negautas!!!<br/><br/>Įrašykite teikėjo duomenis ir paleiskite grotuvą iš naujo!!!<br/><br/>',
    'Error getting channel list !!!':'Klaida gaunant kanalų sąrašą!!!',
    'system':'sisteminis',
    'Choose provider':'Pasirinkite teikėją',
    '<br>Rewind<br>':'<br>Persukti<br>',
    '<br>Menu':'<br>Meniu',
    '<br>Pause<br>':'<br>Pauzė<br>',
    '<br>Toggle sound track':'<br>Garso takelio pakeitimas',
    '<br>Live':'<br>Tiesioginė transliacija',
    '<br>Previous channel':'<br>Ankstesnis kanalas',
    '<br/><b>Failed to load provider script !!!</b>':'<br/><b>Nepavyko gauti teikėjo nustatymų!!!</b>',
    '<br/>Loading provider %1 script ...':'<br/>Įkeliamas teikėjo scenarijus %1 ...',
    '<br/>Loading settings...':'<br/>Gaunami nustatymai...',
    '<br/>Loading channel list...':'<br/>Įkeliamas kanalų sąrašas...',
    'Choose language':'Pasirinkite kalbą',
    'Change interface language':'Keisti sąsajos kalbą',
    'Aspect':'Santykis',
    'Audio':'Garso takelis',
    'Stalker portals':'Stalker portalai',
    'm3u-m3u8 playlists':'m3u-m3u8 grojaraštis',
    '<br/>Loading STB...':'<br/>STB Paleidimas...',
    '<br/>Setup STB...':'<br/>STB Nustatymas...',
    'Save settings to storage':'Išsaugokite nustatymus saugykloje',
    'Load settings from storage':'Įkelkite nustatymus iš saugyklos',
    'Download':'Atsiųsti',
    'Skip this version':'Praleisti šią versiją',
    'Volume control':'Garso valdymas',
    'Long button presses':'Ilgas mygtuko paspaudimas',
    'Download new version Android App':'Atsisiųskite naują Android programos versiją',
    'To access you must enter url, username and password!':'Norėdami prisijungti, turite įvesti URL, vartotojo vardą ir slaptažodį!',
    'Failed to load channel list!':'Nepavyko įkelti kanalų sąrašo!',
    'Year':'Metai',
    'Duration':'Trukmė',
    'Genre':'Žanras',
    'Country':'Šalis',
    'Director':'Režisierius',
    'Actors':'Aktoriai',
    'Release date':'Išleidimo data',
    'Rating':'Reitingas',
    'Season':'Sezonas',
    'Episodes':'Serijų kiekis',
    'VOD':'Mediateka (VOD)',
    'TV series':'Serialai',
    'Episode':'Serija',
    'Download! Wait ...':'Atsisiunčiama! laukite ...',
    'Server':'Serveris',
    'URL':'Adresas (URL)',
    'Username':'Prisijungimo vardas',
    'Password':'Slaptažodis',
    'Stream type':'Srautų tipas',
    'Account info':'Teikėjo informacija',
    'Select server number from 1 to 6 to save data':'Pasirinkite serverio numerį nuo 1 iki 6 norėdami išsaugoti duomenys',
    ' (after changing, restart player)':' (po nustatymų pakeitimo reikia perkrauti grotuvą)',
    ' (after changing, switch the channel!)':' (po pakeitimo paleiskite grotuvą iš naujo!)',
    'Enter URL of server':'Įrašykite serverio adresą (URL)',
    'Enter username':'Įrašykite prisijungimo vardą',
    'Enter password':'Įrašykite slaptažodį',
    'Select stream type':'Pasirinkite srautų tipą',
    '??? No channel name':'??? Nėra kanalo pavadinimo',
    'Playlist URL':'Grojaraščio adresas (URL)',
    'Archive hours':'Įrašykite kiek valandų archyvo suteikia jūsų teikėjas',
    'Enter playlist URL':'Įrašykite grojaraščio adresą (URL)',
    'Enter playlist archive hours':'Įrašykite grojaraščio archyvo valandas',
    'show on-screen keyboard':'rodyti ekrano klaviatūrą',
    'Sleep without leaving player':'Miego režimas neišeinant iš grotuvo',
    'PiP is not available!':'PiP nepasiekiamas!',
    'NORMAL':'PAPRASTAS',
    'ENLARGE':'PADIDINITAS',
    'MAKE_WIDER':'PLOČIO PADIDINIMAS',
    'NON_LINEAR_STRETCH':'NELINIJINIS IŠTEMPIMAS',
    'NON_LINEAR_STRETCH_TO_FULL_SCREEN':'NELINIJINIS IŠTEMPIMAS PER VISĄ EKRANĄ',
    'MAKE_TALLER':'AUKŠČIO PADIDINIMAS',
    'CUT_EDGES':'KRAŠTŲ NUKIRPIMAS',
    'FULL_SCREEN':'VISAS EKRANAS',
    'STRETCH_TO_FULL_SCREEN':'IŠTEMPTI PER VISĄ EKRANĄ',
    'Background color':'Fono spalva',
    'Brightness':'Ryškumas',
    '3 hours':'3 valandos',
    'Restart stream / Live':'Tiesioginė transliacija / paleiskite srautą iš naujo',
    '- keyboard': '- klaviatūra',
    'Media':'Mediateka (VOD)',
    'String for search':'Paieškos eilutė',
    'Playlist Name':'Grojaraščio pavadinimas',
    'Enter playlist Name':'Įrašykite grojaraščio pavadinimą',
    'Media Library URL':'Medijos bibliotekos URL',
    'Enter Media Library URL':'Įrašykite medijos bibliotekos adresą (URL)',
    'Playlist':'Grojaraštis',
    'Select playlist':'Pasirinkite grojaraštį',
    'Edit':'Redaguoti',
    'Load':'Įkelti',
    'Edit playlist data':'Redaguoti grojaraščio duomenys',
    'Select portal':'Pasirinkite portalą',
    'Portal Name':'Portalo pavadinimas',
    'Enter Portal Name':'Įrašykite portalo pavadinimą',
    'Edit portal data':'Redaguoti portalo duomenys',
    'without':'be',
    'Settings STB':'Įrenginio nustatymai',
    'Soft audio render':'Minkštas garso pateikimas',
    'Long press horizontal arrows for volume control':'Norėdami reguliuoti garsumą, ilgai spauskite horizontalias rodykles',
    'Yes':'Taip',
    'Back':'Atgal',
    'Show providers?':'Rodyti teikėjų sąrašą?',
    'Hide providers?':'Paslėpti teikėjų sąrašą?',
    'Show provider settings?':'Rodyti teikėjų nustatymus?',
    'Hide provider settings?':'Slėpti teikėjų nustatymus?',
    'Clear all settings?':'Išvalyti visus nustatymus?',
    'Timer':'Laikmatis',
    'Set timer?':'Nustatyti laikmatį?',
    'Remove timer?':'Ištrinti laikmatį?',
    'Timer: switch to channel?':'Laikmatis: perjungti į kanalą?',
    ' (if archive exists)':' (jeigu yra archyvas)',
    'Preffered audio track':'Pageidaujamas garso takelis',
    'Information':'Informacija',
    'Lists settings':'Sąrašų nustatymai',
    'Channel list settings':'Kanalų sąrašų nustatymai',
    'Buttons settings':'Mygtukų nustatymai',
    'Subtitle':'Subtitrai',
    'Switch subtitle':'Perjungti subtitrus',
    'Off':'Išjungti',
    'Not found':'Nerasta',
    'History of watched movies':'Žiūrėtų filmų istorija',
    'Continue watching?':'Pratęsti žiūrėjimą?',
    'Add to favorites':'Pridėti į mėgstamiausius',
    'Delete':'Ištrinti',
    'Info about current stream':'Peržiūrėti informaciją apie srautą',
    'Stop':'Sustabdyti',
    'Playlist file':'Grojaraščio failas',
    'Select playlist file':'Pasirinkite grojaraščio failą',
    'Graphical indication':'Grafinis indikatorius',
    'Background color of selected item':'Pasirinkto elemento fono spalva',
    'Default':'Numatytasis',
    'Not supported!':'Nepalaikoma!',
    'Menu items settings':'Meniu elementų nustatymai',
    'Select menu items':'Pasirinkite meniu elementus',
// 13.5
    'Protect Adult Channels':'Suaugusiųjų kanalų apsauga',
    'Protect Settings':'Nustatymų apsauga',
    'Protect Change Provider':'Teikėjo pakeitimo apsauga',
    'Infobar settings':'Informacijos juostos nustatymai',
    'Show when switching':'Rodyti perjungiant',
    'Show when changing program':'Rodyti keičiant programą',
    'Show when rewind':'Rodyti atsukant atgal',
    'Archive. Category: ':'Archyvas. Kategorija: ',
    'Sort channels':'Rūšiuoti kanalus',
    '"As Is"':'"Pagal nutylėjimą"',
    'Load playlist':'Įkelti grojaraštį',
    ' (after changing, load playlist)':' (po pakeitimo įkelkite grojaraštį)',
    'Statistics of current stream':'Dabartinio srauto statistika',
    'Search':'Paieška',
// 14.6
    'Behavior of %1/%2 buttons in lists':'Mygtukų elgsena %1/%2 sąrašuose',
    'begin/end':'pradžia/pabaiga',
    'Position shift -10 seconds after pause':'Padėties poslinkis -10 sekundžių po pauzės',
    'Remember previous channels':'Prisiminti ankstesnius kanalus',
    'History in Media Library':'Istorija medijos bibliotekoje',
}
