keyStrings = {
    'lang':'Polski',
    'alhabet':'aąbcćdeęfghijklłmnńoóprsśtuwyzźż',
    'Channel list. Category: ':'Lista kanałów. Kategorie: ',
    'EPG':'EPG',
    'Category':'Kategoria',
    'Actions':'Akcje',
    'Description':'Opis',
    'Open in PiP':'Otwórz w PiP',
    'Move channel up':'Przesuń kanał w górę',
    'Move channel down':'Przesuń kanał w dół',
    'Delete channel':'Usuń kanał',
    'Add channel to category':'Dodaj kanał do kategorii',
    'Add channel to favorites':'Dodaj kanał do ulubionych',
    'Channel parental control':'Kontrola rodzicielska kanału',
    'Channel is not available!!!':'Kanał nie jest dostępny!!!',
    'min':'min',
    'Channel ':'Kanał ',
    ' added to category ':' dodano do kategorii ',
    ' added to favorites':' dodano do ulubionych',
    'Favorites':'Ulubione',
    'Select category to add channel':'Wybierz kategorię, aby dodać kanał',
    'Enter parental code':'Wpisz kod rodzica',
    'Wrong parental code !!!':'Nieprawidłowy kod rodzica!!!',
    '<br>UP<br>':'<br>W górę<br>',
    '<br>Delete':'<br>Usuń',
    '<br>Add<br>to favorites':'<br>Dodaj do<br>ulubionych',
    '<br>Add<br>to category':'<br>Dodaj do<br>kategorii',
    '<br>Parental<br>Control':'<br>Kontrola<br>rodzicielska',
    '<br>Down':'<br>W dół',
    'Close':'Zamknij',
    'Edit category name':'Zmień nazwę kategorii ',
    'Category %1 already exists!':'Kategoria %1 już istnieje!',
    'Enter name for new category':'Dodaj nazwę dla nowej kategorii',
    '<br>More...<br>':'<br>Więcej...<br>',
    '<br>Rename':'<br>Zmień nazwę',
    '<br>Copy<br>category':'<br>Skopiuj<br>kategorię',
    '<br>Back<br>':'<br>Wstecz<br>',
    '<br>Create<br>category':'<br>Utwórz<br>kategorię',
    'Category selection':'Wybierz kategorię',
    'Menu':'Menu',
    'Channel list':'Lista kanałów',
    'Move category up':'Przesuń kategorię w górę',
    'Move category down':'Przesuń kategorię w dół',
    'Create category':'Utwórz kategorię',
    'Rename category':'Zmień nazwę kategorii',
    'Copy category':'Skopiuj kategorię',
    'Delete category':'Usuń kategorię',
    'Su Mo Tu We Th Fr Sa':'Nd Pn Wt Śr Cz Pt Sb',
    'EPG and archive. Channel: ':'EPG i archiwum. Kanał: ',
    'By alphabet':'Alfabetycznie',
    'Archive. Channel: ':'Archiwum. Kanał: ',
    'By time':'Po czasie',
    'Player info:':'Informacje o odtwarzaczu:',
    'Device info:':'Informacje o urządzeniu:',
    '- switch:':'- przełącz:',
    '- erase':'- wyczyść',
    '- move cursor':'- przesuń kursor',
    '- return without save':'- wróć bez zapisywania',
    '- save':'- zapisz',
    'Return to previous channel':'Wróć do poprzedniego kanału',
    'Call PiP / PiP exchange':'Połączenie PiP / PiP zamiana',
    'Info about TV program':'Informacje o programie telewizyjnym',
    'Show player menu':'Pokaż menu odtwarzacza',
    'Interface settings':'Ustawienia interfejsu',
    'Show channel selection list':'Pokaż listę wyboru kanałów',
    'Hide / Return':'Ukryj / Cofnij',
    'Exit player':'Wyjdź z odtwarzacza',
    'Show EPG and archive for channel':'Pokaż EPG i archiwum kanału',
    'Channel category selection':'Wybór kategorii kanału',
    'Toggle Aspect Ratio':'Włącz współczynnik proporcji',
    'Toggle Zoom Mode':'Włącz tryb powiększenia',
    'Switch sound track':'Zmień ścieżkę dźwiękową',
    'In live mode: <br/>':'W trybie na żywo:<br/>',
    'Channel selection by number':'Wybór kanału po numerze',
    'Timeshift: to start of TV program':'Przeskocz: do startu programu',
    'Timeshift: one minute back':'Przeskocz: jedną minutę do tyłu',
    '<br/><br/>In archive mode:<br/>':'<br/><br/>W trybie archiwizacji:<br/>',
    'Pause/Play':'Zatrzymaj/Odtwórz',
    'Stop playback and return to In live mode':'Zatrzymaj odtwarzanie i wróć do trybu na żywo',
    'To start of TV program / Previous TV program':'Do startu programu / Poprzedni program',
    'Next TV program':'Następny program',
    'Back / Forward for 1 minute':'Do tyłu / Do przodu 1 minutę',
    'Back / Forward for 15 seconds':'Do tyłu / Do przodu 15 sekund',
    'Back / Forward for 3 minutes':'Do tyłu / Do przodu 3 minuty',
    'Back / Forward for 10 minutes':'Do tyłu / Do przodu 10 minut',
    'Show rewind window':'Pokaż okno przewijania',
    'Description of remote control buttons':'Opis przycisków pilota',
    'Description of remote control buttons depending on the view mode':'Opis przycisków pilota w zależności od trybu wyświetlania',
    'Set parental code':'Ustaw kod rodzica',
    'Repeat parental code':'Powtórz kod rodzica',
    'Show list of channel archive records':'Pokaż listę nagrań kanału',
    'Show list of channel archive records without duplication':'Pokaż listę zapisów archiwalnych kanału bez duplikatów',
    'Show Media Library':'Pokaż bibliotekę multimediów',
    'Show Media Library (if available from provider)':'Pokaż bibliotekę multimediów (jeśli jest dostępna od dostawcy)',
    'Rewind':'Przewiń',
    'Close PiP':'Zamknij PiP',
    'Parental control':'Kontrola rodzicielska',
    'Change provider':'Zmień dostawcę',
    'Change provider - you can change the provider, and it will be remembered at the next start of player!':'Zmień dostawcę - możesz zmienić dostawcę i zostanie on zapamiętany przy następnym uruchomieniu odtwarzacza!',
    'Restart player':'Uruchom ponownie odtwarzacz',
    'Restart player - after changing provider settings (as example)':'Uruchom ponownie odtwarzacz - np. po zmianie ustawień dostawcy',
    'Description of remote control buttons':'Opis przycisków pilota',
    'About':'Na temat',
    'Player and device info':'Informacje o odtwarzaczu i urządzeniu',
    'Donate <div class="btn" style="background-color:orange;">donate</div>':'Darowizna <div class="btn" style="background-color:orange;">Darowizna</div>',
    'Voluntary donation for the development of project':'Dobrowolna darowizna na rozwój projektu',
    'Settings saved':'Ustawienia zostały zapisane',
    'no':'nie',
    'yes':'tak',
    'Records':'Lista nagrań',
    'Previous':'Poprzednie',
    'Info':'Informacje',
    'Not reduce video when showing the list (bugfix)':'Nie zmniejszaj wideo podczas wyświetlania listy (poprawka)',
    'Black screen while switching the channel':'Czarny ekran podczas zaminy kanału',
    'PiP window size':'Rozmiar okna PiP',
    'small':'mały',
    'medium':'średni',
    'large':'duży',
    'PiP window position':'położenie okna PiP',
    'top-right':'góra prawo',
    'bottom-right':'dół prawo',
    'left-bottom':'dół lewo',
    'top-left':'góra lewo',
    'Number of rows in lists':'Liczba wierszy na liście',
    'Distance between lines in lists':'Odległość pomiędzy wierszami na liście',
    'Font type':'Czcionka',
    'volume':'glośność',
    'paging':'stronicowanie',
    'Nothing':'Nic',
    'Exit':'Wyjście',
    'Joystick':'Joystick',
    'Button %1 function when viewing':'Funkcja przycisku %1 podczas przeglądania',
    'Button function %1 when viewing archive':'Funkcja przycisku %1 podczas przeglądania archiwum',
    'Channels':'Kanały',
    'Remote (color buttons N/A)':'Pilot (kolory przycisków)',
    'Remote (number buttons N/A)':'Pilot (numery przycisków)',
    'Timezone':'Strefa czasowa',
    'Sleep timer':'Wyłącznik czasowy',
    'off':'wyłączony',
    '30 minutes':'30 minut',
    '1 hour':'1 godzina',
    '2 hours':'2 godziny',
    'Infobar display timeout, s':'Limit czasu wyświetlania paska informacyjnego, s',
    '"Sliding" infobar':'"Przesuwany" pasek informacyjny',
    'Interface transparency':'Przezroczystość interfejsu',
    'Volume step, %':'Poziom głośności, %',
    'List location':'Lokalizacja listy',
    'right':'prawo',
    'left':'lewo',
    'Color spectrum':'Zakres kolorów',
    'select':'wybierz',
    'Permanent clock on screen':'Stały zegar na ekranie',
    'Show channel number in list':'Pokaż numer kanału na liście',
    'Show picons in channel list':'Pokaż picony na liście kanałów',
    'Show channel name in list':'Pokaż nazwy kanałów na liście',
    'Show progress in channel list':'Pokaż postęp na liście kanałów',
    'Show archive availability in list':'Pokaż dostępność archiwum na liście',
    'Show scrollbar in list':'Pokaż pasek przewijania na liście',
    'Preview in channel list':'Podgląd na liście kanałów',
    'always':'zawsze',
    'on ':'na ',
    'Number of next TV programs in channel list':'Numer kolejnych porogramów na liście kanałów',
    'Channel list editing style':'Styl edycji listy kanałów',
    'All categories':'Wszystkie kategorie',
    '"Favorites"':'"Ulubione"',
    'Editor':'Edytor',
    'built-in':'wbudowany',
    'native':'naturalny',
    'HDMI-CEC support (on/off from TV)':'Obsługa HDMI-CEC (włączanie/wyłączanie z telewizora)',
    'Type of player for streaming':'Rodzaj odtwarzacza do przesyłania na żywo',
    'Autostart of player':'Autostart odtwarzacza',
    'Buffer Size, s':'Rozmiar bufora, s',
    'Choose from':'Wybierz z',
    'Settings':'Ustawienia',
    'Change value':'Zmień wartość',
    'Save Settings':'Zapisz ustawienia',
    'To beginning':'Na początek',
    'Live':'Na żywo',
    ' m ':' min ',
    ' s':' s',
    '1 minute':'1 minuta',
    '10 Seconds':'10 sekund',
    'Go to':'Przejdź do',
    'Archive - begin':'Archiwizuj - rozpocznij',
    'Pause':'Pauza',
    'Play':'Odtwórz',
    'Shutdown after %1 seconds<br/><br/>Cancel - any action':'Zamknięcie za %1 sekund<br/><br/>Przerwij - jakiekolwiek działanie',
    'Do you want to exit player?':'Czy chcesz wyjść z odtwarzacza?',
    'Color':'Kolor',
    'Saturation':'Nasycenie',
    'Yellow':'Żółty',
    'Green':'Zielony',
    'Blue':'Niebieski',
    'Set':'Ustaw',
    'Restart stream':'Uruchom ponownie stream',
    'Favorites':'Ulubione',
    'All':'Wszystkie',
    '<br/>Processing the channel list...':'<br/>Przetwarzanie listy kanałów...',
    '<br/>Start playback...':'<br/>Rozpoczynanie odtwarzania...',
    '<br/>Channel list not received !!!':'<br/>Nie otrzymano listy kanałów!!!',
    'Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>':'Nie otrzymano listy kanałów!!!<br/><br/>Wprowadź dane dostawcy i uruchom ponownie odtwarzacz!!!<br/><br/>',
    'Error getting channel list !!!':'Błąd podczas pobierania listy kanałów!!!',
    'system':'system',
    'Choose provider':'Wybierz dostawcę',
    '<br>Rewind<br>':'<br>Przewijanie<br>',
    '<br>Menu':'<br>Menu',
    '<br>Pause<br>':'<br>Pauza<br>',
    '<br>Toggle<br>sound track':'<br>Przełącz<br>ścieżkę dźwiękową',
    '<br>Live':'<br>Transmisja na żywo',
    '<br>Previous<br>channel':'<br>Poprzedni<br>kanał',
    '<br/><b>Failed to load provider script !!!</b>':'<br/><b>Nie udało się załadować skryptu dostawcy!!!</b>',
    '<br/>Loading provider %1 script ...':'<br/>Ładowanie skryptu dostawcy %1 ...',
    '<br/>Loading settings...':'<br/>Ładowanie ustawień...',
    '<br/>Loading channel list...':'<br/>Ładowanie listy kanałów...',
    'Choose language':'Wybierz język',
    'Change interface language':'Zmień język interfejsu',
    'Aspect':'Wygląd',
    'Audio':'Audio',
    'Stalker portals':'Portale stalkerów',
    'm3u-m3u8 playlists':'playlisty m3u-m3u8',
    '<br/>Loading STB...':'<br/>Ładowanie STB...',
    '<br/>Setup STB...':'<br/>Konfiguracja STB...',
    'Save settings to storage':'Zapisz ustawienia w pamięci',
    'Load settings from storage':'Załaduj ustawienia z pamięci',
    'Download':'Pobierz',
    'Skip this version':'Pomiń tę wersję',
    'Volume control':'Regulacja głośności',
    'Long button presses':'Długie przytrzymanie przycisku',
    'Download new version Android App':'Pobierz nową wersję aplikacji na Androida',
    'To access you must enter url, username and password!':'Aby uzyskać dostęp, musisz wprowadzić adres URL, nazwę użytkownika i hasło!',
    'Failed to load channel list!':'Nie udało się załadować listy kanałów!',
    'Year':'Rok',
    'Duration':'Czas trwania',
    'Genre':'Gatunek',
    'Country':'Kraj',
    'Director':'Reżyser',
    'Actors':'Aktorzy',
    'Release date':'Data publikacji',
    'Rating':'Ocena',
    'Season':'Sezon',
    'Episodes':'Odcinki',
    'VOD':'VOD',
    'TV series':'Seriale telewizyjne',
    'Episode':'Odcinek',
    'Download! Wait ...':'Pobieranie! Czekaj ...',
    'Server':'Serwer',
    'URL':'URL',
    'Username':'Nazwa użytkownika',
    'Password':'Hasło',
    'Stream type':'Rodzaj transmisji',
    'Account info':'Informacje o koncie',
    'Select server number from 1 to 6 to save data':'Wybierz numer serwera od 1 do 6, aby zapisać dane',
    ' (after changing, restart player)':' (po zmianie, uruchom ponownie odtwarzacz)',
    ' (after changing, switch the channel!)':' (po zmianie, zmień kanał!)',
    'Enter URL of server':'Wpisz URL serwera',
    'Enter username':'Wpisz nazwę użytkownika',
    'Enter password':'Wpisz hasło',
    'Select stream type':'Wybierz typ transmisji',
    '??? No channel name':'??? Brak nazwy kanału',
    'Playlist URL':'URL playlisty',
    'Archive hours':'Godziny archiwizacji',
    'Enter playlist URL':'Wpisz URL playlisty',
    'Enter playlist archive hours':'Wpisz godziny archiwizacji playlisty',
    'show on-screen keyboard':'pokaż klawiaturę ekranową',
    'Sleep without leaving player':'Uśpij bez wychodzenia z odtwarzacza',
    'PiP is not available!':'PiP nie jest dostępne!',
    'NORMAL':'NORMALNY',
    'ENLARGE':'POWIĘKSZONY',
    'MAKE_WIDER':'ZRÓB_SZERSZY',
    'NON_LINEAR_STRETCH':'NIELINIOWE_ROZCIĄGANIE',
    'NON_LINEAR_STRETCH_TO_FULL_SCREEN':'NIELINIOWE_ROZCIĄGANIE_DO_CAŁEGO_EKRANU',
    'MAKE_TALLER':'ZRÓB_WYŻSZY',
    'CUT_EDGES':'ZETNIJ_KRAWĘDZIE',
    'FULL_SCREEN':'PEŁNY_EKRAN',
    'STRETCH_TO_FULL_SCREEN':'ROZCIĄGNIJ_DO_PEŁNEGO_EKRANU',
    'Background color':'Kolor tła',
    'Brightness':'Jasność',
    '3 hours':'3 godziny',
    'Restart stream / Live':'Uruchom ponownie stream / Na żywo',
    '- keyboard': '- klawiatura',
    'Media':'Media',
    'String for search':'Tekst do wyszukania',
    'Playlist Name':'Nazwa playlisty',
    'Enter playlist Name':'Podaj playlistę',
    'Media Library URL':'URL biblioteki mediów',
    'Enter Media Library URL':'Podaj URL biblioteki mediów',
    'Playlist':'Playlista',
    'Select playlist':'Wybierz playlistę',
    'Edit':'Edytuj',
    'Load':'Wczytaj',
    'Edit playlist data':'Edytuj dane playlisty',
    'Select portal':'Wybierz portal',
    'Portal Name':'Nazwa portalu',
    'Enter Portal Name':'Wpisz nazwę portalu',
    'Edit portal data':'Edytuj dane portalu',
    'without':'bez',
    'Settings STB':'Ustawienia STB',
    'Soft audio render':'Łagodne renderowanie audio',
    'Long press horizontal arrows for volume control':'Przytrzymaj strzałki poziome aby sterować głośnością',
    'Yes':'Tak',
    'Back':'Cofnij',
    'Show providers?':'Pokazać dostawcę?',
    'Hide providers?':'Ukryć dostawcę?',
    'Show provider settings?':'Pokazać ustawienia dostawcy?',
    'Hide provider settings?':'Ukryć ustawienia dostawcy?',
    'Clear all settings?':'Wyczyścić wszystkie ustawienia?',
    'Timer':'Minutnik',
    'Set timer?':'Ustawić minutnik?',
    'Remove timer?':'Usunać minutnik?',
    'Timer: switch to channel?':'Minutnik: przełączyć na kanał?',
    ' (if archive exists)':' (jeżeli istnieje archiwum)',
    'Preffered audio track':'Preferowana ścieżka dźwiękowa',
    'Information':'Inforamcje',
    'Lists settings':'Ustawienia listy',
    'Channel list settings':'Ustawienia listy kanału',
    'Buttons settings':'Ustawienia przycisków',
    'Subtitle':'Napisy',
    'Switch subtitle':'Przełącz napisy',
    'Off':'Wyłączone',
    'Not found':'Nie znaleziono',
    'History of watched movies':'Historia oglądanych filmów',
    'Continue watching?':'Kontynuować oglądanie?',
    'Add to favorites':'Dodaj do ulubionych',
    'Delete':'Usuń',
    'Info about current stream':'Informacje o aktualnym streamie',
    'Stop':'Zatrzymaj',
    'Playlist file':'Plik playlisty',
    'Select playlist file':'Wybierz plik playlisty',
    'Graphical indication':'Oznaczenie graficzne',
    'Background color of selected item':'Kolor tła wybranego elemetu',
    'Default':'Domyślne',
    'Not supported!':'Nieobsługiwany!',
    'Menu items settings':'Ustawienia elementów menu',
    'Select menu items':'Wybierz elementy menu',
// 13.5
    'Protect Adult Channels':'Ochrona kanałów dla dorosłych',
    'Protect Settings':'Ochrona ustawień',
    'Protect Change Provider':'Chroń zmianę dostawcy',
    'Infobar settings':'Ustawienia paska informacji',
    'Show when switching':'Pokaż podczas przełączania',
    'Show when changing program':'Pokaż przy zmianie programu',
    'Show when rewind':'Pokaż podczas przewijania',
    'Archive. Category: ':'Archiwum. Kategoria: ',
    'Sort channels':'Sortuj kanały',
    '"As Is"':'"Tak jak jest"',
    'Load playlist':'Wczytaj playlistę',
    ' (after changing, load playlist)':' (po zmianie wczytaj playlistę)',
    'Statistics of current stream':'Statystyki bieżącego strumienia',
    'Search':'Szukaj',
// 14.6
    'Behavior of %1/%2 buttons in lists':'Zachowanie przycisków %1/%2 na listach',
    'begin/end':'początek/koniec',
    'Position shift -10 seconds after pause':'Zmiana pozycji o -10 sekund po przerwie',
    'Remember previous channels':'Zapamiętaj poprzednie kanały',
    'History in Media Library':'Historia przeglądania w bibliotece',
}
