keyStrings = {
    'lang':'Português',
    'alhabet':'AÂÃBCÇDEFGHIJKLMNOÔÕPQRSTUVWXYZ',
    'Channel list. Category: ':'Lista de Canais. Categoria: ',
    'EPG':'Guia de programação',
    'Category':'Categorias',
    'Actions':'Ações',
    'Description':'Descrição',
    'Open in PiP':'Abrir em PiP',
    'Move channel up':'Mover o canal para cima',
    'Move channel down':'Mover o canal para baixo',
    'Delete channel':'Eliminar canal',
    'Add channel to category':'Adicionar o canal a categoria',
    'Add channel to favorites':'Adicionar o canal aos Favoritos',
    'Channel parental control':'Controle parental para o canal',
    'Channel is not available!!!':'Canal não está disponível!!!',
    'min':'minutos',
    'Channel ':'Canal ',
    ' added to category ':' Adicionado a categoría ',
    ' added to favorites':' Adicionado aos Favoritos',
    'Favorites':'Favoritos',
    'Select category to add channel':'Selecione uma categoria para adicionar o canal',
    'Enter parental code':'Insira a senha para o controle parental',
    'Wrong parental code !!!':'Senha incorreta !!!',
    '<br>Up<br>':'<br>Acima<br>',
    '<br>Delete':'<br>Eliminar',
    '<br>Add<br>to favorites':'<br>Adicionar<br>aos Favoritos',
    '<br>Add<br>to category':'<br>Adicionar<br>a categoría',
    '<br>Parental<br>Control':'<br>Controle<br>parental',
    '<br>Down':'<br>Abaixo',
    'Close':'Fechar',
    'Edit category name':'Editar o nome da categoria',
    'Category %1 already exists!':'A categoria %1 já existe!',
    'Enter name for new category':'Digite um nome para a nova categoria',
    '<br>More...<br>':'<br>Mais...<br>',
    '<br>Rename':'<br>Renomear',
    '<br>Copy<br>category':'<br>Copiar<br>categoria',
    '<br>Back<br>':'<br>Volver<br>',
    '<br>Create<br>category':'<br>Criar<br>categoria',
    'Category selection':'Selecionar categoría',
    'Menu':'Menu',
    'Channel list':'Lista de Canais',
    'Move category up':'Mover a categoría para cima',
    'Move category down':'Mover a categoria para baixo',
    'Create category':'Criar uma categoria',
    'Rename category':'Renomear categoria',
    'Copy category':'Copiar categoria',
    'Delete category':'Eliminar la categoría',
    'Su Mo Tu We Th Fr Sa':'Dom Seg Ter Qua Qui Sex Sáb',
    'EPG and archive. Channel: ':'Guia da tv e arquivo. Canal: ',
    'By alphabet':'Por alfabeto',
    'Archive. Channel: ':'Arquivo. Canal: ',
    'By time':'Por tempo',
    'Player info:':'Informações sobre Player:',
    'Device info:':'Informacões sobre o dispositivo:',
    '- switch:':'- trocar:',
    '- erase':'- apagar',
    '- move cursor':'- mover o cursor',
    '- return without save':'- voltar sem salvar',
    '- save':'- salvar',
    'Return to previous channel':'Voltar ao canal anterior',
    'Call PiP / PiP exchange':'Abrir PiP / Trocar de tela com o PiP',
    'Info about TV program':'Informacão sobre o programa de TV',
    'Show player menu':'Mostrar o menu do Player',
    'Interface settings':'Configuração de interface',
    'Show channel selection list':'Mostrar a lista de seleção de canal',
    'Hide / Return':'Esconder a informação / Voltar',
    'Exit player':'Sair do Player',
    'Show EPG and archive for channel':'Mostrar Guia de programação e arquivo do canal',
    'Channel category selection':'Escolher a categoria dos canais',
    'Toggle Aspect Ratio':'Alterar o modo "Proporção de aspecto da tela" (Aspect Ratio)',
    'Toggle Zoom Mode':'Alterar o modo de Zoom',
    'Switch sound track':'Alterar o canal de áudio',
    'In live mode: <br/>':'Em modo ao vivo:<br/>',
    'Channel selection by number':'Escolher o canal pelo número',
    'Timeshift: to start of TV program':'Timeshift: Voltar ao inicio de programa de TV',
    'Timeshift: one minute back':'Timeshift: Voltar 1 minuto',
    '<br/><br/>In archive mode:<br/>':'<br/><br/>Em modo de arquivo:<br/>',
    'Pause/Play':'Pause/Play',
    'Stop playback and return to In live mode':'Parar reprodução e retornar ao modo ao vivo',
    'To start of TV program / Previous TV program':'Ao inicio do programa de TV / Ao seguinte programa de TV',
    'Next TV program':'Próximo programa',
    'Back / Forward for 1 minute':'Voltar / Avançar a 1 minuto',
    'Back / Forward for 15 seconds':'Voltar / Avançar a 15 segundos',
    'Back / Forward for 3 minutes':'Voltar / Avançar a 3 minutos',
    'Back / Forward for 10 minutes':'Voltar / Avançar a 10 minutos',
    'Show rewind window':'Mostrar a tela de retrocesso',
    'Description of remote control buttons':'Descrição das funções dos botões do controle remoto',
    'Description of remote control buttons depending on the view mode':'Descrição das funções dos botões do controle remoto que dependem do modo de visualização',
    'Set parental code':'Defina a senha do controle parental',
    'Repeat parental code':'Repita a senha do controle parental',
    'Show list of channel archive records':'Mostrar a lista de arquivos de gravações do canal',
    'Show list of channel archive records without duplication':'Mostrar a lista de arquivos de gravações do canal sem repetições',
    'Show Media Library':'Mostrar a biblioteca de midia',
    'Rewind':'Retroceder',
    'Close PiP':'Fechar PiP',
    'Parental control':'Controle parental',
    'Change provider':'Alterar provedor',
    'Change provider - you can change the provider, and it will be remembered at the next start of player!':'Alterar provedor - Você pode alterar o provedor e sua escolha será lembrada durante a próxima ativação do player!',
    'Restart player':'Reiniciar Player',
    'Restart player - after changing provider settings (as example)':'Reiniciar Player - depois de alterar as configurações do provedor (por exemplo)',
    'Description of remote control buttons':'Descrição dos botões do controle remoto',
    'About':'Informacão',
    'Player and device info':'Informação sobre o Player e dispositivo',
    'Donate <div class="btn" style="background-color:orange;">donate</div>':'Ajude este projeto <div class="btn" style="background-color:orange;">Doando</div>',
    'Voluntary donation for the development of project':'Ajuda voluntária para o desenvolvimento deste projeto',
    'Settings saved':'Configurações salvas',
    'no':'não',
    'yes':'sim',
    'Records':'Gravações',
    'Previous':'Anterior',
    'Info':'Info',
    'Not reduce video when showing the list (bugfix)':'Não reduzir o tamanho da tela ao mostrar a lista (bugfix)',
    'Black screen while switching the channel':'Tela preta durante a troca de canais',
    'PiP window size':'Tamanho da janela do PiP',
    'small':'pequeno',
    'medium':'médio',
    'large':'grande',
    'PiP window position':'Posição da janela do PiP',
    'top-right':'Direita-acima',
    'bottom-right':'Direita-abaixo',
    'left-bottom':'Esquerda-abaixo',
    'top-left':'Esquerda-acima',
    'Number of rows in lists':'Quantidade de linhas na lista',
    'Distance between lines in lists':'Distância entre as linhas na lista',
    'Font type':'Tipo de fonte',
    'volume':'volume',
    'paging':'paginação',
    'Nothing':'Nada',
    'Exit':'Sair',
    'Joystick':'Joystick',
    'Button %1 function when viewing':'Função do botão %1 durante a visualização',
    'Button function %1 when viewing archive':'Função do botão %1 durante a visualização de arquivos',
    'Channels':'Canais',
    'Remote (color buttons N/A)':'Controle remoto sem botões coloridos',
    'Remote (number buttons N/A)':'Controle remoto sem botões numéricos',
    'Timezone':'Fuso horário',
    'Sleep timer':'Temporizador para desligar',
    'off':'desativado',
    '30 minutes':'30 minutos',
    '1 hour':'1 hora',
    '2 hours':'2 horas',
    'Infobar display timeout, s':'Tempo para mostrar barra de informações na tela, s',
    '"Sliding" infobar':'Animar barra de informações',
    'Interface transparency':'Transparência da interface',
    'Volume step, %':'Passo de volume, %',
    'List location':'Posição da lista',
    'right':'Direita',
    'left':'Esquerda',
    'Color spectrum':'Espectro de cores',
    'select':'Selecionar',
    'Permanent clock on screen':'Mostrar relógio permanentemente na tela',
    'Show channel number in list':'Mostrar o número do canal na lista',
    'Show picons in channel list':'Mostrar imagens na lista de canais',
    'Show channel name in list':'Mostrar o nome do canal na lista',
    'Show progress in channel list':'Mostrar o progresso na lista',
    'Show archive availability in list':'Mostrar a possibilidade de arquivo do canal na lista',
    'Show scrollbar in list':'Mostrar barra de rolagem na lista',
    'Preview in channel list':'Mostrar prévia na lista de canais',
    'always':'sempre',
    'on ':'por ',
    'Number of next TV programs in channel list':'Quantidade de programas seguintes na lista de canais',
    'Channel list editing style':'Estilo de editar canais',
    'All categories':'Todas as categorías',
    '"Favorites"':'"Favoritos"',
    'Editor':'Editor',
    'built-in':'integrado',
    'native':'nativo',
    'HDMI-CEC support (on/off from TV)':'Disponibilidade de HDMI-CEC (Ativar / Desativar na TV)',
    'Type of player for streaming':'Tipo de Player para a reprodução',
    'Autostart of player':'Abrir Player ao iniciar',
    'Buffer Size, s':'Tamanho do buffer, s',
    'Choose from':'Escolha de',
    'Settings':'Configurações',
    'Change value':'Alterar valor',
    'Save Settings':'Salvar configurações',
    'To begining':'Do começo',
    'Live':'Ao vivo',
    ' m ':' min ',
    ' s':' seg',
    '1 minute':'1 minuto',
    '10 Seconds':'10 segundos',
    'Go to':'Ir para',
    'Archive - begin':'Arquivo - do inicio',
    'Pause':'Pausar',
    'Play':'Reproduzir',
    'Shutdown after %1 seconds<br/><br/>Cancel - any action':'Saindo em %1 segundos<br/><br/>Cancelar - Qualquer ação',
    'Do you want to exit player?':'Tem certeza que deseja sair?',
    'Color':'Cor',
    'Saturation':'Saturação',
    'Yellow':'Amarelo',
    'Green':'Verde',
    'Blue':'Azul',
    'Set':'Definir',
    'Restart stream':'Reiniciar a transmissão',
    'Favorites':'Favoritos',
    'All':'Todos',
    '<br/>Processing the channel list...':'<br/>Processando a lista de canais...',
    '<br/>Start playback...':'<br/>Iniciando a reprodução...',
    '<br/>Channel list not received !!!':'<br/>Não foi possível receber a lista de canais!!!',
    'Channel list not received !!!<br/><br/>Confira os dados do provedor e reinicie o player !!!<br/><br/>':'Não foi possível receber a lista de canais!!!<br/><br/>Insira os dados do provedor e reinicie o player!!!<br/><br/>',
    'Error getting channel list !!!':'Erro ao obter a lista de canais!!!',
    'system':'do sistema',
    'Choose provider':'Selecione um provedor',
    '<br>Rewind<br>':'<br>Retroceder<br>',
    '<br>Menu':'<br>Menu',
    '<br>Pause<br>':'<br>Pausa<br>',
    '<br>Toggle<br>sound track':'<br>Alterar o canal<br>de áudio',
    '<br>Live':'<br>Ao vivo',
    '<br>Previous<br>channel':'<br>Canal<br>anterior',
    '<br/><b>Failed to load provider script !!!</b>':'<br/><b>Erro ao carregar o script do provedor!!!</b>',
    '<br/>Loading provider %1 script ...':'<br/>Carregando script do provedor %1 ...',
    '<br/>Loading settings...':'<br/>Carregando configurações...',
    '<br/>Loading channel list...':'<br/>Carregando a lista de canais...',
    'Choose language':'Escolha o idioma',
    'Change interface language':'Alterar o idioma da interface',
    'Aspect':'Aspecto',
    'Audio':'Canal de áudio',
    'Stalker portals':'Portal Stalker',
    'm3u-m3u8 playlists':'Lista em m3u-m3u8',
    '<br/>Loading STB...':'<br/>Carregando STB...',
    '<br/>Setup STB...':'<br/>Configurando STB...',
    'Save settings to storage':'Gravar a configuração em um pendrive USB',
    'Load settings from storage':'Carregar a configuração de um pendrive USB',
    'Download':'Baixar',
    'Skip this version':'Pular essa versão',
    'Volume control':'Controle de volume',
    'Long button presses':'Manter botão pressionado',
    'Download new version Android App':'Baixar a nova versão do aplicativo',
    'To access you must enter url, username and password!':'Para acessar insira URL, nome do usuário e senha!',
    'Failed to load channel list!':'Erro ao carregar a lista de canais!!',
    'Year':'Ano',
    'Duration':'Duração',
    'Genre':'Gênero',
    'Country':'Pais',
    'Director':'Diretor',
    'Actors':'Atores',
    'Release date':'Data do lançamento',
    'Rating':'Avaliação',
    'Season':'Temporada',
    'Episodes':'Quantidade de episódios',
    'VOD':'Filmes',
    'TV series':'Séries',
    'Episode':'Episodio',
    'Download! Wait ...':'Baixando! Aguarde...',
    'Server':'Servidor',
    'URL':'URL',
    'Username':'Nome do usuário',
    'Password':'Senha',
    'Stream type':'Тipo de stream',
    'Account info':'Informações da conta',
    'Select server number from 1 to 6 to save data':'Escolha um número de 1 a 6 para guardar as informações do servidor',
    ' (after changing, restart player)':' (Após alterar, deve reiniciar o player)',
    ' (after changing, switch the channel!)':' (Após alterar, deve trocar de canal!)',
    'Enter URL of server':'Editar URL do servidor',
    'Enter username':'Editar o nome do usuário',
    'Enter password':'Editar a senha',
    'Select stream type':'Escolha o tipo do stream',
    '??? No channel name':'Canal sem nome???',
    'Playlist URL':'URL da playlist',
    'Archive hours':'Quantidade de horas de arquivo',
    'Enter playlist URL':'Digite a URL da Playlist',
    'Enter playlist archive hours':'Digite a quantidade de horas de arquivos na Playlist',
    'show on-screen keyboard':'Mostrar o teclado na tela',
    'Sleep without leaving player':'Entrar em modo Sleep sem sair do player',
    'PiP is not available!':'PiP não está disponível!',
    'NORMAL':'NORMAL',
    'ENLARGE':'AUMENTAR',
    'MAKE_WIDER':'EXTENDER',
    'NON_LINEAR_STRETCH':'ALONGAMENTO NÃO LINEAR',
    'NON_LINEAR_STRETCH_TO_FULL_SCREEN':'ALONGAMENTO NÃO LINEAR PARA TELA CHEIA',
    'MAKE_TALLER':'ALTURA AUMENTADA',
    'CUT_EDGES':'RECORTAR NAS BORDAS',
    'FULL_SCREEN':'TELA CHEIA',
    'STRETCH_TO_FULL_SCREEN':'ALONGAR PARA TELA CHEIA',
    'Background color':'Cor de fundo',
    'Brightness':'Intensidade',
    '3 hours':'3 horas',
    'Restart stream / Live':'Reiniciar transmissão / ao vivo',
    '- keyboard': '- teclado',
    'Media':'Media',
    'String for search':'Barra de busca',
    'Playlist Name':'Nome da Playlist',
    'Enter playlist Name':'Insira o nome da Playlist',
    'Media Library URL':'URL da biblioteca ',
    'Enter Media Library URL':'Insira a URL da biblioteca',
    'Playlist':'Playlist',
    'Select playlist':'Selecionar playlist',
    'Edit':'Editar',
    'Load':'Carregar',
    'Edit playlist data':'Editar os dados da playlist',
    'Select portal':'Selecionar portal',
    'Portal Name':'Nome do portal',
    'Enter Portal Name':'Insira o nome do portal',
    'Edit portal data':'Editar os dados do portal',
    'without':'sem',
    'Settings STB':'Configurações do STB',
    'Soft audio render':'Decodificar audio via software',
    'Long press horizontal arrows for volume control':'Controla volume mantendo pressionado as setas horizontais',
    'Yes':'Sim',
    'Back':'Voltar',
    'Show providers?':'Mostrar os provedores?',
    'Hide providers?':'Ocultar os provedores?',
    'Show provider settings?':'Mostrar a configuração do provedor?',
    'Hide provider settings?':'Ocultar a configuração do provedor?',
    'Clear all settings?':'Apagar todas as configurações?',
    'Timer':'Temporizador',
    'Set timer?':'Ativar temporizador?',
    'Remove timer?':'Remover temporizador?',
    'Timer: switch to channel?':'Temporizador: trocar de canal?',
    ' (if archive exists)':' (se estiver disponivel o arquivo do canal)',
    'Preffered audio track':'Canal de áudio preferido',
    'Information':'Informação',
    'Lists settings':'Configuração das listas',
    'Channel list settings':'Configuração da lista de canais',
    'Buttons settings':'Configuração dos botões do controle remoto',
    'Subtitle':'Legendas',
    'Switch subtitle':'Trocar legenda',
    'Off':'Desativar',
    'Not found':'Não encontrado',
    'History of watched movies':'Conteúdos vistos anteriormente',
    'Continue watching?':'Continuar a assistir do ponto que parou?',
    'Add to favorites':'Adicionar aos favoritos',
    'Delete':'Apagar',
    'Info about current stream':'Informações sobre o fluxo corrente',
    'Stop':'Stop',
    'Playlist file':'Arquivo de playlist',
    'Select playlist file':'Seleção de arquivo de playlist',
    'Graphical indication':'Indicação gráfica',
    'Background color of selected item':'Cor de fundo do elemento selecionado',
    'Default':'Padrão',
    'Not supported!':'Não é suportado!',
    'Menu items settings':'Configuração dos elementos do menu',
    'Select menu items':'Escolher os elementos do menu',
    'Protect Adult Channels':'Proteção de "canais para adultos"',
    'Protect Settings':'Proteção das configurações',
    'Protect Change Provider':'Proteção de troca de provedores',
    'Infobar settings':'Configuração da barra de informações',
    'Show when switching':'Mostrar durante a troca de canal',
    'Show when changing program':'Mostrar durante a troca de programa',
    'Show when rewind':'Mostrar durante retrocede',
    'Archive. Category: ':'Arquivo. Categoria: ',
    'Sort channels':'Ordenar canais',
    '"As Is"':'"Assim como é"',
    'Load playlist':'Carregar a playlist',
    ' (after changing, load playlist)':' (Depois de alterar, carregue a playlist)',
    'Statistics of current stream':'Estatísticas do fluxo corrente',
    'Search':'Busca',
// 14.6
    'Behavior of %1/%2 buttons in lists':'Comportamento dos botoões %1/%2 nas listas',
    'begin/end':'inicio/final',
    'Position shift -10 seconds after pause':'Trocar a posição em -10 segundos depois de pausar',
    'Remember previous channels':'Lembrar canais vistos anteriormente',
    'History in Media Library':'Conteúdos vistos anteriormente na biblioteca',
// 5.11
    'Manage settings':'Gerenciar configurações',
    'Save settings':'Salvar configurações',
    'Load settings':'Carregar configurações',
    'Clear settings':'Apagar configurações',
    'Send settings':'Enviar configurações',
    'Settings sended!':'Configurações enviadas!',
    'For download settings file open':'Para baixar o arquivo de configurações, abra ',
    'and enter code':'e insira o código',
    'or scan':'ou escaneie',
    'Send request':'Enviar o pedido para o servidor',
    'Request sended!':'O pedido foi enviado!',
    'For upload settings file open':'Para carregar o arquivo de configurações, abra',
    'Enter Provider Code':'Entre com o código do provedor',
    'Error Code!':'Código inválido!!!',
    'For enter value open':'Para digitar o valor, abra',
    'First Run Setup':'Configuração inicial',
    'Enter Provider Code on PC or Phone':'Digite o código do provedor no seu PC ou Smartphone',
    'Manual setup':'Configuração manual',
    'Access settings':'Configuracão de acesso',
// 26.1
    'Script':'Roteiro',
    'Producer':'Produtor',
    'Operator':'Operador',
    'Composer':'Compositor',
    'Artist':'Artista',
    'Installation':'Pós Produção',
    'Budget':'Orçamento',
    'Audience':'Audiência',
    'Premiere world':'Estréia mundial',
    'Display settings':'Configurações de tela',
    'Age':'Idade',
    'Sort':'Ordenar',
    'by name':'por nome',
    'by adding':'Por ordem de adição',
    'Order':'Ordem',
    'asc':'Crescente',
    'desc':'Decrescente',
    'Language':'Idioma',
    'Quality':'Qualidade',
    'Show program name':'Mostrar o nome do programa',
    'Show description':'Mostrar a descrição do programa',
    'transparent':'transparente',
}
