keyStrings = {
    'lang':'Română',
    'alhabet':'aăâbcdefghiîjklmnopqrsștțuvwxyz',
    'Channel list. Category: ':'Lista canalelor. Categoria: ',
    'EPG':'Programa',
    'Category':'Categorii',
    'Actions':'Acțiune',
    'Description':'Descriere',
    'Open in PiP':'Deschide în PiP',
    'Move channel up':'Mută canalul mai sus',
    'Move channel down':'Mută canalul mai jos',
    'Delete channel':'Șterge canalul',
    'Add channel to category':'Adaugă canalul în categoria',
    'Add channel to favorites':'Adaugă canalul în favorite',
    'Channel parental control':'Canal control parental',
    'Channel is not available!!!':'Canalul nu este disponibil!!!',
    'min':'minute',
    'Channel ':'Canal ',
    ' added to category ':' adăugat în categoria ',
    ' added to favorites':' adăugat în favorite',
    'Favorites':'Favorite',
    'Select category to add channel':'Selectează categoria pentru a adăuga canalul',
    'Enter parental code':'Introduceți codul parental',
    'Wrong parental code !!!':'Cod parental greșit !!!',
    '<br>Up<br>':'<br>Sus<br>',
    '<br>Delete':'<br>Șterge',
    '<br>Add<br>to favorites':'<br>Adaugă<br>în favorite',
    '<br>Add<br>to category':'<br>Adaugă<br>în categoria',
    '<br>Parental<br>Control':'Control <br>Parental<br>',
    '<br>Down':'<br>În jos',
    'Close':'Închide',
    'Edit category name':'Editare nume categorie',
    'Category %1 already exists!':'Categoria %1 există!',
    'Enter name for new category':'Introduceți numele categoriei noi',
    '<br>More...<br>':'<br>Mai mult...<br>',
    '<br>Rename':'<br>Redenumiți',
    '<br>Copy<br>category':'<br>Copie<br>categoria',
    '<br>Back<br>':'<br>Înapoi<br>',
    '<br>Create<br>category':'<br>Creați<br>categorie',
    'Category selection':'Selectare categorie',
    'Menu':'Meniu',
    'Channel list':'Lista canalelor',
    'Move category up':'Mută ​​categoria în sus',
    'Move category down':'Mută ​​categoria în jos',
    'Create category':'Crează categorie',
    'Rename category':'Redenumiți categoria',
    'Copy category':'Copie categoria',
    'Delete category':'Șterge categoria',
    'Su Mo Tu We Th Fr Sa':'Dum Lun Mar Mie Joi Vin Sâm',
    'EPG and archive. Channel: ':'Program și arhiv. Canal: ',
    'By alphabet':'După alfabet',
    'Archive. Channel: ':'Arhiv. Canal: ',
    'By time':'După timp',
    'Player info:':'Info player:',
    'Device info:':'Info device:',
    '- switch:':'- comutare:',
    '- erase':'- șterge',
    '- move cursor':'- mișcare cursor',
    '- return without save':'- înapoi fără a salva',
    '- save':'- salvează',
    'Return to previous channel':'Revenire la canalul anterior',
    'Call PiP / PiP exchange':'Apel PiP / Schimbă sursa PiP',
    'Info about TV program':'Info TV program',
    'Show player menu':'Afișează meniu player',
    'Interface settings':'Setări interfață',
    'Show channel selection list':'Afișează lista de selecție a canalelor',
    'Hide / Return':'Ascunde / Întoarce',
    'Exit player':'Ieșire din player',
    'Show EPG and archive for channel':'Afișare program și arhiva canalului',
    'Channel category selection':'Selectare categorie canal',
    'Toggle Aspect Ratio':'Comutare ”Raport aspect ecran” (Aspect Ratio)',
    'Toggle Zoom Mode':'Mod Zoom',
    'Switch sound track':'Schimbare track audio',
    'In live mode: <br/>':'Regim în direct:<br/>',
    'Channel selection by number':'Alege canalul după număr',
    'Timeshift: to start of TV program':'Timeshift: la începutul programului',
    'Timeshift: one minute back':'Timeshift: cu un minut în urmă',
    '<br/><br/>In archive mode:<br/>':'<br/><br/>În regim vizualizare arhivă:<br/>',
    'Pause/Play':'Pauză/Play',
    'Stop playback and return to In live mode':'Oprire redarea arhivei și revinere în direct',
    'To start of TV program / Previous TV program':'La începutul programului / Programul precedent',
    'Next TV program':'Programul urmator',
    'Back / Forward for 1 minute':'Înapoi / Înainte cu 1 minută',
    'Back / Forward for 15 seconds':'Înapoi / Înainte cu 15 minute',
    'Back / Forward for 3 minutes':'Înapoi / Înainte cu 3 minute',
    'Back / Forward for 10 minutes':'Înapoi / Înainte cu 10 minute',
    'Show rewind window':'Afișare fereastră de derulare',
    'Description of remote control buttons':'Descrierea butoanelor telecomenzii',
    'Description of remote control buttons depending on the view mode':'Descrierea butoanelor telecomenzii în funcție de modul de vizualizare',
    'Set parental code':'Introdu cod parental',
    'Repeat parental code':'Repetă cod parental',
    'Show list of channel archive records':'Afișare lista înregistrărilor din arhiva canalului',
    'Show list of channel archive records without duplication':'Afișare lista arhivă înregistrări a canalului fără repetare',
    'Show Media Library':'Afișare biblioteca media',
    'Rewind':'Derulare',
    'Close PiP':'Închide PiP',
    'Parental control':'Control parental',
    'Change provider':'Schimbare furnizor',
    'Change provider - you can change the provider, and it will be remembered at the next start of player!':'Schimbare furnizor - Puteți schimba furnizorul și va fi reținut data viitoare când porniți playerul!',
    'Restart player':'Restart player',
    // 'Restart player - after changing provider settings (as example)':'Restart player - ex. după modificarea setărilor furnizorului',
    'Description of remote control buttons':'Descriere butoane telecomandă',
    'About':'Despre',
    'Player and device info':'Informații despre player și dispozitiv',
    'Donate <div class="btn" style="background-color:orange;">donate</div>':'Suport pentru proiect <div class="btn" style="background-color:orange;">donează</div>',
    'Voluntary donation for the development of project':'Donează pentru dezvoltarea proiectului',
    'Settings saved':'Setări salvate',
    'no':'nu',
    'yes':'da',
    'Records':'Înregistrări',
    'Previous':'Precedent',
    'Info':'Info',
    'Not reduce video when showing the list (bugfix)':'Nu micșora video când afișez lista (bugfix)',
    'Black screen while switching the channel':'Ecran negru când schimb canalul',
    'PiP window size':'Mărime fereastră PiP',
    'small':'mică',
    'medium':'mediu',
    'large':'mare',
    'PiP window position':'Poziție fereastră PiP',
    'top-right':'sus-dreapta',
    'bottom-right':'jos-dreapta',
    'left-bottom':'stânga-jos',
    'top-left':'sus-stânga',
    'Number of rows in lists':'Număr rânduri în listă',
    'Distance between lines in lists':'Spațiu între rânduri din listă',
    'Font type':'Tip font',
    'volume':'volum',
    'paging':'paginare',
    'Nothing':'Fără acțiune',
    'Exit':'Ieșire',
    'Joystick':'Joystick',
    'Button %1 function when viewing':'Funcțe buton %1 în regim vizualizăre',
    'Button function %1 when viewing archive':'Funcțe buton %1 în regim vizualizăre arhivă',
    'Channels':'Canale',
    'Remote (color buttons N/A)':'Telecomanda fără butoane colore',
    'Remote (number buttons N/A)':'Telecomanda fără butoane numerice',
    'Timezone':'Fus orar',
    'Sleep timer':'Timer somn',
    'off':'oprit',
    '30 minutes':'30 minute',
    '1 hour':'1 oră',
    '2 hours':'2 ore',
    'Infobar display timeout, s':'Timp afișare bara de informație, s',
    '"Sliding" infobar':'"Afișare" bara de informație',
    'Interface transparency':'Transparență interfață',
    'Volume step, %':'Pas volum, %',
    'List location':'Poziție listă',
    'right':'în dreapta',
    'left':'în stânga',
    'Color spectrum':'Spectrul de culori',
    'select':'selectează',
    'Permanent clock on screen':'Ceas permanent pe ecran',
    'Show channel number in list':'Afișare număr canal în listă',
    'Show picons in channel list':'Afișare pictograme în lista de canale',
    'Show channel name in list':'Afișare nume canal în listă',
    'Show progress in channel list':'Afișare progres în lista canal',
    'Show archive availability in list':'Afișare disponibilitate arhivă în listă',
    'Show scrollbar in list':'Afișare bară de derulare în listă',
    'Preview in channel list':'Previzualizare lista canale',
    'always':'mereu',
    'on ':'pe ',
    'Number of next TV programs in channel list':'Nr. programe în lista de canale',
    'Channel list editing style':'Stil de editare a listei, categorii',
    'All categories':'Toate',
    '"Favorites"':'"Favorite"',
    'Editor':'Redactor',
    'built-in':'integrat',
    'native':'nativ',
    'HDMI-CEC support (on/off from TV)':'HDMI-СEC suport (on/off de la TV)',
    'Type of player for streaming':'Tip player pentru flux',
    'Autostart of player':'Autostart player',
    'Buffer Size, s':'Mărime buffer, s',
    'Choose from':'Selectare',
    'Settings':'Setări',
    'Change value':'Schimbă valoarea',
    'Save Settings':'Salvare setări',
    'To begining':'La inceput',
    'Live':'În direct',
    ' m ':' min ',
    ' s':' sec',
    '1 minute':'1 minută',
    '10 Seconds':'10 secunde',
    'Go to':'Treci la',
    'Archive - begin':'Arhiv - start program',
    'Pause':'Pauză',
    'Play':'Play',
    'Shutdown after %1 seconds<br/><br/>Cancel - any action':'Închide peste %1 secunde<br/><br/>Renunță - oricare acțiune',
    'Do you want to exit player?':'Ieșire din player?',
    'Color':'Culoare',
    'Saturation':'Saturare',
    'Yellow':'Galben',
    'Green':'Verde',
    'Blue':'Albastru',
    'Set':'Memorează',
    'Restart stream':'Restart flux',
    'Favorites':'Favorite',
    'All':'Toate',
    '<br/>Processing the channel list...':'<br/>Procesare lista canale...',
    '<br/>Start playback...':'<br/>Start vizualizare...',
    '<br/>Channel list not received !!!':'<br/>Lista canalelor nu a fost primită !!!',
    'Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>':'Lista canalelor nu a fost primită !!!<br/><br/>Introduceți datele furnizorului și restartați playerul !!!<br/><br/>',
    'Error getting channel list !!!':'Eroare obținere listă canale !!!',
    'system':'de sistem',
    'Choose provider':'Selectare furnizor',
    '<br>Rewind<br>':'<br>Derulare<br>',
    '<br>Menu':'<br>Meniu',
    '<br>Pause<br>':'<br>Pauză<br>',
    '<br>Toggle<br>sound track':'<br>Schimbă<br>audio track',
    '<br>Live':'<br>În direct',
    '<br>Previous<br>channel':'<br>Canan<br>precedent',
    '<br/><b>Failed to load provider script !!!</b>':'<br/><b>Nu s-a încărcat scriptul furnizorului !!!</b>',
    '<br/>Loading provider %1 script ...':'<br/>Încărcare script furnizorul %1 ...',
    '<br/>Loading settings...':'<br/>Încarcă setări...',
    '<br/>Loading channel list...':'<br/>Încarcare listă canale...',
    'Choose language':'Selectează limba',
    'Change interface language':'Schimbare limbă interfață',
    'Aspect':'Aspect',
    'Audio':'Audio track',
    'Stalker portals':'Stalker portal',
    'm3u-m3u8 playlists':'m3u-m3u8 pleylista',
    '<br/>Loading STB...':'<br/>Încarcare STB...',
    '<br/>Setup STB...':'<br/>Setări STB...',
    'Save settings to storage':'Salvare setări pe stick',
    'Load settings from storage':'Restabilire setări de pe stick',
    'Download':'Copie',
    'Skip this version':'Omite această versiune',
    'Volume control':'Volum control',
    'Long button presses':'Apăsare continuă a butonului',
    'Download new version Android App':'Copie versiune nouă aplicatie Android',
    'To access you must enter url, username and password!':'Pentru a accesa introduceți adresa URL, loghin si parola!',
    'Failed to load channel list!':'Nu s-a încărcat lista cu canale!',
    'Year':'An',
    'Duration':'Durata filmului',
    'Genre':'Gen',
    'Country':'Țara',
    'Director':'Regia',
    'Actors':'În roluri',
    'Release date':'Data premierei',
    'Rating':'Reiting',
    'Season':'Sezon',
    'Episodes':'Epizoade',
    'VOD':'Filme și video',
    'TV series':'Seriale',
    'Episode':'Epizod',
    'Download! Wait ...':'Încarcare! Așteptați ...',
    'Server':'Server',
    'URL':'Adresa URL',
    'Username':'Loghin',
    'Password':'Parola',
    'Stream type':'Tip flux',
    'Account info':'Infomație acaunt',
    'Select server number from 1 to 6 to save data':'Alegeți numărul serverului de la 1 până la 6 salvarea datelor',
    ' (after changing, restart player)':' (restart player după schimbare)',
    ' (after changing, switch the channel!)':' (dupa schimbare treceți la alt canal!)',
    'Enter URL of server':'Introduce URL server',
    'Enter username':'Introduce loghin',
    'Enter password':'Introduce parola',
    'Select stream type':'Alege tipul fluxului',
    '??? No channel name':'??? Canal fără nume',
    'Playlist URL':'URL playlist',
    'Archive hours':'Nr. ore arhivă',
    'Enter playlist URL':'Introduceți URL playlist',
    'Enter playlist archive hours':'Introduceți nr. ore de arhivă pentru playlist',
    'show on-screen keyboard':'afișează tastatura pe ecran',
    'Sleep without leaving player':'Hibernare fără a părăsi playerul',
    'PiP is not available!':'PiP nu e disponibil!',
    'NORMAL':'NORMAL',
    'ENLARGE':'MĂREȘTE',
    'MAKE_WIDER':'MĂREȘTE LĂȚIMEA',
    'NON_LINEAR_STRETCH':'ÎNTINDERE NELINIARĂ',
    'NON_LINEAR_STRETCH_TO_FULL_SCREEN':'ÎNTINDERE NELINIARĂ PENTRU ECRANUL COMPLET',
    'MAKE_TALLER':'MĂREȘTE ÎNĂLȚIMEA',
    'CUT_EDGES':'TĂIERE MUCHII',
    'FULL_SCREEN':'TOT ECRANUL',
    'STRETCH_TO_FULL_SCREEN':'EXTINDE TOT ECRANUL',
    'Background color':'Culoare de fundal',
    'Brightness':'Luminozitatea',
    '3 hours':'3 ore',
    'Restart stream / Live':'Restart flux / În direct',
    '- keyboard': '- tastatura',
    'Media':'Bibliotecii media',
    'String for search':'Caseta pentru căutare',
    'Playlist Name':'Nume playlist',
    'Enter playlist Name':'Introduce nume playlist',
    'Media Library URL':'Adresa URL a bibliotecii media',
    'Enter Media Library URL':'Introduceți adresa URL a bibliotecii media',
    'Playlist':'Playlist',
    'Select playlist':'Selectare playlist',
    'Edit':'Editare',
    'Load':'Incarcă',
    'Edit playlist data':'Editare date playlist',
    'Select portal':'Selectare portal',
    'Portal Name':'Nume portal',
    'Enter Portal Name':'Introduce nume portal',
    'Edit portal data':'Editare date portal',
    'without':'fără',
    'Settings STB':'Setări dispozitiv',
    'Soft audio render':'Software audio decodare',
    'Long press horizontal arrows for volume control':'Țineți apăsat săgețile orizontale pentru controlul volumului',
    'Yes':'Da',
    'Back':'Înapoi',
    'Show providers?':'Afișați furnizorii?',
    'Hide providers?':'Ascundeți furnizorii?',
    'Show provider settings?':'Afișează setări furnizori?',
    'Hide provider settings?':'Ascunde setări furnizori?',
    'Clear all settings?':'Resetare setări?',
    'Timer':'Timer',
    'Set timer?':'Setare timer?',
    'Remove timer?':'Șterge timer?',
    'Timer: switch to channel?':'Timer: schimbă pe canalul?',
    ' (if archive exists)':' (dacă există arhiva)',
    'Preffered audio track':'Track audio preferat',
    'Information':'Informație',
    'Lists settings':'Setări liste',
    'Channel list settings':'Setări lista canale',
    'Buttons settings':'Setări butoane telecomandă',
    'Subtitle':'subtitrare',
    'Switch subtitle':'Schimbare subtitrare',
    'Off':'Oprit',
    'Not found':'Nu a fost găsit',
    'History of watched movies':'Istoria filmelor vizionate',
    'Continue watching?':'Continuați să vizionați?',
    'Add to favorites':'Adaugă în favorit',
    'Delete':'Șterge',
    'Info about current stream':'Info despre fluxul curent',
    'Stop':'Stop',
    'Playlist file':'Fișier playlist',
    'Select playlist file':'Selectare fișier playlist',
    'Graphical indication':'Indicație grafică',
    'Background color of selected item':'Culoare fundal pentru selecție',
    'Default':'Implicit',
    'Not supported!':'Nu e suportat!',
    'Menu items settings':'Setări elemente meniu',
    'Select menu items':'Selectare elemente meniu',
    'Protect Adult Channels':'Protecție canale ”Adult”',
    'Protect Settings':'Protecție setări',
    'Protect Change Provider':'Protecție schimbare furnizor',
    'Infobar settings':'Setări bara de informații',
    'Show when switching':'Afișare când schimbați',
    'Show when changing program':'Afișare când schimbați programul',
    'Show when rewind':'Afișare la derulare',
    'Archive. Category: ':'Arhiva. Categoria: ',
    'Sort channels':'Sortare canale',
    '"As Is"':'"Așa cum este"',
    'Load playlist':'Încărcați playlista',
    ' (after changing, load playlist)':' (după modificare, încărcați pleylista)',
    'Statistics of current stream':'Statistica fluxului curent',
    'Search':'Caută',
// 14.6
    'Behavior of %1/%2 buttons in lists':'Funcție butoane %1/%2 în liste',
    'begin/end':'început/sfârșit',
    'Position shift -10 seconds after pause':'Schimbare poziție cu -10 secunde după pauză',
    'Remember previous channels':'Memorare canalele precedente',
    'History in Media Library':'Istoria vizionării în biblioteca media',
// 5.11
    'Manage settings':'Gestionare setări',
    'Save settings':'Salvare setări',
    'Load settings':'Încărcare setări',
    'Clear settings':'Ștergeți setările',
    'Send settings':'Trimite setările pe server',
    'Settings sended!':'Setările au fost trimise la server!',
    'For download settings file open':'Pentru a descărca fișierul cu setări deschideți',
    'and enter code':'și introduceți codul',
    'or scan':'sau scanați',
    'Send request':'Trimitere cerere către server',
    'Request sended!':'Cererea a fost trimisă la server!',
    'For upload settings file open':'Pentru a încărca fișierul cu setări deschideți',
    'Enter Provider Code':'Introduceți codul furnizorului',
    'Error Code!':'Eroare cod!!!',
    'For enter value open':'Pentru a introduce valoarea, deschideți',
    'First Run Setup':'Configurare pentru prima dată',
    'Enter Provider Code on PC or Phone':'Introduceți codul furnizorului la calculator sau la telefon',
    'Manual setup':'Setare manuală',
    'Access settings':'Setări acces',
// 26.1
    'Script':'Scenariu',
    'Producer':'Producător',
    'Operator':'Operator',
    'Composer':'Compozitor',
    'Artist':'Artist',
    'Installation':'Montaj',
    'Budget':'Buget',
    'Audience':'Publicul',
    'Premiere world':'Premieră mondială',
    'Display settings':'Setări de afișare',
    'Age':'Vârsta',
    'Sort':'Sortare',
    'by name':'după nume',
    'by adding':'după adăugare',
    'Order':'Ordonare',
    'asc':'crescător',
    'desc':'descrescător',
    'Language':'Limba',
    'Quality':'Calitate',
    'Show program name':'Afișează nume program',
    'Show description':'Afișează descrierea',
    'transparent':'transparent',
// 23.3
    'Rewind step by buttons %1/%2':'Pas derulare butoane %1/%2',
// 10.2
    'Show thumbnails':'Afișare miniaturi',
}
