keyStrings = {
    'lang':'Русский',
    'alhabet':'абвгдеёжзийклмнопрстуфхцчшщъыьэюя',
    'Channel list. Category: ':'Список каналов. Категория: ',
    'EPG':'Программа',
    'Category':'Категории',
    'Actions':'Действия',
    'Description':'Описание',
    'Open in PiP':'Открыть в PiP',
    'Move channel up':'Передвинуть канал вверх',
    'Move channel down':'Передвинуть канал вниз',
    'Delete channel':'Удалить канал',
    'Add channel to category':'Добавить канал в категорию',
    'Add channel to favorites':'Добавить канал в избранные',
    'Channel parental control':'Родительский контроль канала',
    'Channel is not available!!!':'Канал не доступен!!!',
    'min':'минут',
    'Channel ':'Канал ',
    ' added to category ':' добавлен в категорию ',
    ' added to favorites':' добавлен в избранные',
    'Favorites':'Избранные',
    'Select category to add channel':'Выбор категории для добавления канала',
    'Enter parental code':'Введите родительский код',
    'Wrong parental code !!!':'Неверный родительский код !!!',
    '<br>Up<br>':'<br>Вверх<br>',
    '<br>Delete':'<br>Удалить',
    '<br>Add<br>to favorites':'<br>Добавить<br>в избранные',
    '<br>Add<br>to category':'<br>Добавить<br>в категорию',
    '<br>Parental<br>Control':'<br>Родительский<br>контроль',
    '<br>Down':'<br>Вниз',
    'Close':'Закрыть',
    'Edit category name':'Редактирование названия категории',
    'Category %1 already exists!':'Категория %1 уже существует!',
    'Enter name for new category':'Введите название для новой категории',
    '<br>More...<br>':'<br>Еще...<br>',
    '<br>Rename':'<br>Переименовать',
    '<br>Copy<br>category':'<br>Копировать<br>категорию',
    '<br>Back<br>':'<br>Назад<br>',
    '<br>Create<br>category':'<br>Создать<br>категорию',
    'Category selection':'Выбор категории каналов',
    'Menu':'Меню',
    'Channel list':'Список каналов',
    'Move category up':'Передвинуть категорию вверх',
    'Move category down':'Передвинуть категорию вниз',
    'Create category':'Создать категорию',
    'Rename category':'Переименовать категорию',
    'Copy category':'Копировать категорию',
    'Delete category':'Удалить категорию',
    'Su Mo Tu We Th Fr Sa':'Вс Пн Вт Ср Чт Пт Сб',
    'EPG and archive. Channel: ':'Программа и архив. Канал: ',
    'By alphabet':'По алфавиту',
    'Archive. Channel: ':'Архив. Канал: ',
    'By time':'По времени',
    'Player info:':'Информация о плеере:',
    'Device info:':'Информация об устройстве:',
    '- switch:':'- переключение:',
    '- erase':'- стереть',
    '- move cursor':'- перемещение курсора',
    '- return without save':'- вернуться без сохранения',
    '- save':'- запомнить',
    'Return to previous channel':'Возврат к предыдущему каналу',
    'Call PiP / PiP exchange':'Вызов PiP / Обмен источниками PiP',
    'Info about TV program':'Вызов информации о передаче',
    'Show player menu':'Вызов меню плеера',
    'Interface settings':'Настройки интерфейса',
    'Show channel selection list':'Вызов списка выбора канала',
    'Hide / Return':'Убрать информацию / возврат',
    'Exit player':'Выход из плеера',
    'Show EPG and archive for channel':'Вызов программы передач и архива канала',
    'Channel category selection':'Выбор категории каналов',
    'Toggle Aspect Ratio':'Переключить режим "Соотношение сторон экрана" (Aspect Ratio)',
    'Toggle Zoom Mode':'Переключить режим увеличения',
    'Switch sound track':'Переключить дорожку звука',
    'In live mode: <br/>':'В режиме просмотра прямого эфира:<br/>',
    'Channel selection by number':'Выбор канала по номеру',
    'Timeshift: to start of TV program':'Таймшифт: в начало передачи',
    'Timeshift: one minute back':'Таймшифт: на минуту назад',
    '<br/><br/>In archive mode:<br/>':'<br/><br/>В режиме просмотра архива:<br/>',
    'Pause/Play':'Пауза/Воспроизведение',
    'Stop playback and return to In live mode':'Остановить воспроизведение и вернуться к прямому эфиру',
    'To start of TV program / Previous TV program':'В начало передачи / На предыдущуюю передачу',
    'Next TV program':'На следующую передачу',
    'Back / Forward for 1 minute':'Назад / Вперед на 1 минуту',
    'Back / Forward for 15 seconds':'Назад / Вперед на 15 секунд',
    'Back / Forward for 3 minutes':'Назад / Вперед на 3 минуты',
    'Back / Forward for 10 minutes':'Назад / Вперед на 10 минут',
    'Show rewind window':'Вызов окошка перемотки',
    'Description of remote control buttons':'Описание функций кнопок пульта',
    'Description of remote control buttons depending on the view mode':'Описание функций кнопок пульта, зависящих от режима просмотра',
    'Set parental code':'Задайте родительский код',
    'Repeat parental code':'Повторите родительский код',
    'Show list of channel archive records':'Вызов списка записей архива канала',
    'Show list of channel archive records without duplication':'Вызов списка записей архива канала без повторений',
    'Show Media Library':'Вызов медиатеки',
    'Rewind':'Перемотка',
    'Close PiP':'Закрыть PiP',
    'Parental control':'Родительский контроль',
    'Change provider':'Смена провайдера',
    'Change provider - you can change the provider, and it will be remembered at the next start of player!':'Смена провайдера - Вы можете сменить провайдера, и он запомнится при следующем запуске!',
    'Restart player':'Перезапустить плеер',
    // 'Restart player - after changing provider settings (as example)':'Перезапустить плеер - например после смены настроек провайдера',
    'Description of remote control buttons':'Описание кнопок пульта',
    'About':'Информация',
    'Player and device info':'Информация о плеере и устройстве',
    'Donate <div class="btn" style="background-color:orange;">donate</div>':'Помощь проекту <div class="btn" style="background-color:orange;">donate</div>',
    'Voluntary donation for the development of project':'Добровольная помощь на развитие проекта',
    'Settings saved':'Настройки сохранены',
    'no':'нет',
    'yes':'да',
    'Records':'Записи',
    'Previous':'Предыдущий',
    'Info':'Инфо',
    'Not reduce video when showing the list (bugfix)':'Не уменьшать видео при вызове списка (bugfix)',
    'Black screen while switching the channel':'Черный экран при переключении канала',
    'PiP window size':'Размер окошка PiP',
    'small':'маленькое',
    'medium':'среднее',
    'large':'большое',
    'PiP window position':'Положение окошка PiP',
    'top-right':'право-верх',
    'bottom-right':'право-низ',
    'left-bottom':'лево-низ',
    'top-left':'лево-верх',
    'Number of rows in lists':'Количество строк в списках',
    'Distance between lines in lists':'Расстояние между строк в списках',
    'Font type':'Тип шрифта',
    'volume':'громкость',
    'paging':'листание',
    'Nothing':'Ничего',
    'Exit':'Выход',
    'Joystick':'Джойстик',
    'Button %1 function when viewing':'Функция кнопки %1 при просмотре',
    'Button function %1 when viewing archive':'Функция кнопки %1 при просмотре архива',
    'Channels':'Каналы',
    'Remote (color buttons N/A)':'Пульт без цветных кнопок',
    'Remote (number buttons N/A)':'Пульт без цифровых кнопок',
    'Timezone':'Часовой пояс',
    'Sleep timer':'Таймер сна',
    'off':'отключен',
    '30 minutes':'30 минут',
    '1 hour':'1 час',
    '2 hours':'2 часа',
    'Infobar display timeout, s':'Таймаут показа инфобара, с',
    '"Sliding" infobar':'"Выезжающий" инфобар',
    'Interface transparency':'Прозрачность интерфейса',
    'Volume step, %':'Шаг громкости, %',
    'List location':'Расположение списка',
    'right':'справа',
    'left':'слева',
    'Color spectrum':'Цветовая гамма',
    'select':'выберите',
    'Permanent clock on screen':'Постоянные часы на экране',
    'Show channel number in list':'Показ номера канала в списке',
    'Show picons in channel list':'Показ пиконов в списке каналов',
    'Show channel name in list':'Показ названия канала в списке',
    'Show progress in channel list':'Показ прогресса в списке каналов',
    'Show archive availability in list':'Показ наличия архива в списке',
    'Show scrollbar in list':'Показ скроллбара в списке',
    'Preview in channel list':'Превью в списке каналов',
    'always':'всегда',
    'on ':'по ',
    'Number of next TV programs in channel list':'К-во следующих передач в списке каналов',
    'Channel list editing style':'Стиль редактирования списков',
    'All categories':'Все категории',
    '"Favorites"':'"Избранное"',
    'Editor':'Редактор',
    'built-in':'встроенный',
    'native':'родной',
    'HDMI-CEC support (on/off from TV)':'HDMI-СEC поддержка (вкл/выкл от ТВ)',
    'Type of player for streaming':'Тип плеера для воспроизведения',
    'Autostart of player':'Старт плеера при включении',
    'Buffer Size, s':'Размер буфера, с',
    'Choose from':'Варианты',
    'Settings':'Настройки',
    'Change value':'Смена значения',
    'Save Settings':'Сохранить настройки',
    'To begining':'В начало',
    'Live':'Прямая трансляция',
    ' m ':' мин ',
    ' s':' сек',
    '1 minute':'1 минута',
    '10 Seconds':'10 секунд',
    'Go to':'Перейти',
    'Archive - begin':'Архив - начало передачи',
    'Pause':'Пауза',
    'Play':'Воспроизведение',
    'Shutdown after %1 seconds<br/><br/>Cancel - any action':'Выключение через %1 секунд<br/><br/>Отмена - любое действие',
    'Do you want to exit player?':'Вы хотите выйти из плеера?',
    'Color':'Цвет',
    'Saturation':'Насыщенность',
    'Yellow':'Желтый',
    'Green':'Зеленый',
    'Blue':'Голубой',
    'Set':'Установить',
    'Restart stream':'Рестарт потока',
    'Favorites':'Избранные',
    'All':'Все',
    '<br/>Processing the channel list...':'<br/>Обработка списка каналов...',
    '<br/>Start playback...':'<br/>Старт воспроизведения...',
    '<br/>Channel list not received !!!':'<br/>Не получен список каналов!!!',
    'Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>':'Не получен список каналов!!!<br/><br/>Введите данные провайдера и перезапустите плеер!!!<br/><br/>',
    'Error getting channel list !!!':'Ошибка получения списка каналов!!!',
    'system':'системный',
    'Choose provider':'Выберите провайдера',
    '<br>Rewind<br>':'<br>Перемотка<br>',
    '<br>Menu':'<br>Меню',
    '<br>Pause<br>':'<br>Пауза<br>',
    '<br>Toggle<br>sound track':'<br>Переключить<br>зв.дорожку',
    '<br>Live':'<br>Прямой эфир',
    '<br>Previous<br>channel':'<br>Предыдущий<br>канал',
    '<br/><b>Failed to load provider script !!!</b>':'<br/><b>Не удалось загрузить скрипт провайдера!!!</b>',
    '<br/>Loading provider %1 script ...':'<br/>Загрузка скрипта провайдера %1 ...',
    '<br/>Loading settings...':'<br/>Загрузка настроек...',
    '<br/>Loading channel list...':'<br/>Загрузка списка каналов...',
    'Choose language':'Выберите язык',
    'Change interface language':'Смена языка интерфейса',
    'Aspect':'Аспект',
    'Audio':'Зв.дорожка',
    'Stalker portals':'Сталкер порталы',
    'm3u-m3u8 playlists':'m3u-m3u8 плейлисты',
    '<br/>Loading STB...':'<br/>Загрузка STB...',
    '<br/>Setup STB...':'<br/>Настройка STB...',
    'Save settings to storage':'Записать настройки на флешку',
    'Load settings from storage':'Восстановить настройки с флешки',
    'Download':'Скачать',
    'Skip this version':'Пропустить эту версию',
    'Volume control':'Регулировка громкости',
    'Long button presses':'Долгие нажатия кнопок',
    'Download new version Android App':'Скачать новую версию оболочки',
    'To access you must enter url, username and password!':'Для доступа необходимо ввести адрес, логин и пароль!',
    'Failed to load channel list!':'Не удалось загрузить список каналов!',
    'Year':'Год',
    'Duration':'Продолжительность',
    'Genre':'Жанр',
    'Country':'Страна',
    'Director':'Режиссер',
    'Actors':'В ролях',
    'Release date':'Дата выхода',
    'Rating':'Рейтинг',
    'Season':'Сезон',
    'Episodes':'К-во эпизодов',
    'VOD':'Фильмы и видео',
    'TV series':'Сериалы',
    'Episode':'Эпизод',
    'Download! Wait ...':'Загрузка! Подождите ...',
    'Server':'Сервер',
    'URL':'Адрес',
    'Username':'Логин',
    'Password':'Пароль',
    'Stream type':'Тип потоков',
    'Account info':'Информация о подписке',
    'Select server number from 1 to 6 to save data':'Выберите номер сервера от 1 до 6 для сохранения данных',
    ' (after changing, restart player)':' (после изменения нужно перезапустить плеер)',
    ' (after changing, switch the channel!)':' (после изменения переключите канал!)',
    'Enter URL of server':'Редактирование адреса сервера',
    'Enter username':'Редактирование логина',
    'Enter password':'Редактирование пароля',
    'Select stream type':'Выберите тип потоков',
    '??? No channel name':'??? Нет названия канала',
    'Playlist URL':'Адрес плейлиста',
    'Archive hours':'Количество часов архива',
    'Enter playlist URL':'Ввод адреса плейлиста',
    'Enter playlist archive hours':'Ввод количества часов архива для плейлиста',
    'show on-screen keyboard':'вызвать экранную клавиатуру',
    'Sleep without leaving player':'Заснуть не выходя из плеера',
    'PiP is not available!':'PiP не доступен!',
    'NORMAL':'ОБЫЧНЫЙ',
    'ENLARGE':'УВЕЛИЧЕНИЕ',
    'MAKE_WIDER':'УВЕЛИЧЕНИЕ ШИРИНЫ',
    'NON_LINEAR_STRETCH':'НЕЛИНЕЙНОЕ РАСТЯЖЕНИЕ',
    'NON_LINEAR_STRETCH_TO_FULL_SCREEN':'НЕЛИНЕЙНОЕ РАСТЯЖЕНИЕ НА ВЕСЬ ЭКРАН',
    'MAKE_TALLER':'УВЕЛИЧЕНИЕ ВЫСОТЫ',
    'CUT_EDGES':'ОБРЕЗКА КРАЕВ',
    'FULL_SCREEN':'ПОЛНЫЙ ЭКРАН',
    'STRETCH_TO_FULL_SCREEN':'РАСТЯЖЕНИЕ НА ВЕСЬ ЭКРАН',
    'Background color':'Цвет фона',
    'Brightness':'Яркость',
    '3 hours':'3 часа',
    'Restart stream / Live':'Рестарт потока / Прямая трансляция',
    '- keyboard': '- клавиатура',
    'Media':'Медиатека',
    'String for search':'Строка для поиска',
    'Playlist Name':'Название плейлиста',
    'Enter playlist Name':'Ввод названия плейлиста',
    'Media Library URL':'Адрес медиатеки',
    'Enter Media Library URL':'Ввод адреса медиатеки',
    'Playlist':'Плейлист',
    'Select playlist':'Выберите плейлист',
    'Edit':'Редактировать',
    'Load':'Загрузить',
    'Edit playlist data':'Редактирование данных плейлиста',
    'Select portal':'Выберите портал',
    'Portal Name':'Название портала',
    'Enter Portal Name':'Ввод названия портала',
    'Edit portal data':'Редактирование данных портала',
    'without':'без',
    'Settings STB':'Настройки устройства',
    'Soft audio render':'Программно декодировать звук',
    'Long press horizontal arrows for volume control':'Управление громкостью удержанием гор.стрелок',
    'Yes':'Да',
    'Back':'Назад',
    'Show providers?':'Показать выбор провайдеров?',
    'Hide providers?':'Скрыть выбор провайдеров?',
    'Show provider settings?':'Показать настройки провайдера?',
    'Hide provider settings?':'Скрыть настройки провайдера?',
    'Clear all settings?':'Очистить все настройки?',
    'Timer':'Таймер',
    'Set timer?':'Установить таймер?',
    'Remove timer?':'Удалить таймер?',
    'Timer: switch to channel?':'Таймер: переключиться на канал?',
    ' (if archive exists)':' (при наличии архива канала)',
    'Preffered audio track':'Предпочтительная звуковая дорожка',
    'Information':'Информация',
    'Lists settings':'Настройки списков',
    'Channel list settings':'Настройки списка каналов',
    'Buttons settings':'Настройки кнопок пульта',
    'Subtitle':'Субтитры',
    'Switch subtitle':'Переключить субтитры',
    'Off':'Выключить',
    'Not found':'Отсутствуют',
    'History of watched movies':'История просмотров',
    'Continue watching?':'Продолжить просмотр?',
    'Add to favorites':'Добавить в избранное',
    'Delete':'Удалить',
    'Info about current stream':'Информация о текущем потоке',
    'Stop':'Стоп',
    'Playlist file':'Файл плейлиста',
    'Select playlist file':'Выбор файла плейлиста',
    'Graphical indication':'Графическая индикация',
    'Background color of selected item':'Цвет фона выделения',
    'Default':'По умолчанию',
    'Not supported!':'Не поддерживается!',
    'Menu items settings':'Настройка пунктов меню',
    'Select menu items':'Выберите пункты меню',
    'Protect Adult Channels':'Защита "взрослых" каналов',
    'Protect Settings':'Защита настроек',
    'Protect Change Provider':'Защита смены провайдера',
    'Infobar settings':'Настройки инфобара',
    'Show when switching':'Показать при переключении',
    'Show when changing program':'Показать при смене программы',
    'Show when rewind':'Показать при перемотке',
    'Archive. Category: ':'Архив. Категория: ',
    'Sort channels':'Сортировка',
    '"As Is"':'"Как есть"',
    'Load playlist':'Загрузить плейлист',
    ' (after changing, load playlist)':' (после изменения, загрузить плейлист)',
    'Statistics of current stream':'Статистика текущего потока',
    'Search':'Поиск',
// 14.6
    'Behavior of %1/%2 buttons in lists':'Поведение кнопок %1/%2 в списках',
    'begin/end':'начало/конец',
    'Position shift -10 seconds after pause':'Сдвиг позиции на -10 секунд после паузы',
    'Remember previous channels':'Запоминать предыдущих каналов',
    'History in Media Library':'История просмотров в медиатеке',
// 5.11
    'Manage settings':'Управление настройками',
    'Save settings':'Сохранить настройки',
    'Load settings':'Загрузить настройки',
    'Clear settings':'Очистить настройки',
    'Send settings':'Отправка настроек на сервер',
    'Settings sended!':'Настройки отправлены на сервер!',
    'For download settings file open':'Для скачивания файла настроек откройте',
    'and enter code':'и введите код',
    'or scan':'или отсканируйте',
    'Send request':'Отправка запроса на сервер',
    'Request sended!':'Запрос отправлен на сервер!',
    'For upload settings file open':'Для загрузки файла настроек откройте',
    'Enter Provider Code':'Ввод кода провайдера',
    'Error Code!':'Ошибка кода!!!',
    'For enter value open':'Для ввода значения откройте',
    'First Run Setup':'Настройка при первом запуске',
    'Enter Provider Code on PC or Phone':'Ввод кода провайдера на компьютере или телефоне',
    'Manual setup':'Ручная настройка',
    'Access settings':'Настройки доступа',
// 26.1
    'Script':'Сценарий',
    'Producer':'Продюсер',
    'Operator':'Оператор',
    'Composer':'Композитор',
    'Artist':'Художник',
    'Installation':'Монтаж',
    'Budget':'Бюджет',
    'Audience':'Аудитория',
    'Premiere world':'Мировая премьера',
    'Display settings':'Настройки отображения',
    'Age':'Возраст',
    'Sort':'Сортировка',
    'by name':'по названию',
    'by adding':'по добавлению',
    'Order':'Порядок',
    'asc':'возрастание',
    'desc':'убывание',
    'Language':'Язык',
    'Quality':'Качество',
    'Show program name':'Показ названия передачи',
    'Show description':'Показ описания передачи',
    'transparent':'прозрачные',
// 23.3
    'Rewind step by buttons %1/%2':'Шаг перемотки кнопками %1/%2',
// 10.2
    'Show thumbnails':'Показать миниатюры',
}
