keyStrings = {
    'lang':'Español',
    'alhabet':'ABCDEFGHIJKLMNÑOPQRSTUVWXYZ',
    'Channel list. Category: ':'Lista de Canales. Categoría: ',
    'EPG':'TV Guía',
    'Category':'Categorías',
    'Actions':'Acciones',
    'Description':'Descripción',
    'Open in PiP':'Abrir en PiP',
    'Move channel up':'Mover el canal hacia arriba',
    'Move channel down':'Mover el canal hacia abajo',
    'Delete channel':'Eliminar el canal',
    'Add channel to category':'Añadir el canal a la categoría',
    'Add channel to favorites':'Añadir el canal a Favoritos',
    'Channel parental control':'Control parental para el canal',
    'Channel is not available!!!':'Canal no está disponible!!!',
    'min':'minutos',
    'Channel ':'Canal ',
    ' added to category ':' añadido a la categoría ',
    ' added to favorites':' añadido a Favoritos',
    'Favorites':'Favoritos',
    'Select category to add channel':'Elegir la categoría para añadir el canal',
    'Enter parental code':'Introduzca el código parental',
    'Wrong parental code !!!':'Código parental incorrecto !!!',
    '<br>Up<br>':'<br>Arriba<br>',
    '<br>Delete':'<br>Eliminar',
    '<br>Add<br>to favorites':'<br>Añadir<br>a Favoritos',
    '<br>Add<br>to category':'<br>Añadir<br>a la categoría',
    '<br>Parental<br>Control':'<br>Control<br>parental',
    '<br>Down':'<br>Abajo',
    'Close':'Cerrar',
    'Edit category name':'Editar el nombre de categoría',
    'Category %1 already exists!':'La categoría %1 ya existe!',
    'Enter name for new category':'Entrar el nombre para la nueva categoría',
    '<br>More...<br>':'<br>Más...<br>',
    '<br>Rename':'<br>Cambiar de nombre',
    '<br>Copy<br>category':'<br>Copiar<br>la categoría',
    '<br>Back<br>':'<br>Volver<br>',
    '<br>Create<br>category':'<br>Crear<br>la categoría',
    'Category selection':'Elegir la categoría',
    'Menu':'Menu',
    'Channel list':'Lista de Canales',
    'Move category up':'Mover la categoría hacia arriba',
    'Move category down':'Mover la categoría hacia abajo',
    'Create category':'Crear la categoría',
    'Rename category':'Cambiar el nombre de la categoría',
    'Copy category':'Copiar la categoría',
    'Delete category':'Eliminar la categoría',
    'Su Mo Tu We Th Fr Sa':'Dom Lun Mar Mié Jue Vie Sáb',
    'EPG and archive. Channel: ':'TV Guía y archivo. Canal: ',
    'By alphabet':'Por alfabeto',
    'Archive. Channel: ':'Archivo. Canal: ',
    'By time':'Por tiempo',
    'Player info:':'Información sobre Player:',
    'Device info:':'Información sobre el reproductor:',
    '- switch:':'- cambio:',
    '- erase':'- borrar',
    '- move cursor':'- mover el cursor',
    '- return without save':'- volver sin guardar',
    '- save':'- guardar',
    'Return to previous channel':'Volver al canal previo',
    'Call PiP / PiP exchange':'Llamar a PiP / Intercambio entre fuentes de PiP',
    'Info about TV program':'Información sobre el programa de TV',
    'Show player menu':'Mostrar el menú de Player',
    'Interface settings':'Configuración de interface',
    'Show channel selection list':'Mostrar el listado de elección de canal',
    'Hide / Return':'Retirar la información / Volver',
    'Exit player':'Salir de Player',
    'Show EPG and archive for channel':'Mostrar TV Guía y archivo de canal',
    'Channel category selection':'Elegir la categoría de canales',
    'Toggle Aspect Ratio':'Alternar el modo "Proporcíon de aspecto de la pantalla" (Aspect Ratio)',
    'Toggle Zoom Mode':'Alternar el modo Zoom',
    'Switch sound track':'Alterar la pista de sonido',
    'In live mode: <br/>':'En modo en vivo:<br/>',
    'Channel selection by number':'Elegir el canal por número',
    'Timeshift: to start of TV program':'Timeshift: al comienzo de programa de TV',
    'Timeshift: one minute back':'Timeshift: un minuto atrás',
    '<br/><br/>In archive mode:<br/>':'<br/><br/>En modo de vista de archivo:<br/>',
    'Pause/Play':'Pausa/Reproducción',
    'Stop playback and return to In live mode':'Detener la reproducción y volver al modo en vivo',
    'To start of TV program / Previous TV program':'Al comienzo de programa de TV / Al siguiente programa de TV',
    'Next TV program':'Al siguiente programa de TV',
    'Back / Forward for 1 minute':'Volver / Adelantar a 1 minuto',
    'Back / Forward for 15 seconds':'Volver / Adelantar a 15 segundos',
    'Back / Forward for 3 minutes':'Volver / Adelantar a 3 minutos',
    'Back / Forward for 10 minutes':'Volver / Adelantar a 10 minutos',
    'Show rewind window':'Mostrar la ventanilla de rebobinar',
    'Description of remote control buttons':'Descripción de funciones de botones de control remoto',
    'Description of remote control buttons depending on the view mode':'Descripción de funciones de botones de control remoto que dependen de modo de vista',
    'Set parental code':'Establecer el código paternal',
    'Repeat parental code':'Reiterar el código parental',
    'Show list of channel archive records':'Mostrar la lista de grabaciones de archivo de canal',
    'Show list of channel archive records without duplication':'Mostrar la lista de grabaciones de archivo de canal sin repeticiones',
    'Show Media Library':'Mostrar la Mediateca',
    'Rewind':'Rebobinar',
    'Close PiP':'Cerrar PiP',
    'Parental control':'Control parental',
    'Change provider':'Cambiar de proveedor',
    'Change provider - you can change the provider, and it will be remembered at the next start of player!':'Cambiar de proveedor - Ud. puede cambial al proveedor y la elección será recordada durante la siguente activación de Player!',
    'Restart player':'Reiniciar Player',
    // 'Restart player - after changing provider settings (as example)':'Reiniciar Player - después de cambios de configuraciones de proveedor (por ejemplo)',
    'Description of remote control buttons':'Descripción de botones de remote control',
    'About':'Información',
    'Player and device info':'Información sobre Player y reproductor',
    'Donate <div class="btn" style="background-color:orange;">donate</div>':'Ayuda al proyecto <div class="btn" style="background-color:orange;">donate</div>',
    'Voluntary donation for the development of project':'Ayuda voluntaria al desarollo del proyecto',
    'Settings saved':'Configuración guardada',
    'no':'no',
    'yes':'sí',
    'Records':'Grabaciones',
    'Previous':'Previo',
    'Info':'Info',
    'Not reduce video when showing the list (bugfix)':'Sin reducir el tamaño de video durante la demostración de la lista (bugfix)',
    'Black screen while switching the channel':'Pantalla negra durante el cambio de canal',
    'PiP window size':'Tamaño de la ventanilla de PiP',
    'small':'pequeño',
    'medium':'medio',
    'large':'grande',
    'PiP window position':'Posición de la ventanilla de PiP',
    'top-right':'a la derecha-arriba',
    'bottom-right':'a la derecha-abajo',
    'left-bottom':'a la izquierda-abajo',
    'top-left':'a la izquierda-arriba',
    'Number of rows in lists':'Cantidad de lineas en listados',
    'Distance between lines in lists':'Distancia entre las lineas en listados',
    'Font type':'Tipo de letra',
    'volume':'volumen',
    'paging':'paginación',
    'Nothing':'Nada',
    'Exit':'Salir',
    'Joystick':'Joystick',
    'Button %1 function when viewing':'Función del botón %1 durante la vista',
    'Button function %1 when viewing archive':'Función del botón %1 durante la vista del archivo',
    'Channels':'Canales',
    'Remote (color buttons N/A)':'Remote control sin botones en color',
    'Remote (number buttons N/A)':'Remote control sin botones numéricos',
    'Timezone':'Zona horaria',
    'Sleep timer':'Temporizador de sueño',
    'off':'desactivado',
    '30 minutes':'30 minutos',
    '1 hour':'1 hora',
    '2 hours':'2 horas',
    'Infobar display timeout, s':'Timeout de demostración de infobar, s',
    '"Sliding" infobar':'"Sliding" infobar',
    'Interface transparency':'Transparecia de interface',
    'Volume step, %':'Paso de volumen, %',
    'List location':'Localización de listado',
    'right':'a la derecha',
    'left':'a la izquierda',
    'Color spectrum':'Espectro de colores',
    'select':'elegir',
    'Permanent clock on screen':'Reloj permanente en la pantalla',
    'Show channel number in list':'Mostrar el número de canal en listado',
    'Show picons in channel list':'Mostrar picones en el listado de canales',
    'Show channel name in list':'Mostrar el nombre de canal en listado',
    'Show progress in channel list':'Mostrar el progreso en listado de canales',
    'Show archive availability in list':'Mostrar la disponibilidad de archivo en listado',
    'Show scrollbar in list':'Mostrar scrollbar en listado',
    'Preview in channel list':'Vista previa en listado de canales',
    'always':'siempre',
    'on ':'por ',
    'Number of next TV programs in channel list':'Cantidad de programas siguientes en listado de canales',
    'Channel list editing style':'Estilo de editar canales',
    'All categories':'Todas categorías',
    '"Favorites"':'"Favoritos"',
    'Editor':'Editor',
    'built-in':'integrado',
    'native':'nativo',
    'HDMI-CEC support (on/off from TV)':'HDMI-СEC disponibilidad (activar/desactivar de TV)',
    'Type of player for streaming':'Tipo de Player para la reproducción',
    'Autostart of player':'Autostart de Player',
    'Buffer Size, s':'Tamaño de buffer, s',
    'Choose from':'Elegir de',
    'Settings':'Configuración',
    'Change value':'Cambiar el valor',
    'Save Settings':'Guardar configuración',
    'To begining':'Al comienzo',
    'Live':'En vivo',
    ' m ':' min ',
    ' s':' seg',
    '1 minute':'1 minuto',
    '10 Seconds':'10 segundos',
    'Go to':'Ir a',
    'Archive - begin':'Archivo - el comienzo de programa',
    'Pause':'Pause',
    'Play':'Reproducción',
    'Shutdown after %1 seconds<br/><br/>Cancel - any action':'Desactivar en %1 segundos<br/><br/>Cancelar - acción qualquiera',
    'Do you want to exit player?':'Desea Ud. salir de Player?',
    'Color':'Color',
    'Saturation':'Saturación',
    'Yellow':'Amarillo',
    'Green':'Verde',
    'Blue':'Azul',
    'Set':'Establecer',
    'Restart stream':'Reiniciar el stream',
    'Favorites':'Favoritos',
    'All':'Todos',
    '<br/>Processing the channel list...':'<br/>Procesamiento la lista de canales...',
    '<br/>Start playback...':'<br/>Empezar la reproducción...',
    '<br/>Channel list not received !!!':'<br/>La lista de canales lo está recibida!!!',
    'Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>':'La lista de canales lo está recibida!!!<br/><br/>Introduzca ñps datos de proveedor y reinicia el Player!!!<br/><br/>',
    'Error getting channel list !!!':'Error en obtener la lista de canales!!!',
    'system':'de sistema',
    'Choose provider':'Selecciona al proveedor',
    '<br>Rewind<br>':'<br>Rebobinar<br>',
    '<br>Menu':'<br>Menú',
    '<br>Pause<br>':'<br>Pausa<br>',
    '<br>Toggle<br>sound track':'<br>Cambiar la pista<br>de sonido',
    '<br>Live':'<br>En vivo',
    '<br>Previous<br>channel':'<br>Canal<br>anterior',
    '<br/><b>Failed to load provider script !!!</b>':'<br/><b>Error al cargar el script de proveedor!!!</b>',
    '<br/>Loading provider %1 script ...':'<br/>Carga de script de proveedor %1 ...',
    '<br/>Loading settings...':'<br/>Carga de configurcaión...',
    '<br/>Loading channel list...':'<br/>Carga de la lista de canales...',
    'Choose language':'Elegir el idioma',
    'Change interface language':'Cambiar el idioma de interfaz',
    'Aspect':'Aspecto',
    'Audio':'Pista de sonido',
    'Stalker portals':'Stalker portals',
    'm3u-m3u8 playlists':'m3u-m3u8 playlists',
    '<br/>Loading STB...':'<br/>Carga de STB...',
    '<br/>Setup STB...':'<br/>Configuración de STB...',
    'Save settings to storage':'Grabar la configuración a la memoria USB',
    'Load settings from storage':'Descargar configuración de la memoria USB',
    'Download':'Descargar',
    'Skip this version':'Omitir esta versión',
    'Volume control':'Control de vloumen',
    'Long button presses':'Largas presiones a botones',
    'Download new version Android App':'Descargar la nueva versión de Android App',
    'To access you must enter url, username and password!':'Para obtener el acceso hay que introducir URL, nombre de usuario y contraseña!',
    'Failed to load channel list!':'Error al cargar la lista de canales!',
    'Year':'Año',
    'Duration':'Duración',
    'Genre':'Género',
    'Country':'País',
    'Director':'Director',
    'Actors':'Actores',
    'Release date':'Fecha de streno',
    'Rating':'Rating',
    'Season':'Temporada',
    'Episodes':'Cantidad de episodios',
    'VOD':'Películas y video',
    'TV series':'Series',
    'Episode':'Episodio',
    'Download! Wait ...':'Descarga! Espera ...',
    'Server':'Servidor',
    'URL':'URL',
    'Username':'Nombre de usuario',
    'Password':'Contraseña',
    'Stream type':'Тipo de stream',
    'Account info':'Información de la cuenta',
    'Select server number from 1 to 6 to save data':'Elige el número de servidor desde 1 hasta 6 para guardar los datos',
    ' (after changing, restart player)':' (al aplicar los cambios hay que reiniciar el Player)',
    ' (after changing, switch the channel!)':' (al aplicar los cambios hay que cambiar de canal!)',
    'Enter URL of server':'Editar URL de servidor',
    'Enter username':'Editar el nombre de usuario',
    'Enter password':'Editar la contraseña',
    'Select stream type':'Elegir el tipo de stream',
    '??? No channel name':'??? No hay nombre de canal',
    'Playlist URL':'URL de playlist',
    'Archive hours':'Cantidad de horas de archivo',
    'Enter playlist URL':'Introducir URL de playlist',
    'Enter playlist archive hours':'Introducir la cantidad de horas de archivo para playlist',
    'show on-screen keyboard':'demostrar el teclado de la pantalla',
    'Sleep without leaving player':'Quedar dormido sin salir de Player',
    'PiP is not available!':'PiP no está disponible!',
    'NORMAL':'NORMAL',
    'ENLARGE':'AGRANDAR',
    'MAKE_WIDER':'EXTENDER',
    'NON_LINEAR_STRETCH':'EXTENSIÓN NO LINEAL',
    'NON_LINEAR_STRETCH_TO_FULL_SCREEN':'EXTENSIÓN NO LINEAL A PANTALLA COMPLETA',
    'MAKE_TALLER':'AUMENTO DE ALTITUD',
    'CUT_EDGES':'RECORTO DE ARISTAS',
    'FULL_SCREEN':'PANTALLA COMPLETA',
    'STRETCH_TO_FULL_SCREEN':'EXTENDER A PANTALLA COMPLETA',
    'Background color':'Color de fondo',
    'Brightness':'Intensidad',
    '3 hours':'3 horas',
    'Restart stream / Live':'Reiniciar el stream / En vivo',
    '- keyboard': '- teclado',
    'Media':'Media',
    'String for search':'Barra de búsqueda',
    'Playlist Name':'Nombre de playlist',
    'Enter playlist Name':'Introducir el nombre de playlist',
    'Media Library URL':'URL de librería media',
    'Enter Media Library URL':'Introducir URL de librería media',
    'Playlist':'Playlist',
    'Select playlist':'Elegir el playlist',
    'Edit':'Editar',
    'Load':'Cargar',
    'Edit playlist data':'Editar los datos de playlist',
    'Select portal':'Elegir portal',
    'Portal Name':'Nombre de portal',
    'Enter Portal Name':'Introducir el nombre de portal',
    'Edit portal data':'Editar los datos de portal',
    'without':'sin',
    'Settings STB':'Configuración de STB',
    'Soft audio render':'Decodificar el sonido por medios programmáticos',
    'Long press horizontal arrows for volume control':'Control de volumen por mantener presionadas las flechas horizontales',
    'Yes':'Sí',
    'Back':'Atrás',
    'Show providers?':'Mostrar a los proveedores?',
    'Hide providers?':'Ocular la elección de proveedores?',
    'Show provider settings?':'Mostrar la configuración de proveedor?',
    'Hide provider settings?':'Ocultar la configuración de proveedor?',
    'Clear all settings?':'Borrar la configuración?',
    'Timer':'Temporizador',
    'Set timer?':'Activar temporizador?',
    'Remove timer?':'Eliminar temporizador?',
    'Timer: switch to channel?':'Temporizador: cambiar al canal?',
    ' (if archive exists)':' (si está disponible el archivo de canal)',
    'Preffered audio track':'Banda sonora preferible',
    'Information':'Información',
    'Lists settings':'Configuración de listas',
    'Channel list settings':'Configuración de lista de canales',
    'Buttons settings':'Configuración de botones de control remoto',
    'Subtitle':'Subtítulos',
    'Switch subtitle':'Cambiar los subtíilos',
    'Off':'Desactivar',
    'Not found':'No encontrado',
    'History of watched movies':'Historia de vistas prévias',
    'Continue watching?':'Continuar de mirar?',
    'Add to favorites':'Añadir a favoritos',
    'Delete':'Eliminar',
    'Info about current stream':'Información sobre el flujo corriente',
    'Stop':'Stop',
    'Playlist file':'Archivo de playlist',
    'Select playlist file':'Selección de archivo de playlist',
    'Graphical indication':'Indicación gráfica',
    'Background color of selected item':'Color de trasfondo de elemento seleccionado ',
    'Default':'Predeterminado',
    'Not supported!':'No es compatible!',
    'Menu items settings':'Configuración de los elementos de menú',
    'Select menu items':'Elegir los elementos de menú',
    'Protect Adult Channels':'Protección de "canales para adultos"',
    'Protect Settings':'Protección de configuración',
    'Protect Change Provider':'Protección del cambio de proveedor',
    'Infobar settings':'Configuración de infobar',
    'Show when switching':'Mostrar durante el cambio de canal',
    'Show when changing program':'Mostrar durante el cambio de programa',
    'Show when rewind':'Mostrar durante el rebobinar',
    'Archive. Category: ':'Archivo. Categoría: ',
    'Sort channels':'Ordenar canales',
    '"As Is"':'"Así como es"',
    'Load playlist':'Cargar el playlist',
    ' (after changing, load playlist)':' (después del cambio, cargar el playlist)',
    'Statistics of current stream':'Estadísticas del flujo corriente',
    'Search':'Búsqueda',
// 14.6
    'Behavior of %1/%2 buttons in lists':'Comportamiento de botones %1/%2 en listados',
    'begin/end':'principio/final',
    'Position shift -10 seconds after pause':'Cambio de posición en -10 segundos después de pausa',
    'Remember previous channels':'Recordar canales anteriores',
    'History in Media Library':'Historia de vistas previas en Mediateca',
// 5.11
    'Manage settings':'Administrar la configuración',
    'Save settings':'Guardar la configuración',
    'Load settings':'Cargar la configuración',
    'Clear settings':'Borrar la configuración',
    'Send settings':'Opciones de envio de configuración',
    'Settings sended!':'La configuración está enviada!',
    'For download settings file open':'Para descargar el archivo de configuración ábran',
    'and enter code':'e introduzcan código',
    'or scan':'o escaneén',
    'Send request':'Enviar la demanda al servidor',
    'Request sended!':'La demanda está enviada!',
    'For upload settings file open':'Para cargar el archivo de configuración ábran',
    'Enter Provider Code':'Entrar el código de proveedor',
    'Error Code!':'Error del código!!!',
    'For enter value open':'Para entrar el vlor ábran',
    'First Run Setup':'Configuración durante el primer lanzamiento',
    'Enter Provider Code on PC or Phone':'Entrar el código de proveedor en ordenador o en móvil',
    'Manual setup':'Configuración manual',
    'Access settings':'Configuración de acceso',
// 26.1
    'Script':'Guión',
    'Producer':'Productor',
    'Operator':'Camarógrafo',
    'Composer':'Compositor',
    'Artist':'Artista',
    'Installation':'Postproducción',
    'Budget':'Presupuesto',
    'Audience':'Audiencia',
    'Premiere world':'Estreo mundial',
    'Display settings':'Parámetros derepresentación',
    'Age':'Edad',
    'Sort':'Ordenar',
    'by name':'por nombre',
    'by adding':'por tiempo de agregar',
    'Order':'Orden',
    'asc':'por ascendente',
    'desc':'por descedente',
    'Language':'Idioma',
    'Quality':'Calidad',
    'Show program name':'Mostrar el nombre de programa',
    'Show description':'Mostrar la descripción de programa',
    'transparent':'transparentes',
}
