keyStrings = {
    'lang':'Türkçe',
    'alhabet':'abcçdefgğhiıjklmnoöprsştuüvyz',
    'Channel list. Category: ':'Kanal listesi. Kategori: ',
    'EPG':'Yayın akışı',
    'Category':'Kategoriler',
    'Actions':'İşlemler',
    'Description':'Açıklama',
    'Open in PiP':'PiP olarak aç',
    'Move channel up':'Kanalı yukarı taşı',
    'Move channel down':'Kanalı aşağı taşı',
    'Delete channel':'Kanalı sil',
    'Add channel to category':'Kanalı kategoriye ekle',
    'Add channel to favorites':'Kanalı favorilere ekle',
    'Channel parental control':'Kanalın ebeveyn kontrolü',
    'Channel is not available!!!':'Kanal mevcut değil!!!',
    'min':'dk',
    'Channel ':'Kanal ',
    ' added to category ':' kategoriye eklendi ',
    ' added to favorites':' favorilere eklendi',
    'Favorites':'Favoriler',
    'Select category to add channel':'Kanalın ekleneceği kategoriyi seçin',
    'Enter parental code':'Ebeveyn kontrol kodunu girin',
    'Wrong parental code !!!':'Yanlış ebeveyn kontol kodu !!!',
    '<br>Up<br>':'<br>Yukarı<br>',
    '<br>Delete':'<br>Sil',
    '<br>Add<br>to favorites':'<br>Favorilere<br>ekle',
    '<br>Add<br>to category':'<br>Kategoriye<br>ekle',
    '<br>Parental<br>Control':'<br>Ebeveyn<br>kontrolü',
    '<br>Down':'<br>Aşağı',
    'Close':'Kapat',
    'Edit category name':'Kategori ismini değiştir',
    'Category %1 already exists!':'%1 kategorisi zaten mevcut!',
    'Enter name for new category':'Yeni kategori ismini girin',
    '<br>More...<br>':'<br>Daha fazla...<br>',
    '<br>Rename':'<br>İsmini değiştir',
    '<br>Copy<br>category':'<br>Kategoriyi<br>kopyala',
    '<br>Back<br>':'<br>Geri<br>',
    '<br>Create<br>category':'<br>Kategori<br>oluştur',
    'Category selection':'Kanal kategorilerini seçin',
    'Menu':'Menü',
    'Channel list':'Kanal listesi',
    'Move category up':'Kategoriyi yukarı taşı',
    'Move category down':'Kategoriyi aşağı taşı',
    'Create category':'Kategori oluştur',
    'Rename category':'Kategori ismini değiştir',
    'Copy category':'Kategoriyi kopyala',
    'Delete category':'Kategoriyi sil',
    'Su Mo Tu We Th Fr Sa':'Paz Pzt Sal Çar Per Cum Cmt',
    'EPG and archive. Channel: ':'Yayın akışı ve arşiv. Kanal: ',
    'By alphabet':'Alfabetik',
    'Archive. Channel: ':'Arşiv. Kanal: ',
    'By time':'Yayın zamanına göre',
    'Player info:':'Oynatıcı hakkında:',
    'Device info:':'Cihaz hakkında:',
    '- switch:':'- değiştir:',
    '- erase':'- sil',
    '- move cursor':'- imleci hareket ettir',
    '- return without save':'- kaydetmeden çık',
    '- save':'- kaydet',
    'Return to previous channel':'Önceki kanala geri dön',
    'Call PiP / PiP exchange':'PiP aç / PiP kaynaklarını değiştir',
    'Info about TV program':'TV program bilgisini göster',
    'Show player menu':'Oynatıcı menüsünü göster',
    'Interface settings':'Arayüz ayarları',
    'Show channel selection list':'Kanal seçme listesini göster',
    'Hide / Return':'Gizle / Geri dön',
    'Exit player':'Oynatıcıdan çık',
    'Show EPG and archive for channel':'Kanalın yayın akışını ve arşivini göster',
    'Channel category selection':'Kanal kategorisini seç',
    'Toggle Aspect Ratio':'Ekranın en/boy oranını değiştir (Aspect Ratio)',
    'Toggle Zoom Mode':'Yakınlaştırma (zoom) modunu değiştir',
    'Switch sound track':'Ses parçasını değiştir',
    'In live mode: <br/>':'Canlı yayın modunda:<br/>',
    'Channel selection by number':'Kanalı numarasıyla seç',
    'Timeshift: to start of TV program':'Geri al: program başına',
    'Timeshift: one minute back':'Geri al: 1 dk',
    '<br/><br/>In archive mode:<br/>':'<br/><br/>Arşiv izleme modunda:<br/>',
    'Pause/Play':'Duraklat/Oynat',
    'Stop playback and return to In live mode':'Oynatmayı durdur ve canlı yayına dön',
    'To start of TV program / Previous TV program':'Program başına / Önceki program',
    'Next TV program':'Sonraki program',
    'Back / Forward for 1 minute':'1 dk Geri / İleri ',
    'Back / Forward for 15 seconds':'15 sn Geri / İleri',
    'Back / Forward for 3 minutes':'3 dk Geri / İleri',
    'Back / Forward for 10 minutes':'10 dk Geri / İleri',
    'Show rewind window':'Geri/İleri sarma penceresini göster',
    'Description of remote control buttons':'Uzaktan kumanda tuşlarının açıklaması',
    'Description of remote control buttons depending on the view mode':'İzleme moduna bağlı olarak uzaktan kumanda tuşlarının açıklaması',
    'Set parental code':'Ebeveyn kontrol kodunu oluştur',
    'Repeat parental code':'Ebeveyn kontrol kodunu tekrar gir',
    'Show list of channel archive records':'Kanalın arşiv kayıtlarının listesini göster',
    'Show list of channel archive records without duplication':'Kanalın arşiv kayıtlarının listesini "tekrarsız" göster',
    'Show Media Library':'Medya kütüphanesini göster',
    'Rewind':'Geri/İleri sar',
    'Close PiP':'PiP kapat',
    'Parental control':'Ebeveyn kontrolü',
    'Change provider':'Servis sağlayıcıyı değiştir',
    'Change provider - you can change the provider, and it will be remembered at the next start of player!':'Servis sağlayıcıyı değiştir - Başka bir servis sağlayıcıyı seçebilirisiniz ve seçiminiz kaydedilir!',
    'Restart player':'Oynatıcıyı yeniden başlat',
    // 'Restart player - after changing provider settings (as example)':'Oynatıcıyı yeniden başlat - örneğin servis sağlayıcı ayarlarını değiştirdikten sonra',
    'Description of remote control buttons':'Uzaktan kumanda tuşlarının açıklaması',
    'About':'Hakkında',
    'Player and device info':'Oynatıcı ve cihaz hakkında',
    'Donate <div class="btn" style="background-color:orange;">donate</div>':'Bağış yap <div class="btn" style="background-color:orange;">donate</div>',
    'Voluntary donation for the development of project':'Projenin gelişimi için gönüllü bağış yap',
    'Settings saved':'Ayarlar kaydedildi',
    'no':'hayır',
    'yes':'evet',
    'Records':'Kayıtlar',
    'Previous':'Önceki',
    'Info':'Bilgi',
    'Not reduce video when showing the list (bugfix)':'Liste gösterilirken videoyu küçültme (bugfix)',
    'Black screen while switching the channel':'Kanal değiştirirken siyah ekran göster',
    'PiP window size':'PiP penceresinin boyutu',
    'small':'küçük',
    'medium':'orta',
    'large':'büyük',
    'PiP window position':'PiP penceresinin konumu',
    'top-right':'sağ üst',
    'bottom-right':'sağ alt',
    'left-bottom':'sol alt',
    'top-left':'sol üst',
    'Number of rows in lists':'Listelerdeki satır sayısı',
    'Distance between lines in lists':'Listelerdeki satır aralıkları',
    'Font type':'Yazı tipi',
    'volume':'ses seviyesi',
    'paging':'sayfalama',
    'Nothing':'Hiçbir şey',
    'Exit':'Çık',
    'Joystick':'Kumanda kolu',
    'Button %1 function when viewing':'İzleme modunda %1 tuşunun fonksiyonu',
    'Button function %1 when viewing archive':'Arşiv izleme modunda %1 tuşunun fonksiyonu',
    'Channels':'Kanallar',
    'Remote (color buttons N/A)':'Kumanda (renkli tuş yok)',
    'Remote (number buttons N/A)':'Kumanda (sayısal tuş yok)',
    'Timezone':'Saat dilimi',
    'Sleep timer':'Uyku zamanlama',
    'off':'kapalı',
    '30 minutes':'30 dk',
    '1 hour':'1 saat',
    '2 hours':'2 saat',
    'Infobar display timeout, s':'Bilgi çubuğu görüntüleme zaman aşımı, sn',
    '"Sliding" infobar':'"Kayan" bilgi çubuğu',
    'Interface transparency':'Arayüz şeffaflığı',
    'Volume step, %':'Ses değişim kesiti, %',
    'List location':'Liste konumu',
    'right':'sağ',
    'left':'sol',
    'Color spectrum':'Renk gaması',
    'select':'seçin',
    'Permanent clock on screen':'Ekranda kalıcı saat',
    'Show channel number in list':'Kanal numarasını listede göster',
    'Show picons in channel list':'Kanal listesinde pikonları göster',
    'Show channel name in list':'Kanal ismini listede göster',
    'Show progress in channel list':'Kanal listesinde program ilerlemesini göster',
    'Show archive availability in list':'Arşiv varlığını listede göster',
    'Show scrollbar in list':'Listede kaydırma çubuğunu göster',
    'Preview in channel list':'Kanal listesinde ön izleme',
    'always':'her zaman',
    'on ':'için bas - ',
    'Number of next TV programs in channel list':'Kanal listesinde sonraki TV programlarının sayısı',
    'Channel list editing style':'Kanal listesi düzenleme şekli',
    'All categories':'Tüm kategoriler',
    '"Favorites"':'"Favoriler"',
    'Editor':'Düzenleyici',
    'built-in':'dahili',
    'native':'yerel',
    'HDMI-CEC support (on/off from TV)':'HDMI-СEC desteği (TV\'den aç/kapat)',
    'Type of player for streaming':'Yayınlar için oynatıcı türü',
    'Autostart of player':'Açılışta otomatik başlatma',
    'Buffer Size, s':'Arabellek boyutu, sn',
    'Choose from':'Seçenekler',
    'Settings':'Ayarlar',
    'Change value':'Değeri değiştir',
    'Save Settings':'Ayarları kaydet',
    'To begining':'Başa sar',
    'Live':'Canlı yayın',
    ' m ':' dk ',
    ' s':' sn',
    '1 minute':'1 dk',
    '10 Seconds':'10 sn',
    'Go to':'Git',
    'Archive - begin':'Arşiv - program başlangıcı',
    'Pause':'Duraklat',
    'Play':'Oynat',
    'Shutdown after %1 seconds<br/><br/>Cancel - any action':'Oynatıcı %1 sn sonra otomatik kapanacaktır<br/><br/>İptal için herhangi bir işlem yapın',
    'Do you want to exit player?':'Oynatıcıdan çıkmak istiyor musunuz?',
    'Color':'Renk',
    'Saturation':'Doygunluk',
    'Yellow':'Sarı',
    'Green':'Yeşil',
    'Blue':'Mavi',
    'Set':'Ayarla',
    'Restart stream':'Yayını yeniden başlat',
    'Favorites':'Favoriler',
    'All':'Tümü',
    '<br/>Processing the channel list...':'<br/>Kanal listesi işleniyor...',
    '<br/>Start playback...':'<br/>Oynatmayı başlat...',
    '<br/>Channel list not received !!!':'<br/>Kanal listesi alınamadı!!!',
    'Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>':'Kanal listesi alınamadı!!!<br/><br/>Servis sağlayıcı bilgilerini girin ve oynatıcıyı yeniden başlatın!!!<br/><br/>',
    'Error getting channel list !!!':'Kanal listesi alım hatası!!!',
    'system':'sistem',
    'Choose provider':'Servis sağlayıcıyı seçin',
    '<br>Rewind<br>':'<br>Geri/İleri sar<br>',
    '<br>Menu':'<br>Menü',
    '<br>Pause<br>':'<br>Duraklat<br>',
    '<br>Toggle<br>sound track':'<br>Ses parçasını<br>değiştir',
    '<br>Live':'<br>Canlı yayın',
    '<br>Previous<br>channel':'<br>Önceki<br>kanal',
    '<br/><b>Failed to load provider script !!!</b>':'<br/><b>Servis sağlayıcı verileri yüklenemedi!!!</b>',
    '<br/>Loading provider %1 script ...':'<br/> %1 servis sağlayıcısının verileri yükleniyor...',
    '<br/>Loading settings...':'<br/>Ayarlar yükleniyor...',
    '<br/>Loading channel list...':'<br/>Kanal listesi yükleniyor...',
    'Choose language':'Dili seçin',
    'Change interface language':'Arayüz dilini değiştir',
    'Aspect':'En/boy oranı',
    'Audio':'Ses parçası',
    'Stalker portals':'Stalker portalleri',
    'm3u-m3u8 playlists':'m3u-m3u8 listeleri',
    '<br/>Loading STB...':'<br/>STB yükleniyor...',
    '<br/>Setup STB...':'<br/>STB ayarlanıyor...',
    'Save settings to storage':'Ayarları USB-sürücüsüne kaydet',
    'Load settings from storage':'Ayarları USB-sürücüsünden geri yükle',
    'Download':'İndir',
    'Skip this version':'Bu sürümü atla',
    'Volume control':'Ses ayarı',
    'Long button presses':'Tuşlara uzun basmalar',
    'Download new version Android App':'Yeni sürüm arayüz indirin',
    'To access you must enter url, username and password!':'Erişmek için URL, kullanıcı adı ve şifre girmelisiniz!',
    'Failed to load channel list!':'Kanal listesi yüklenemedi!',
    'Year':'Yıl',
    'Duration':'Süre',
    'Genre':'Tür',
    'Country':'Ülke',
    'Director':'Yönetmen',
    'Actors':'Aktörler',
    'Release date':'Çıkış tarihi',
    'Rating':'Puan',
    'Season':'Sezon',
    'Episodes':'Bölüm sayısı',
    'VOD':'Film ve videolar',
    'TV series':'Diziler',
    'Episode':'Bölüm',
    'Download! Wait ...':'Yükleniyor! Bekleyin ...',
    'Server':'Sunucu',
    'URL':'URL',
    'Username':'Kullanıcı adı',
    'Password':'Şifre',
    'Stream type':'Yayın türü',
    'Account info':'Hesap bilgisi',
    'Select server number from 1 to 6 to save data':'Verilerin kaydedileceği sunucu numarasını seçin (1 ile 6 arası)',
    ' (after changing, restart player)':' (değiştirdikten sonra oynatıcıyı yeniden başlatın)',
    ' (after changing, switch the channel!)':' (değiştirdikten sonra kanalı değiştirin!)',
    'Enter URL of server':'Sunucu adresini değiştir',
    'Enter username':'Kullanıcı adını değiştir',
    'Enter password':'Şifre değiştir',
    'Select stream type':'Yayın türünü seçin',
    '??? No channel name':'??? kanal ismi yok',
    'Playlist URL':'Çalma listesi adresi',
    'Archive hours':'Arşiv saat sayısı',
    'Enter playlist URL':'Çalma listesi adresini gir',
    'Enter playlist archive hours':'Çalma listesinin arşiv saat sayısını girin',
    'show on-screen keyboard':'ekran klavyesini göster',
    'Sleep without leaving player':'Oynatıcıdan çıkmadan uyku moduna al',
    'PiP is not available!':'PiP kullanılamaz!',
    'NORMAL':'NORMAL',
    'ENLARGE':'BÜYÜT',
    'MAKE_WIDER':'GENİŞLET',
    'NON_LINEAR_STRETCH':'DOĞRUSAL OLMAYAN UZATMA',
    'NON_LINEAR_STRETCH_TO_FULL_SCREEN':'DOĞRUSAL OLMAYAN TAM EKRAN UZATMA',
    'MAKE_TALLER':'UZAT',
    'CUT_EDGES':'KENARLARI KES',
    'FULL_SCREEN':'TAM EKRAN',
    'STRETCH_TO_FULL_SCREEN':'TAM EKRANA UZAT',
    'Background color':'Arkaplan rengi',
    'Brightness':'Parlaklık',
    '3 hours':'3 saat',
    'Restart stream / Live':'Yayını yeniden başlat / Canlı yayın',
    '- keyboard': '- klavye',
    'Media':'Medya kütüphanesi',
    'String for search':'Aranacak satır',
    'Playlist Name':'Çalma listesi ismi',
    'Enter playlist Name':'Çalma listesi ismini gir',
    'Media Library URL':'Medya kütüphanesi adresi',
    'Enter Media Library URL':'Medya kütüphanesi adresini gir',
    'Playlist':'Çalma listesi',
    'Select playlist':'Çalma listesini seç',
    'Edit':'Düzenle',
    'Load':'Yükle',
    'Edit playlist data':'Çalma listesi verilerini düzenleyin',
    'Select portal':'Portal seçin',
    'Portal Name':'Portal ismi',
    'Enter Portal Name':'Portal ismini gir',
    'Edit portal data':'Portal verilerini düzenle',
    'without':'olmadan',
    'Settings STB':'STB ayarları',
    'Soft audio render':'Yazılımsal ses çözme',
    'Long press horizontal arrows for volume control':'Yatay oklara uzun basarak ses seviyesini değiştir',
    'Yes':'Evet',
    'Back':'Geri',
    'Show providers?':'Servis sağlayıcı listesi gösterilsin mi?',
    'Hide providers?':'Servis sağlayıcı listesi gizlensin mi?',
    'Show provider settings?':'Servis sağlayıcı ayarları gösterilsin mi?',
    'Hide provider settings?':'Servis sağlayıcı ayarları gizlensin mi?',
    'Clear all settings?':'Tüm ayarlar silinsin mi?',
    'Timer':'Zamanlayıcı',
    'Set timer?':'Zamanlayıcı ayarlansın mı?',
    'Remove timer?':'Zamanlayıcı silinsin mi?',
    'Timer: switch to channel?':'Zamanlayıcı: kanal değiştirilsin mi?',
    ' (if archive exists)':' (kanal arşivi mevcut ise)',
    'Preffered audio track':'Tercih edilen ses parçası',
    'Information':'Bilgi',
    'Lists settings':'Liste ayarları',
    'Channel list settings':'Kanal listesi ayarları',
    'Buttons settings':'Uzaktan kumanda tuş ayarları',
    'Subtitle':'Altyazı',
    'Switch subtitle':'Altyazı değiştir',
    'Off':'Kapalı',
    'Not found':'Bulunamadı',
    'History of watched movies':'İzleme geçmişi',
    'Continue watching?':'Kaldığı yerden devam et?',
    'Add to favorites':'Favorilere ekle',
    'Delete':'Sil',
    'Info about current stream':'Mevcut yayın hakkında bilgi',
    'Stop':'Durdur',
    'Playlist file':'Çalma listesi dosyası',
    'Select playlist file':'Çalma listesi dosyasını seç',
    'Graphical indication':'Grafik gösterge',
    'Background color of selected item':'Seçili öğenin arkaplan rengi',
    'Default':'Varsayılan',
    'Not supported!':'Desteklenmiyor!',
    'Menu items settings':'Menü öğesi ayarları',
    'Select menu items':'Menü öğelerini seçin',
    'Protect Adult Channels':'"18+" kanalları kilitle',
    'Protect Settings':'Ayarları kilitle',
    'Protect Change Provider':'Servis sağlayıcı değiştirmesini kilitle',
    'Infobar settings':'Bilgi çubuğu ayarları',
    'Show when switching':'Kanal değiştirirken göster',
    'Show when changing program':'Program değiştirirken göster',
    'Show when rewind':'Geri/İleri sararken göster',
    'Archive. Category: ':'Arşiv. Kategori: ',
    'Sort channels':'Kanalları sırala',
    '"As Is"':'"Olduğu gibi"',
    'Load playlist':'Çalma listesi yükle',
    ' (after changing, load playlist)':' (değiştirdikten sonra çalma listesini yükle)',
    'Statistics of current stream':'Mevcut yayının istatistiği',
    'Search':'Arama',
// 14.6
    'Behavior of %1/%2 buttons in lists':'Listelerde %1/%2 tuşların işlevi',
    'begin/end':'baş/son',
    'Position shift -10 seconds after pause':'Duraklattıktan sonra 10 sn geri al',
    'Remember previous channels':'Önceki kanalları hatırla',
    'History in Media Library':'Medya kütüphanesinde izleme geçmişi',
// 5.11
    'Manage settings':'Ayarları yönet',
    'Save settings':'Ayarları kaydet',
    'Load settings':'Ayarları yükle',
    'Clear settings':'Ayarları temizle',
    'Send settings':'Ayarları sunucuya gönder',
    'Settings sended!':'Ayarlar sunucuya gönderildi!',
    'For download settings file open':'Ayarlar dosyasını indirmek için sayfayı açın',
    'and enter code':'ve kodu girin',
    'or scan':'veya tarayın',
    'Send request':'Sunucuya istek gönder',
    'Request sended!':'Sunucuya istek gönderildi!',
    'For upload settings file open':'Ayarlar dosyasını indirmek için sayfayı açın',
    'Enter Provider Code':'Distribütör kodunu girin',
    'Error Code!':'Hatalı kod!!!',
    'For enter value open':'Değeri girmek için sayfayı açın',
    'First Run Setup':'İlk kurulum ayarları',
    'Enter Provider Code on PC or Phone':'Distribütör kodunu bilgisayar veya telefonunuzdan girin',
    'Manual setup':'Manuel ayarlar',
    'Access settings':'Erişim ayarları',
// 26.1
    'Script':'Senaryo',
    'Producer':'Yapımcı',
    'Operator':'Kameraman',
    'Composer':'Besteci',
    'Artist':'Ressam',
    'Installation':'Montaj',
    'Budget':'Bütçe',
    'Audience':'Seyirci kitlesi',
    'Premiere world':'Dünya prömiyeri',
    'Display settings':'Ekran Ayarları',
    'Age':'Yaş',
    'Sort':'Sırala',
    'by name':'isme göre',
    'by adding':'eklenme tarihine göre',
    'Order':'Sıra',
    'asc':'artan',
    'desc':'azalan',
    'Language':'Dil',
    'Quality':'Kalite',
    'Show program name':'Program ismini göster',
    'Show description':'Program detayını göster',
    'transparent':'şeffaf',
// 23.3
    'Rewind step by buttons %1/%2':'%1/%2 tuşlarıylala Geri/İleri sarma adım boyutu',
}
