keyStrings = {
    'lang':'Українська',
    'alhabet':'абвгґдеєжзиіїйклмнопрстуфхцчшщьюя',
    'Channel list. Category: ':'Список каналів. Категорія: ',
    'EPG':'Програма',
    'Category':'Категорії',
    'Actions':'Дії',
    'Description':'Опис',
    'Open in PiP':'Відкрити у PiP',
    'Move channel up':'Пересунути канал догори',
    'Move channel down':'Пересунути канал вниз',
    'Delete channel':'Видалити канал',
    'Add channel to category':'Додати канал до категорії',
    'Add channel to favorites':'Додати канал у Вибране',
    'Channel parental control':'Батьківський контроль каналу',
    'Channel is not available!!!':'Канал не доступний!!!',
    'min':'хвилин',
    'Channel ':'Канал ',
    ' added to category ':' доданий до категорії ',
    ' added to favorites':' доданий у Вибране',
    'Favorites':'Вибране',
    'Select category to add channel':'Вибір категорії для додавання каналу',
    'Enter parental code':'Уведіть батьківський код',
    'Wrong parental code !!!':'Невірний батьківський код !!!',
    '<br>Up<br>':'<br>Догори<br>',
    '<br>Delete':'<br>Видалити',
    '<br>Add<br>to favorites':'<br>Додати<br>у Вибране',
    '<br>Add<br>to category':'<br>Додати<br>до категорії',
    '<br>Parental<br>Control':'<br>Батьківський<br>контроль',
    '<br>Down':'<br>Вниз',
    'Close':'Закрити',
    'Edit category name':'Редагування назви категорії',
    'Category %1 already exists!':'Категорія %1 вже існує!',
    'Enter name for new category':'Уведіть назву для нової категорії',
    '<br>More...<br>':'<br>Еще...<br>',
    '<br>Rename':'<br>Змінити<br>назву',
    '<br>Copy<br>category':'<br>Копіювати<br>категорію',
    '<br>Back<br>':'<br>Назад<br>',
    '<br>Create<br>category':'<br>Створити<br>категорію',
    'Category selection':'Вибір категорії каналів',
    'Menu':'Меню',
    'Channel list':'Список каналів',
    'Move category up':'Пересунути категорію догори',
    'Move category down':'Пересунути категорію вниз',
    'Create category':'Створити категорію',
    'Rename category':'Змінити назву категорії',
    'Copy category':'Копіювати категорію',
    'Delete category':'Видалити категорію',
    'Su Mo Tu We Th Fr Sa':'Нд Пн Вт Ср Чт Пт Сб',
    'EPG and archive. Channel: ':'Програма та архів. Канал: ',
    'By alphabet':'За алфавітом',
    'Archive. Channel: ':'Архів. Канал: ',
    'By time':'За часом',
    'Player info:':'Інформація про плеєр:',
    'Device info:':'інформація про пристрій:',
    '- switch:':'- перемикання:',
    '- erase':'- витерти',
    '- move cursor':'- переміщення курсору',
    '- return without save':'- повернутися без зберігання',
    '- save':'- запам\'ятати',
    'Return to previous channel':'Повернення до попереднього каналу',
    'Call PiP / PiP exchange':'Виклик PiP / Обмін джерелами PiP',
    'Info about TV program':'Виклик інформації про передачу',
    'Show player menu':'Виклик меню плеєра',
    'Interface settings':'Налаштування інтерфейсу',
    'Show channel selection list':'Виклик списку вибору каналу',
    'Hide / Return':'Приховати інформацію / повернення',
    'Exit player':'Вихід з плеєра',
    'Show EPG and archive for channel':'Виклик програми передач та архіву каналу',
    'Channel category selection':'Вибір категорії каналів',
    'Toggle Aspect Ratio':'Перемкнути режим "Співвідношення сторін екрану" (Aspect Ratio)',
    'Toggle Zoom Mode':'Перемкнути режим збільшення',
    'Switch sound track':'Перемкнути доріжку звуку',
    'In live mode: <br/>':'У режимі перегляду прямого етера:<br/>',
    'Channel selection by number':'Вибір каналу за номером',
    'Timeshift: to start of TV program (if archive exists)':'Таймшифт: до початку передачі (за наявності архіву каналу)',
    'Timeshift: one minute back (if archive exists)':'Таймшифт: на хвилину назад (за наявності архіву каналу)',
    '<br/><br/>In archive mode:<br/>':'<br/><br/>У режимі перегляду архіву:<br/>',
    'Pause/Play':'Пауза/Відтворення',
    'Stop playback and return to In live mode':'Зупинити відтворення та повернутися до прямого етеру',
    'To start of TV program / Previous TV program':'До початку передачі / До попередньої передачі',
    'Next TV program':'До наступної передачі',
    'Back / Forward for 1 minute':'Назад / Вперед на 1 хвилину',
    'Back / Forward for 15 seconds':'Назад / Вперед на 15 секунд',
    'Back / Forward for 3 minutes':'Назад / Вперед на 3 хвилини',
    'Back / Forward for 10 minutes':'Назад / Вперед на 10 хвилин',
    'Show rewind window':'Виклик віконця перемотування',
    'Description of remote control buttons':'Опис функцій кнопок пульту',
    'Description of remote control buttons depending on the view mode':'Опис функцій кнопок пульту, що залежать від режиму перегляду',
    'Set parental code':'Задайте батьківський код',
    'Repeat parental code':'Повторіть батьківський код',
    'Show list of channel archive records':'Виклик списку записів архіву каналу',
    'Show list of channel archive records without duplication':'Виклик списку записів архіву каналу без повторів',
    'Show Media Library':'Виклик медіатеки',
    'Rewind':'Перемотування',
    'Close PiP':'Закрити PiP',
    'Parental control':'Батьківський контроль',
    'Change provider':'Зміна провайдера',
    'Change provider - you can change the provider, and it will be remembered at the next start of player!':'Зміна провайдера - Ви можете змінити провайдера, і він буде запам\'ятований при наступному запуску!',
    'Restart player':'Перезапустити плеєр',
    // 'Restart player - after changing provider settings (as example)':'Перезапустити плеєр - наприклад, після зміни налаштувань провайдера',
    'Description of remote control buttons':'Опис кнопок пульту',
    'About':'Інформація',
    'Player and device info':'Інформація про плеєр та пристрій',
    'Donate <div class="btn" style="background-color:orange;">donate</div>':'Допомога проекту <div class="btn" style="background-color:orange;">donate</div>',
    'Voluntary donation for the development of project':'Добровільна допомога на розвиток проекту',
    'Settings saved':'Налаштування збережені',
    'no':'ні',
    'yes':'так',
    'Records':'Записи',
    'Previous':'Попередній',
    'Info':'Інфо',
    'Not reduce video when showing the list (bugfix)':'Не зменшувати відео при викликові списку (bugfix)',
    'Black screen while switching the channel':'Чорний екран при перемиканні каналу',
    'PiP window size':'Розмір віконця PiP',
    'small':'маленьке',
    'medium':'середнє',
    'large':'велике',
    'PiP window position':'Розташування віконця PiP',
    'top-right':'право-верх',
    'bottom-right':'право-низ',
    'left-bottom':'ліво-низ',
    'top-left':'ліво-верх',
    'Number of rows in lists':'Кількість рядків у списках',
    'Distance between lines in lists':'Відстань між рядками у списках',
    'Font type':'Тип шрифту',
    'volume':'гучність',
    'paging':'гортання',
    'Nothing':'Нічого',
    'Exit':'Вихід',
    'Joystick':'Джойстик',
    'Button %1 function when viewing':'Функція кнопки %1 при перегляді',
    'Button function %1 when viewing archive':'Функція кнопки %1 при перегляді архіву',
    'Channels':'Канали',
    'Remote (color buttons N/A)':'Пульт без кольорових кнопок',
    'Remote (number buttons N/A)':'Пульт без цифрових кнопок',
    'Timezone':'Часовий пояс',
    'Sleep timer':'Таймер сну',
    'off':'вимкнений',
    '30 minutes':'30 хвилин',
    '1 hour':'1 година',
    '2 hours':'2 години',
    'Infobar display timeout, s':'Таймаут показу инфобару, с',
    '"Sliding" infobar':'"Спливаючий" інфобар',
    'Interface transparency':'Прозорість інтерфейсу',
    'Volume step, %':'Крок гучності, %',
    'List location':'Розташування списку',
    'right':'справа',
    'left':'зліва',
    'Color spectrum':'Кольорова гама',
    'select':'оберіть',
    'Permanent clock on screen':'Постійний годинник на екрані',
    'Show channel number in list':'Показ номеру каналу у списку',
    'Show picons in channel list':'Показ піконів у списку каналів',
    'Show channel name in list':'Показ назви каналу у списку',
    'Show progress in channel list':'Показ прогресу у списку каналів',
    'Show archive availability in list':'Показ наявності архіву у списку',
    'Show scrollbar in list':'Показ скроллбара у списку',
    'Preview in channel list':'Прев\'ю у списку каналів',
    'always':'завжди',
    'on ':'по ',
    'Number of next TV programs in channel list':'К-ть наступних передач у списку каналів',
    'Channel list editing style':'Стиль редагування списків',
    'All categories':'Усі категорії',
    '"Favorites"':'"Вибране"',
    'Editor':'Редактор',
    'built-in':'вбудований',
    'native':'рідний',
    'HDMI-CEC support (on/off from TV)':'HDMI-СEC підтримка (увімк/вимк від ТВ)',
    'Type of player for streaming':'Тип плеєра для відтворення',
    'Autostart of player':'Старт плеєра при ввімкненні',
    'Buffer Size, s':'Розмір буфера, с',
    'Choose from':'Варіанти',
    'Settings':'Налаштування',
    'Change value':'Зміна значення',
    'Save Settings':'Зберегти налаштування',
    'To begining':'На початок',
    'Live':'Пряма трансляція',
    ' m ':' хв ',
    ' s':' сек',
    '1 minute':'1 хвилина',
    '10 Seconds':'10 секунд',
    'Go to':'Перейти',
    'Archive - begin':'Архів - початок передачі',
    'Pause':'Пауза',
    'Play':'Відтворення',
    'Shutdown after %1 seconds<br/><br/>Cancel - any action':'Вимкнення через %1 секунд<br/><br/>Відміна - будь-яка дія',
    'Do you want to exit player?':'Ви хочете вийти з плеєру?',
    'Color':'Колір',
    'Saturation':'Насиченість',
    'Yellow':'Жовтий',
    'Green':'Зелений',
    'Blue':'Блакитний',
    'Set':'Встановити',
    'Restart stream':'Рестарт потоку',
    'Favorites':'Вибрані',
    'All':'Усі',
    '<br/>Processing the channel list...':'<br/>Обробка списку каналів...',
    '<br/>Start playback...':'<br/>Старт відтворення...',
    '<br/>Channel list not received !!!':'<br/>Не отримано список каналів!!!',
    'Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>':'Не отримано список каналів!!!<br/><br/>Введіть дані провайдера та перезапустіть плеєр!!!<br/><br/>',
    'Error getting channel list !!!':'Помилка отримання списку каналів!!!',
    'system':'системний',
    'Choose provider':'Оберіть провайдера',
    '<br>Rewind<br>':'<br>Перемотування<br>',
    '<br>Menu':'<br>Меню',
    '<br>Pause<br>':'<br>Пауза<br>',
    '<br>Toggle<br>sound track':'<br>Перемкнути<br>зв.доріжку',
    '<br>Live':'<br>Прямий етер',
    '<br>Previous<br>channel':'<br>Попередній<br>канал',
    '<br/><b>Failed to load provider script !!!</b>':'<br/><b>Не вдалося завантажити скрипт провайдера!!!</b>',
    '<br/>Loading provider %1 script ...':'<br/>Завантаження скрипту провайдера %1 ...',
    '<br/>Loading settings...':'<br/>Завантаження налаштувань...',
    '<br/>Loading channel list...':'<br/>Завантаження списку каналів...',
    'Choose language':'Оберіть мову',
    'Change interface language':'Зміна мови інтерфейсу',
    'Aspect':'Аспект',
    'Audio':'Зв.доріжка',
    'Stalker portals':'Сталкер портали',
    'm3u-m3u8 playlists':'m3u-m3u8 плейлисти',
    '<br/>Loading STB...':'<br/>Завантаження STB...',
    '<br/>Setup STB...':'<br/>Налаштування STB...',
    'Save settings to storage':'Записати налаштування на флешку',
    'Load settings from storage':'Відновити налаштування з флешки',
    'Download':'Завантажити',
    'Skip this version':'Пропустити цю версію',
    'Volume control':'Регулювання гучності',
    'Long button presses':'Довгі натискання кнопок',
    'Download new version Android App':'Завантажити нову версію оболонки',
    'To access you must enter url, username and password!':'Для доступу необхідно ввести адресу, логін та пароль!',
    'Failed to load channel list!':'Не вдалося завантажити список каналів!',
    'Year':'Рік',
    'Duration':'Тривалість',
    'Genre':'Жанр',
    'Country':'Країна',
    'Director':'Режисер',
    'Actors':'У ролях',
    'Release date':'Дата виходу',
    'Rating':'Рейтинг',
    'Season':'Номер сезону',
    'Episodes':'К-ть епізодів',
    'VOD':'Фільми та відео',
    'TV series':'Серіали',
    'Episode':'Епізод',
    'Download! Wait ...':'Завантаження! Зачекайте ...',
    'Server':'Сервер',
    'URL':'Адреса',
    'Username':'Логін',
    'Password':'Пароль',
    'Stream type':'Тип потоків',
    'Account info':'Інформація про підписку',
    'Select server number from 1 to 6 to save data':'Оберіть номер сервера від 1 до 6 для збереження даних',
    ' (after changing, restart player)':' (після зміни потрібно перезапустити плеєр)',
    ' (after changing, switch the channel!)':' (після зміни перемкніть канал!)',
    'Enter URL of server':'Редагування адреси серверу',
    'Enter username':'Редагування логіну',
    'Enter password':'Редагування паролю',
    'Select stream type':'Оберіть тип потоків',
    '??? No channel name':'??? Немає назви каналу',
    'Playlist URL':'Адреса плейлиста',
    'Archive hours':'Кількість годин архіву',
    'Enter playlist URL':'Введення адреси плейлиста',
    'Enter playlist archive hours':'Введення кількості годин архіву для плейлиста',
    'show on-screen keyboard':'викликати екранну клавіатуру',
    'Sleep without leaving player':'Заснути без виходу з плеєру',
    'PiP is not available!':'PiP недоступий!',
    'NORMAL':'ЗВИЧАЙНИЙ',
    'ENLARGE':'ЗБІЛЬШЕННЯ',
    'MAKE_WIDER':'ЗБІЛЬШЕННЯ ШИРИНИ',
    'NON_LINEAR_STRETCH':'НЕЛІНІЙНЕ РОЗТЯГНЕННЯ',
    'NON_LINEAR_STRETCH_TO_FULL_SCREEN':'НЕЛІНІЙНЕ РОЗТЯГНЕННЯ НА ВЕСЬ ЕКРАН',
    'MAKE_TALLER':'ЗБІЛЬШЕННЯ ВИСОТИ',
    'CUT_EDGES':'ОБРІЗАННЯ КРАЇВ',
    'FULL_SCREEN':'ПОВНИЙ ЕКРАН',
    'STRETCH_TO_FULL_SCREEN':'РОЗТЯГУВАННЯ НА ВЕСЬ ЕКРАН',
    'Background color':'Колір фону',
    'Brightness':'Яскравість',
    '3 hours':'3 години',
    'Restart stream / Live':'Рестарт потоку / Пряма трансляція',
    '- keyboard': '- клавіатура',
    'Media':'медіатеки',
    'String for search':'Фраза для пошуку',
    'Playlist Name':'Назва плейлиста',
    'Enter playlist Name':'Введення назви плейлиста',
    'Media Library URL':'Адреса медіатеки',
    'Enter Media Library URL':'Введення адреси медіатеки',
    'Playlist':'Плейлист',
    'Select playlist':'Оберіть плейлист',
    'Edit':'Редагувати',
    'Load':'Завантажити',
    'Edit playlist data':'Редагувати дані плейлиста',
    'Select portal':'Оберіть портал',
    'Portal Name':'Назва портала',
    'Enter Portal Name':'Введення назви порталу',
    'Edit portal data':'Редагувати дані порталу',
    'without':'без',
    'Settings STB':'Налаштування STB',
    'Soft audio render':'Програмно декодувати звук',
    'Long press horizontal arrows for volume control':'Управління гучністю утриманням гор.стрілок',
    'Yes':'Так',
    'Back':'Назад',
    'Show providers?':'Показати вибір провайдерів?',
    'Hide providers?':'Приховати вибір провайдерів?',
    'Show provider settings?':'Показати налаштування провайдера?',
    'Hide provider settings?':'Приховати налаштування провайдера?',
    'Clear all settings?':'Очистити усі налаштування?',
    'Timer':'Таймер',
    'Set timer?':'Встановити таймер?',
    'Remove timer?':'Видалити таймер?',
    'Timer: switch to channel?':'Таймер: переключитися на канал?',
    ' (if archive exists)':' (за наявності архіву каналу)',
    'Preffered audio track':'Бажана звукова доріжка',
    'Information':'Інформація',
    'Lists settings':'Налаштування списків',
    'Channel list settings':'Налаштування списку каналів',
    'Buttons settings':'Налаштування кнопок пульту',
    'Subtitle':'Субтитри',
    'Switch subtitle':'Перемкнути субтитри',
    'Off':'Вимкнути',
    'Not found':'Відсутні',
    'History of watched movies':'Історія переглядів',
    'Continue watching?':'Продовжити перегляд?',
    'Add to favorites':'Додати в обране',
    'Delete':'Вилучити',
    'Info about current stream':'Інформація про поточний потік',
    'Stop':'Стоп',
    'Playlist file':'Файл плейліста',
    'Select playlist file':'Виберіть файл плейліста',
    'Graphical indication':'Графічна індикація',
    'Background color of selected item':'Колір фону виділення',
    'Default':'За замовчуванням',
    'Not supported!':'Не підтримується!',
    'Menu items settings':'Налаштування пунктів меню',
    'Select menu items':'Виберіть пункти меню',
    'Protect Adult Channels':'Захист "дорослих" каналів',
    'Protect Settings':'Захист параметрів',
    'Protect Change Provider':'Захист зміни провайдера',
    'Infobar settings':'Налаштування інфобара',
    'Show when switching':'Показати при перемиканні',
    'Show when changing program':'Показати при зміні програми',
    'Show when rewind':'Показати при перемотуванні',
    'Archive. Category: ':'Архів. Категорія: ',
    'Sort channels':'Сортування',
    '"As Is"':'"Як є"',
    'Load playlist':'Завантажити плейлист',
    ' (after changing, load playlist)':' (после изменения, завантажити плейлист)',
    'Statistics of current stream':'Статистика поточного потоку',
    'Search':'Пошук',
// 14.6
    'Behavior of %1/%2 buttons in lists':'Поведінка кнопок %1/%2 у списках',
    'begin/end':'початок/кінець',
    'Position shift -10 seconds after pause':'Зсув позиції на -10 секунд після паузи',
    'Remember previous channels':'Запам\'ятати попередніх каналів',
    'History in Media Library':'Історія переглядів в медіатеці',
// 5.11
    'Manage settings':'Керування налаштуваннями',
    'Save settings':'Зберегти налаштування',
    'Load settings':'Завантажити налаштування',
    'Clear settings':'Очистити налаштування',
    'Send settings':'Надіслати налаштування на сервер',
    'Settings sended!':'Налаштування надіслані на сервер!',
    'For download settings file open':'Для завантаження файлу налаштувань відкрийте',
    'and enter code':'та введіть код',
    'or scan':'або відскануйте',
    'Send request':'Відправити запит на сервер',
    'Request sended!':'Запит відправлений на сервер!',
    'For upload settings file open':'Для завантаження файлу налаштувань відкрийте',
    'Enter Provider Code':'Введення коду провайдера',
    'Error Code!':'Помилковий код!!!',
    'For enter value open':'Для введення значення відкрийте',
    'First Run Setup':'Налаштування при першому запуску',
    'Enter Provider Code on PC or Phone':'Введення коду провайдера на комп\'ютері або телефоні',
    'Manual setup':'Налаштування вручну',
    'Access settings':'Налаштування доступу',
// 26.1
    'Script':'Сценарій',
    'Producer':'Продюсер',
    'Operator':'Оператор',
    'Composer':'Композитор',
    'Artist':'Художник',
    'Installation':'Монтаж',
    'Budget':'Бюджет',
    'Audience':'Аудиторія',
    'Premiere world':'Світова прем\'єра',
    'Display settings':'Налаштування відображення',
    'Age':'Вік',
    'Sort':'Сортування',
    'by name':'за назвою',
    'by adding':'по додаванню',
    'Order':'Порядок',
    'asc':'зростання',
    'desc':'спадання',
    'Language':'Мова',
    'Quality':'Якість',
    'Show program name':'Показ назви передачі',
    'Show description':'Показ опису передачі',
    'transparent':'прозорі',
// 23.3
    'Rewind step by buttons %1/%2':'Крок перемотування кнопками %1/%2',
// 10.2
    'Show thumbnails':'Показати мініатюри',
}
